import { PrismaClient } from "../src/generated/prisma/client";
import { PrismaNeon } from "@prisma/adapter-neon";
import "dotenv/config";

const adapter = new PrismaNeon({
  connectionString: process.env.DATABASE_URL ?? "",
});
const prisma = new PrismaClient({ adapter });

const COLORS = [
  "#dbeafe",
  "#dcfce7",
  "#fef9c3",
  "#fce7f3",
  "#ede9fe",
  "#ffedd5",
  "#cffafe",
];

// Rich card tuple: [word, meaning (Vietnamese), ipa, explanation (Vietnamese)]
type Card4 = [string, string, string, string];

// ===== English_Basic_Life (en-US) — 100 everyday-life words =====
const englishBasicLife: Card4[] = [
  ["time", "thời gian", "/taɪm/", "Danh từ chỉ thời gian nói chung. 'What time is it?' = Mấy giờ rồi?"],
  ["day", "ngày", "/deɪ/", "Một ngày 24 giờ. 'today' = hôm nay, 'every day' = mỗi ngày."],
  ["night", "đêm", "/naɪt/", "Khoảng tối từ tối đến sáng. 'Good night' = chúc ngủ ngon."],
  ["morning", "buổi sáng", "/ˈmɔːrnɪŋ/", "'in the morning' = vào buổi sáng. 'Good morning' = chào buổi sáng."],
  ["week", "tuần", "/wiːk/", "7 ngày. 'last week' = tuần trước, 'next week' = tuần sau."],
  ["month", "tháng", "/mʌnθ/", "Một trong 12 tháng. Phát âm 'th' giọng gió."],
  ["year", "năm", "/jɪr/", "12 tháng. 'this year' = năm nay."],
  ["hour", "giờ (tiếng)", "/ˈaʊər/", "60 phút. 'h' câm, đọc như 'our'."],
  ["minute", "phút", "/ˈmɪnɪt/", "60 giây. 'Wait a minute' = đợi một chút."],
  ["water", "nước", "/ˈwɔːtər/", "Chất lỏng để uống. 'a glass of water' = một ly nước."],
  ["food", "thức ăn", "/fuːd/", "Đồ ăn nói chung. 'fast food' = đồ ăn nhanh."],
  ["money", "tiền", "/ˈmʌni/", "'make money' = kiếm tiền, 'spend money' = tiêu tiền."],
  ["house", "ngôi nhà", "/haʊs/", "Nơi ở. Khác 'home' (nhà - cảm giác thân thuộc)."],
  ["home", "nhà (mái ấm)", "/hoʊm/", "Nơi mình sống, mang nghĩa thân thuộc. 'go home' = về nhà."],
  ["family", "gia đình", "/ˈfæməli/", "Những người thân. 'my family' = gia đình tôi."],
  ["friend", "bạn bè", "/frend/", "'best friend' = bạn thân nhất."],
  ["work", "công việc / làm việc", "/wɜːrk/", "Vừa là danh từ vừa là động từ. 'go to work' = đi làm."],
  ["school", "trường học", "/skuːl/", "'go to school' = đi học."],
  ["car", "xe hơi", "/kɑːr/", "Phương tiện 4 bánh. 'drive a car' = lái xe."],
  ["road", "con đường", "/roʊd/", "Đường cho xe chạy. Khác 'street' (đường trong phố)."],
  ["city", "thành phố", "/ˈsɪti/", "'big city' = thành phố lớn."],
  ["country", "đất nước / vùng quê", "/ˈkʌntri/", "Vừa nghĩa quốc gia, vừa nghĩa nông thôn tùy ngữ cảnh."],
  ["people", "mọi người", "/ˈpiːpl/", "Số nhiều của 'person'. Luôn đi với động từ số nhiều."],
  ["person", "người (một người)", "/ˈpɜːrsn/", "Số ít. Số nhiều thường dùng 'people'."],
  ["man", "đàn ông", "/mæn/", "Số nhiều bất quy tắc: 'men'."],
  ["woman", "phụ nữ", "/ˈwʊmən/", "Số nhiều bất quy tắc: 'women' /ˈwɪmɪn/."],
  ["child", "đứa trẻ", "/tʃaɪld/", "Số nhiều bất quy tắc: 'children'."],
  ["name", "tên", "/neɪm/", "'What's your name?' = Bạn tên gì?"],
  ["love", "tình yêu / yêu", "/lʌv/", "Danh từ và động từ. 'I love you' = anh yêu em."],
  ["life", "cuộc sống", "/laɪf/", "Số nhiều: 'lives' /laɪvz/."],
  ["world", "thế giới", "/wɜːrld/", "'around the world' = khắp thế giới."],
  ["place", "nơi chốn", "/pleɪs/", "'a nice place' = một nơi đẹp."],
  ["thing", "vật / việc", "/θɪŋ/", "Từ chung chỉ đồ vật hoặc sự việc."],
  ["word", "từ / lời nói", "/wɜːrd/", "'in other words' = nói cách khác."],
  ["book", "quyển sách", "/bʊk/", "'read a book' = đọc sách."],
  ["phone", "điện thoại", "/foʊn/", "'call on the phone' = gọi điện thoại."],
  ["door", "cửa", "/dɔːr/", "'open the door' = mở cửa."],
  ["window", "cửa sổ", "/ˈwɪndoʊ/", "'look out the window' = nhìn ra cửa sổ."],
  ["table", "cái bàn", "/ˈteɪbl/", "'on the table' = trên bàn."],
  ["chair", "cái ghế", "/tʃer/", "'sit on a chair' = ngồi trên ghế."],
  ["bed", "cái giường", "/bed/", "'go to bed' = đi ngủ."],
  ["room", "căn phòng", "/ruːm/", "'living room' = phòng khách."],
  ["street", "đường phố", "/striːt/", "Đường trong khu dân cư có nhà hai bên."],
  ["bag", "túi / cặp", "/bæɡ/", "'a bag of rice' = một túi gạo."],
  ["clothes", "quần áo", "/kloʊz/", "Luôn số nhiều, không có 'a clothes'."],
  ["shoe", "chiếc giày", "/ʃuː/", "Thường dùng số nhiều 'shoes' (đôi giày)."],
  ["hand", "bàn tay", "/hænd/", "'shake hands' = bắt tay."],
  ["eye", "con mắt", "/aɪ/", "Số nhiều 'eyes'. Phát âm như chữ 'I'."],
  ["head", "cái đầu", "/hed/", "'headache' = đau đầu."],
  ["heart", "trái tim", "/hɑːrt/", "'h' đọc, chữ giống 'hurt' nhưng nghĩa khác."],
  ["color", "màu sắc", "/ˈkʌlər/", "Anh-Anh viết 'colour'. 'favorite color' = màu yêu thích."],
  ["light", "ánh sáng / đèn", "/laɪt/", "'turn on the light' = bật đèn."],
  ["air", "không khí", "/er/", "'fresh air' = không khí trong lành."],
  ["fire", "lửa", "/ˈfaɪər/", "'make a fire' = nhóm lửa."],
  ["sun", "mặt trời", "/sʌn/", "'sunny' = nắng."],
  ["moon", "mặt trăng", "/muːn/", "'full moon' = trăng tròn."],
  ["star", "ngôi sao", "/stɑːr/", "Cũng nghĩa 'ngôi sao' (người nổi tiếng)."],
  ["rain", "mưa", "/reɪn/", "'It's raining' = trời đang mưa."],
  ["wind", "gió", "/wɪnd/", "'windy' = nhiều gió."],
  ["tree", "cây", "/triː/", "Số nhiều 'trees'."],
  ["flower", "bông hoa", "/ˈflaʊər/", "'a bunch of flowers' = một bó hoa."],
  ["animal", "động vật", "/ˈænɪml/", "'wild animal' = động vật hoang dã."],
  ["dog", "con chó", "/dɔːɡ/", "'walk the dog' = dắt chó đi dạo."],
  ["cat", "con mèo", "/kæt/", "Tiếng kêu 'meow'."],
  ["bird", "con chim", "/bɜːrd/", "'birds fly' = chim bay."],
  ["fish", "con cá", "/fɪʃ/", "Số nhiều thường giữ nguyên 'fish'."],
  ["go", "đi", "/ɡoʊ/", "Quá khứ bất quy tắc 'went'. 'go home' = về nhà."],
  ["come", "đến", "/kʌm/", "Quá khứ 'came'. 'come here' = đến đây."],
  ["eat", "ăn", "/iːt/", "Quá khứ 'ate'. 'eat lunch' = ăn trưa."],
  ["drink", "uống", "/drɪŋk/", "Quá khứ 'drank'. Cũng là danh từ 'đồ uống'."],
  ["sleep", "ngủ", "/sliːp/", "Quá khứ 'slept'. 'go to sleep' = đi ngủ."],
  ["see", "nhìn thấy", "/siː/", "Quá khứ 'saw'. Khác 'look' (nhìn chủ động)."],
  ["hear", "nghe thấy", "/hɪr/", "Quá khứ 'heard'. Khác 'listen' (lắng nghe)."],
  ["speak", "nói", "/spiːk/", "Quá khứ 'spoke'. 'speak English' = nói tiếng Anh."],
  ["read", "đọc", "/riːd/", "Quá khứ viết giống nhưng đọc /red/."],
  ["write", "viết", "/raɪt/", "Quá khứ 'wrote'. 'w' câm."],
  ["walk", "đi bộ", "/wɔːk/", "'l' câm. 'go for a walk' = đi dạo."],
  ["run", "chạy", "/rʌn/", "Quá khứ 'ran'. 'go running' = đi chạy bộ."],
  ["buy", "mua", "/baɪ/", "Quá khứ 'bought'. Trái nghĩa 'sell'."],
  ["sell", "bán", "/sel/", "Quá khứ 'sold'. Trái nghĩa 'buy'."],
  ["open", "mở", "/ˈoʊpən/", "Trái nghĩa 'close'. 'open the door' = mở cửa."],
  ["close", "đóng", "/kloʊz/", "Động từ /kloʊz/, tính từ 'gần' đọc /kloʊs/."],
  ["start", "bắt đầu", "/stɑːrt/", "Đồng nghĩa 'begin'. Trái nghĩa 'stop/finish'."],
  ["stop", "dừng lại", "/stɑːp/", "'stop talking' = ngừng nói."],
  ["help", "giúp đỡ", "/help/", "'Can you help me?' = Bạn giúp tôi được không?"],
  ["want", "muốn", "/wɑːnt/", "'I want to go' = tôi muốn đi."],
  ["need", "cần", "/niːd/", "Mạnh hơn 'want'. 'I need water' = tôi cần nước."],
  ["like", "thích", "/laɪk/", "'I like it' = tôi thích nó. Cũng nghĩa 'giống như'."],
  ["know", "biết", "/noʊ/", "Quá khứ 'knew'. 'k' câm. 'I don't know' = tôi không biết."],
  ["think", "nghĩ", "/θɪŋk/", "Quá khứ 'thought'. 'I think so' = tôi nghĩ vậy."],
  ["say", "nói (điều gì)", "/seɪ/", "Quá khứ 'said' /sed/. 'say yes' = nói đồng ý."],
  ["good", "tốt", "/ɡʊd/", "So sánh bất quy tắc: better / best."],
  ["bad", "tệ / xấu", "/bæd/", "So sánh bất quy tắc: worse / worst."],
  ["big", "to / lớn", "/bɪɡ/", "Trái nghĩa 'small'. So sánh 'bigger'."],
  ["small", "nhỏ", "/smɔːl/", "Đồng nghĩa 'little'. Trái nghĩa 'big'."],
  ["new", "mới", "/nuː/", "Trái nghĩa 'old'. 'brand new' = mới toanh."],
  ["old", "cũ / già", "/oʊld/", "'How old are you?' = Bạn bao nhiêu tuổi?"],
  ["hot", "nóng", "/hɑːt/", "Trái nghĩa 'cold'. Cũng nghĩa 'cay'."],
  ["cold", "lạnh", "/koʊld/", "'I'm cold' = tôi thấy lạnh. Cũng nghĩa 'cảm lạnh'."],
  ["happy", "vui / hạnh phúc", "/ˈhæpi/", "Trái nghĩa 'sad'. 'Happy birthday' = chúc mừng sinh nhật."],
  ["easy", "dễ", "/ˈiːzi/", "Trái nghĩa 'hard/difficult'. 'easy to learn' = dễ học."],
];

// ===== English_Basic_Food (en-US) — 100 food & eating words =====
const englishBasicFood: Card4[] = [
  ["rice", "cơm / gạo", "/raɪs/", "Lương thực chính ở châu Á. Không đếm được, không thêm 's'."],
  ["bread", "bánh mì", "/bred/", "'a loaf of bread' = một ổ bánh mì."],
  ["meat", "thịt", "/miːt/", "Đồng âm với 'meet' (gặp). Thịt nói chung."],
  ["chicken", "thịt gà / con gà", "/ˈtʃɪkɪn/", "Vừa chỉ con gà vừa chỉ thịt gà."],
  ["beef", "thịt bò", "/biːf/", "Thịt từ con bò (cow)."],
  ["pork", "thịt heo", "/pɔːrk/", "Thịt từ con heo (pig)."],
  ["fish", "cá", "/fɪʃ/", "Vừa con cá vừa món cá. Số nhiều giữ nguyên."],
  ["egg", "trứng", "/eɡ/", "'fried egg' = trứng chiên, 'boiled egg' = trứng luộc."],
  ["milk", "sữa", "/mɪlk/", "Không đếm được. 'a glass of milk' = một ly sữa."],
  ["cheese", "phô mai", "/tʃiːz/", "Làm từ sữa. 'Say cheese!' = cười lên (khi chụp ảnh)."],
  ["butter", "bơ", "/ˈbʌtər/", "Phết lên bánh mì. Khác 'avocado' (quả bơ)."],
  ["sugar", "đường", "/ˈʃʊɡər/", "'s' đầu đọc như 'sh'. Vị ngọt."],
  ["salt", "muối", "/sɔːlt/", "Vị mặn. 'salt and pepper' = muối và tiêu."],
  ["pepper", "tiêu / ớt chuông", "/ˈpepər/", "'black pepper' = tiêu đen."],
  ["oil", "dầu ăn", "/ɔɪl/", "'cooking oil' = dầu nấu ăn."],
  ["soup", "súp / canh", "/suːp/", "'a bowl of soup' = một tô súp."],
  ["noodle", "mì / bún", "/ˈnuːdl/", "Thường số nhiều 'noodles'."],
  ["fruit", "trái cây", "/fruːt/", "Nói chung không đếm. 'fresh fruit' = trái cây tươi."],
  ["apple", "táo", "/ˈæpl/", "'an apple a day' = mỗi ngày một quả táo."],
  ["banana", "chuối", "/bəˈnænə/", "Nhấn âm giữa: ba-NA-na."],
  ["orange", "cam", "/ˈɔːrɪndʒ/", "Vừa quả cam vừa màu cam."],
  ["grape", "nho", "/ɡreɪp/", "Thường số nhiều 'grapes' (chùm nho)."],
  ["lemon", "chanh vàng", "/ˈlemən/", "Vị chua. Khác 'lime' (chanh xanh)."],
  ["mango", "xoài", "/ˈmæŋɡoʊ/", "Số nhiều 'mangoes'."],
  ["watermelon", "dưa hấu", "/ˈwɔːtərmelən/", "Ghép 'water' + 'melon'."],
  ["strawberry", "dâu tây", "/ˈstrɔːberi/", "Quả đỏ có hạt bên ngoài."],
  ["pineapple", "dứa / thơm", "/ˈpaɪnæpl/", "Ghép 'pine' + 'apple'."],
  ["vegetable", "rau củ", "/ˈvedʒtəbl/", "Đọc gọn 3 âm: VEJ-tə-bl."],
  ["tomato", "cà chua", "/təˈmeɪtoʊ/", "Anh-Mỹ /təˈmeɪtoʊ/, Anh-Anh /təˈmɑːtəʊ/."],
  ["potato", "khoai tây", "/pəˈteɪtoʊ/", "Số nhiều 'potatoes'."],
  ["carrot", "cà rốt", "/ˈkærət/", "Củ màu cam, tốt cho mắt."],
  ["onion", "hành tây", "/ˈʌnjən/", "Bắt đầu bằng âm 'ʌ' (như 'un')."],
  ["garlic", "tỏi", "/ˈɡɑːrlɪk/", "Gia vị thơm, củ trắng nhiều tép."],
  ["salad", "rau trộn / sa lát", "/ˈsæləd/", "Món rau sống trộn."],
  ["mushroom", "nấm", "/ˈmʌʃruːm/", "Mọc ẩm ướt, hình ô."],
  ["corn", "ngô / bắp", "/kɔːrn/", "'sweet corn' = ngô ngọt."],
  ["bean", "đậu", "/biːn/", "Thường số nhiều 'beans'."],
  ["meal", "bữa ăn", "/miːl/", "'three meals a day' = ba bữa một ngày."],
  ["breakfast", "bữa sáng", "/ˈbrekfəst/", "'have breakfast' = ăn sáng."],
  ["lunch", "bữa trưa", "/lʌntʃ/", "'have lunch' = ăn trưa."],
  ["dinner", "bữa tối", "/ˈdɪnər/", "Bữa chính buổi tối."],
  ["snack", "đồ ăn vặt", "/snæk/", "Ăn nhẹ giữa các bữa."],
  ["dessert", "món tráng miệng", "/dɪˈzɜːrt/", "Nhấn âm sau. Khác 'desert' (sa mạc)."],
  ["cake", "bánh ngọt", "/keɪk/", "'birthday cake' = bánh sinh nhật."],
  ["cookie", "bánh quy", "/ˈkʊki/", "Anh-Anh gọi là 'biscuit'."],
  ["candy", "kẹo", "/ˈkændi/", "Anh-Anh gọi là 'sweets'."],
  ["chocolate", "sô cô la", "/ˈtʃɑːklət/", "Đọc gọn 2 âm: CHOK-lət."],
  ["ice cream", "kem", "/ˈaɪs kriːm/", "Món lạnh ngọt."],
  ["coffee", "cà phê", "/ˈkɔːfi/", "'a cup of coffee' = một tách cà phê."],
  ["tea", "trà", "/tiː/", "'green tea' = trà xanh."],
  ["juice", "nước ép", "/dʒuːs/", "'orange juice' = nước cam."],
  ["wine", "rượu vang", "/waɪn/", "'red wine' = vang đỏ."],
  ["beer", "bia", "/bɪr/", "Đồ uống có cồn từ lúa mạch."],
  ["plate", "cái đĩa", "/pleɪt/", "Đĩa phẳng đựng thức ăn."],
  ["bowl", "cái tô / bát", "/boʊl/", "Đựng súp, cơm. 'l' nhẹ."],
  ["cup", "cái tách / cốc", "/kʌp/", "'a cup of tea' = một tách trà."],
  ["glass", "cái ly thủy tinh", "/ɡlæs/", "Cũng nghĩa 'thủy tinh, kính'."],
  ["spoon", "cái thìa / muỗng", "/spuːn/", "Dùng để múc."],
  ["fork", "cái nĩa", "/fɔːrk/", "Dùng để xiên thức ăn."],
  ["knife", "con dao", "/naɪf/", "'k' câm. Số nhiều 'knives'."],
  ["cook", "nấu ăn / đầu bếp", "/kʊk/", "Vừa động từ vừa danh từ (người nấu)."],
  ["bake", "nướng (lò)", "/beɪk/", "Nướng bánh trong lò. 'bakery' = tiệm bánh."],
  ["fry", "chiên / rán", "/fraɪ/", "'fried rice' = cơm chiên."],
  ["boil", "luộc / đun sôi", "/bɔɪl/", "'boiled egg' = trứng luộc."],
  ["taste", "nếm / vị", "/teɪst/", "'It tastes good' = nó ngon."],
  ["sweet", "ngọt", "/swiːt/", "Vị của đường, kẹo."],
  ["sour", "chua", "/ˈsaʊər/", "Vị của chanh, giấm."],
  ["bitter", "đắng", "/ˈbɪtər/", "Vị của cà phê đen."],
  ["spicy", "cay", "/ˈspaɪsi/", "Vị của ớt. 'hot' cũng nghĩa cay."],
  ["fresh", "tươi", "/freʃ/", "'fresh vegetables' = rau tươi."],
  ["delicious", "ngon tuyệt", "/dɪˈlɪʃəs/", "Mạnh hơn 'good'. 'It's delicious' = ngon quá."],
  ["hungry", "đói", "/ˈhʌŋɡri/", "'I'm hungry' = tôi đói."],
  ["thirsty", "khát", "/ˈθɜːrsti/", "'I'm thirsty' = tôi khát nước."],
  ["full", "no", "/fʊl/", "'I'm full' = tôi no rồi."],
  ["dish", "món ăn / cái đĩa", "/dɪʃ/", "Vừa món ăn vừa đĩa lớn."],
  ["menu", "thực đơn", "/ˈmenjuː/", "Danh sách món ở nhà hàng."],
  ["restaurant", "nhà hàng", "/ˈrestrɑːnt/", "Đọc gọn: RES-tront."],
  ["kitchen", "nhà bếp", "/ˈkɪtʃɪn/", "Nơi nấu ăn trong nhà."],
  ["recipe", "công thức nấu ăn", "/ˈresəpi/", "3 âm: RES-ə-pi. Hướng dẫn nấu món."],
  ["flour", "bột mì", "/ˈflaʊər/", "Đồng âm với 'flower' (hoa)."],
  ["honey", "mật ong", "/ˈhʌni/", "Cũng dùng gọi yêu 'cưng'."],
  ["jam", "mứt", "/dʒæm/", "Phết lên bánh mì. Cũng nghĩa 'kẹt xe'."],
  ["sauce", "nước sốt", "/sɔːs/", "'soy sauce' = nước tương."],
  ["soy sauce", "nước tương / xì dầu", "/ˈsɔɪ sɔːs/", "Gia vị mặn màu nâu của châu Á."],
  ["vinegar", "giấm", "/ˈvɪnɪɡər/", "Chất lỏng chua dùng nêm."],
  ["flavor", "hương vị", "/ˈfleɪvər/", "Anh-Anh 'flavour'. Mùi vị món ăn."],
  ["serve", "phục vụ / dọn ra", "/sɜːrv/", "'serve dinner' = dọn bữa tối."],
  ["order", "gọi món / đặt hàng", "/ˈɔːrdər/", "'order food' = gọi đồ ăn."],
  ["bill", "hóa đơn", "/bɪl/", "Anh-Mỹ cũng dùng 'check'."],
  ["tip", "tiền boa / mẹo", "/tɪp/", "Tiền thưởng thêm cho phục vụ."],
  ["waiter", "bồi bàn (nam)", "/ˈweɪtər/", "Nữ là 'waitress'."],
  ["chef", "đầu bếp chính", "/ʃef/", "'ch' đọc như 'sh'. Bếp trưởng."],
  ["frozen", "đông lạnh", "/ˈfroʊzn/", "Quá khứ phân từ của 'freeze'."],
  ["raw", "sống (chưa nấu)", "/rɔː/", "'raw fish' = cá sống (sashimi)."],
  ["ripe", "chín (trái cây)", "/raɪp/", "Trái cây đã chín, sẵn ăn."],
  ["nut", "hạt (óc chó, đậu phộng)", "/nʌt/", "'peanut' = đậu phộng."],
  ["seafood", "hải sản", "/ˈsiːfuːd/", "Ghép 'sea' + 'food'. Tôm, cua, cá biển."],
  ["shrimp", "tôm", "/ʃrɪmp/", "Anh-Anh dùng 'prawn'."],
];

// ===== English_Basic_Home (en-US) — 100 house & home words =====
const englishBasicHome: Card4[] = [
  ["roof", "mái nhà", "/ruːf/", "Phần che trên cùng ngôi nhà."],
  ["wall", "bức tường", "/wɔːl/", "'on the wall' = trên tường."],
  ["floor", "sàn nhà / tầng", "/flɔːr/", "Cũng nghĩa 'tầng': 'first floor'."],
  ["ceiling", "trần nhà", "/ˈsiːlɪŋ/", "Mặt trên trong phòng. 'c' đọc /s/."],
  ["stairs", "cầu thang", "/sterz/", "Luôn số nhiều. 'go up the stairs' = lên cầu thang."],
  ["gate", "cổng", "/ɡeɪt/", "Cửa ở hàng rào, lối vào sân."],
  ["fence", "hàng rào", "/fens/", "Vây quanh sân, vườn."],
  ["garden", "khu vườn", "/ˈɡɑːrdn/", "Anh-Mỹ cũng dùng 'yard'."],
  ["garage", "nhà để xe", "/ɡəˈrɑːʒ/", "Nơi đậu xe hơi."],
  ["bedroom", "phòng ngủ", "/ˈbedruːm/", "Ghép 'bed' + 'room'."],
  ["bathroom", "phòng tắm / nhà vệ sinh", "/ˈbæθruːm/", "Nơi tắm rửa, vệ sinh."],
  ["living room", "phòng khách", "/ˈlɪvɪŋ ruːm/", "Nơi tiếp khách, xem TV."],
  ["dining room", "phòng ăn", "/ˈdaɪnɪŋ ruːm/", "Phòng đặt bàn ăn."],
  ["kitchen", "nhà bếp", "/ˈkɪtʃɪn/", "Nơi nấu nướng."],
  ["furniture", "đồ nội thất", "/ˈfɜːrnɪtʃər/", "Không đếm được. Bàn ghế tủ giường nói chung."],
  ["sofa", "ghế sô pha", "/ˈsoʊfə/", "Ghế dài. Anh-Anh dùng 'couch'."],
  ["shelf", "kệ / giá", "/ʃelf/", "Số nhiều 'shelves'. 'bookshelf' = kệ sách."],
  ["drawer", "ngăn kéo", "/drɔːr/", "Hộc kéo ra kéo vào trong tủ."],
  ["wardrobe", "tủ quần áo", "/ˈwɔːrdroʊb/", "Tủ lớn treo đồ."],
  ["mirror", "cái gương", "/ˈmɪrər/", "Soi để nhìn mình."],
  ["lamp", "đèn bàn", "/læmp/", "Đèn nhỏ để bàn hoặc đứng."],
  ["curtain", "rèm cửa", "/ˈkɜːrtn/", "Vải che cửa sổ."],
  ["carpet", "tấm thảm", "/ˈkɑːrpɪt/", "Trải sàn nhà."],
  ["pillow", "cái gối", "/ˈpɪloʊ/", "Kê đầu khi ngủ."],
  ["blanket", "cái chăn / mền", "/ˈblæŋkɪt/", "Đắp khi ngủ cho ấm."],
  ["sheet", "tấm ga giường", "/ʃiːt/", "Cũng nghĩa 'tờ giấy'."],
  ["towel", "khăn tắm", "/ˈtaʊəl/", "Lau khô người sau khi tắm."],
  ["toilet", "bồn cầu / nhà vệ sinh", "/ˈtɔɪlət/", "Cũng chỉ phòng vệ sinh (Anh-Anh)."],
  ["sink", "bồn rửa", "/sɪŋk/", "Rửa tay, rửa bát. Cũng động từ 'chìm'."],
  ["shower", "vòi sen / tắm vòi", "/ˈʃaʊər/", "'take a shower' = tắm vòi sen."],
  ["tap", "vòi nước", "/tæp/", "Anh-Mỹ dùng 'faucet'."],
  ["stove", "bếp lò", "/stoʊv/", "Nơi đặt nồi để nấu."],
  ["oven", "lò nướng", "/ˈʌvn/", "Nướng bánh, thịt. Bắt đầu âm 'ʌ'."],
  ["fridge", "tủ lạnh", "/frɪdʒ/", "Viết tắt của 'refrigerator'."],
  ["microwave", "lò vi sóng", "/ˈmaɪkrəweɪv/", "Hâm nóng nhanh thức ăn."],
  ["dishwasher", "máy rửa bát", "/ˈdɪʃwɑːʃər/", "Ghép 'dish' + 'washer'."],
  ["washing machine", "máy giặt", "/ˈwɑːʃɪŋ məˌʃiːn/", "Giặt quần áo tự động."],
  ["fan", "cái quạt", "/fæn/", "Cũng nghĩa 'người hâm mộ'."],
  ["heater", "máy sưởi", "/ˈhiːtər/", "Làm ấm phòng mùa lạnh."],
  ["air conditioner", "máy lạnh / điều hòa", "/er kənˈdɪʃənər/", "Viết tắt 'AC' hoặc 'aircon'."],
  ["television", "ti vi", "/ˈtelɪvɪʒn/", "Thường gọi tắt 'TV'."],
  ["remote", "điều khiển từ xa", "/rɪˈmoʊt/", "'remote control'. Cũng nghĩa 'xa xôi'."],
  ["clock", "đồng hồ (treo/để)", "/klɑːk/", "Khác 'watch' (đồng hồ đeo tay)."],
  ["key", "chìa khóa", "/kiː/", "'house key' = chìa khóa nhà."],
  ["lock", "ổ khóa / khóa lại", "/lɑːk/", "Vừa danh từ vừa động từ."],
  ["switch", "công tắc", "/swɪtʃ/", "'light switch' = công tắc đèn."],
  ["plug", "phích cắm / ổ cắm", "/plʌɡ/", "Cắm vào điện."],
  ["socket", "ổ điện", "/ˈsɑːkɪt/", "Lỗ cắm điện trên tường."],
  ["bulb", "bóng đèn", "/bʌlb/", "'light bulb' = bóng đèn."],
  ["candle", "cây nến", "/ˈkændl/", "Thắp sáng bằng lửa."],
  ["broom", "cây chổi", "/bruːm/", "Quét nhà."],
  ["bucket", "cái xô", "/ˈbʌkɪt/", "Đựng nước."],
  ["trash", "rác", "/træʃ/", "Anh-Anh dùng 'rubbish'. 'trash can' = thùng rác."],
  ["soap", "xà phòng", "/soʊp/", "Rửa cho sạch."],
  ["clean", "sạch / dọn dẹp", "/kliːn/", "Vừa tính từ vừa động từ. Trái nghĩa 'dirty'."],
  ["dirty", "bẩn", "/ˈdɜːrti/", "Trái nghĩa 'clean'."],
  ["tidy", "gọn gàng / dọn gọn", "/ˈtaɪdi/", "'tidy up' = dọn gọn lại."],
  ["messy", "bừa bộn", "/ˈmesi/", "Trái nghĩa 'tidy'."],
  ["sweep", "quét", "/swiːp/", "Quá khứ 'swept'. Quét sàn bằng chổi."],
  ["wash", "rửa / giặt", "/wɑːʃ/", "'wash hands' = rửa tay."],
  ["dry", "khô / làm khô", "/draɪ/", "Trái nghĩa 'wet'."],
  ["wet", "ướt", "/wet/", "Trái nghĩa 'dry'."],
  ["repair", "sửa chữa", "/rɪˈper/", "Đồng nghĩa 'fix'."],
  ["fix", "sửa", "/fɪks/", "'fix the door' = sửa cửa."],
  ["build", "xây dựng", "/bɪld/", "Quá khứ 'built'. Xây nhà."],
  ["paint", "sơn / vẽ", "/peɪnt/", "'paint the wall' = sơn tường."],
  ["hang", "treo", "/hæŋ/", "Quá khứ 'hung'. 'hang clothes' = treo quần áo."],
  ["move", "di chuyển / chuyển nhà", "/muːv/", "'move house' = chuyển nhà."],
  ["rent", "thuê / tiền thuê", "/rent/", "'rent an apartment' = thuê căn hộ."],
  ["apartment", "căn hộ", "/əˈpɑːrtmənt/", "Anh-Anh dùng 'flat'."],
  ["neighbor", "hàng xóm", "/ˈneɪbər/", "Anh-Anh 'neighbour'."],
  ["address", "địa chỉ", "/ˈædres/", "Nơi ở. Cũng động từ 'giải quyết'."],
  ["yard", "sân", "/jɑːrd/", "Khoảng sân quanh nhà."],
  ["balcony", "ban công", "/ˈbælkəni/", "Phần nhô ra ngoài tầng cao."],
  ["basement", "tầng hầm", "/ˈbeɪsmənt/", "Tầng dưới mặt đất."],
  ["attic", "gác mái", "/ˈætɪk/", "Khoảng trống dưới mái nhà."],
  ["hallway", "hành lang", "/ˈhɔːlweɪ/", "Lối đi nối các phòng."],
  ["entrance", "lối vào", "/ˈentrəns/", "Trái nghĩa 'exit'."],
  ["table", "cái bàn", "/ˈteɪbl/", "Mặt phẳng có chân."],
  ["desk", "bàn làm việc", "/desk/", "Bàn để học, làm việc."],
  ["cupboard", "tủ chén / tủ bếp", "/ˈkʌbərd/", "'p' câm: đọc 'KUB-əd'."],
  ["cabinet", "tủ có ngăn", "/ˈkæbɪnət/", "Tủ đựng đồ có cánh cửa."],
  ["bin", "thùng rác", "/bɪn/", "Anh-Anh phổ biến. 'dustbin'."],
  ["vacuum", "máy hút bụi / hút bụi", "/ˈvækjuːm/", "'vacuum cleaner' = máy hút bụi."],
  ["iron", "bàn ủi / ủi", "/ˈaɪərn/", "'r' câm kiểu Mỹ. Cũng nghĩa 'sắt'."],
  ["kettle", "ấm đun nước", "/ˈketl/", "Đun nước sôi pha trà."],
  ["pot", "cái nồi", "/pɑːt/", "Nấu canh, hầm."],
  ["pan", "cái chảo", "/pæn/", "'frying pan' = chảo chiên."],
  ["blender", "máy xay sinh tố", "/ˈblendər/", "Xay trái cây, đá."],
  ["toaster", "máy nướng bánh mì", "/ˈtoʊstər/", "Nướng lát bánh mì sandwich."],
  ["wire", "dây điện", "/ˈwaɪər/", "Dây dẫn điện."],
  ["pipe", "đường ống", "/paɪp/", "Dẫn nước. Cũng nghĩa 'tẩu thuốc'."],
  ["roofing", "vật liệu lợp mái", "/ˈruːfɪŋ/", "Ngói, tôn lợp mái."],
  ["doorbell", "chuông cửa", "/ˈdɔːrbel/", "Bấm để báo có khách."],
  ["mat", "tấm thảm chùi chân", "/mæt/", "'doormat' = thảm trước cửa."],
  ["shelf life", "hạn sử dụng", "/ˈʃelf laɪf/", "Thời gian giữ được của sản phẩm."],
  ["household", "hộ gia đình / việc nhà", "/ˈhaʊshoʊld/", "'household chores' = việc nhà."],
  ["chore", "việc vặt trong nhà", "/tʃɔːr/", "'do the chores' = làm việc nhà."],
  ["comfortable", "thoải mái", "/ˈkʌmftəbl/", "Đọc gọn: KUMF-tə-bl."],
  ["cozy", "ấm cúng", "/ˈkoʊzi/", "Nhỏ ấm dễ chịu. Anh-Anh 'cosy'."],
];

// ===== English_Basic_Body (en-US) — 100 body & health words =====
const englishBasicBody: Card4[] = [
  ["body", "cơ thể", "/ˈbɑːdi/", "Toàn bộ cơ thể người."],
  ["head", "cái đầu", "/hed/", "Phần trên cùng cơ thể."],
  ["face", "khuôn mặt", "/feɪs/", "Mặt trước của đầu."],
  ["hair", "tóc", "/her/", "Không đếm được khi nói tóc nói chung."],
  ["eye", "con mắt", "/aɪ/", "Cơ quan để nhìn. Số nhiều 'eyes'."],
  ["ear", "tai", "/ɪr/", "Cơ quan để nghe."],
  ["nose", "mũi", "/noʊz/", "Để thở và ngửi."],
  ["mouth", "miệng", "/maʊθ/", "Để ăn và nói."],
  ["tooth", "răng", "/tuːθ/", "Số nhiều bất quy tắc 'teeth'."],
  ["tongue", "lưỡi", "/tʌŋ/", "Để nếm và nói. 'g' câm."],
  ["lip", "môi", "/lɪp/", "Thường số nhiều 'lips'."],
  ["cheek", "má", "/tʃiːk/", "Hai bên khuôn mặt."],
  ["chin", "cằm", "/tʃɪn/", "Phần dưới miệng."],
  ["forehead", "trán", "/ˈfɔːrhed/", "Phần trên lông mày."],
  ["neck", "cổ", "/nek/", "Nối đầu với thân."],
  ["shoulder", "vai", "/ˈʃoʊldər/", "Nơi nối tay với thân."],
  ["arm", "cánh tay", "/ɑːrm/", "Từ vai đến bàn tay."],
  ["elbow", "khuỷu tay", "/ˈelboʊ/", "Khớp giữa cánh tay."],
  ["hand", "bàn tay", "/hænd/", "Đầu cánh tay, có ngón."],
  ["finger", "ngón tay", "/ˈfɪŋɡər/", "Mỗi bàn tay 5 ngón."],
  ["thumb", "ngón cái", "/θʌm/", "'b' câm. Ngón to nhất."],
  ["nail", "móng tay / móng chân", "/neɪl/", "Cũng nghĩa 'cái đinh'."],
  ["chest", "ngực", "/tʃest/", "Phần trước thân trên."],
  ["back", "lưng", "/bæk/", "Mặt sau cơ thể."],
  ["stomach", "bụng / dạ dày", "/ˈstʌmək/", "'stomachache' = đau bụng."],
  ["waist", "eo", "/weɪst/", "Phần thắt giữa thân. Đồng âm 'waste'."],
  ["hip", "hông", "/hɪp/", "Hai bên dưới eo."],
  ["leg", "chân (cẳng)", "/leɡ/", "Từ hông đến bàn chân."],
  ["knee", "đầu gối", "/niː/", "'k' câm. Khớp giữa chân."],
  ["foot", "bàn chân", "/fʊt/", "Số nhiều bất quy tắc 'feet'."],
  ["toe", "ngón chân", "/toʊ/", "Mỗi bàn chân 5 ngón."],
  ["heel", "gót chân", "/hiːl/", "Phần sau bàn chân."],
  ["skin", "da", "/skɪn/", "Lớp ngoài cơ thể."],
  ["bone", "xương", "/boʊn/", "Khung cứng bên trong."],
  ["blood", "máu", "/blʌd/", "Chất lỏng đỏ. Đọc 'blʌd' không 'blood'."],
  ["heart", "tim", "/hɑːrt/", "Bơm máu đi khắp cơ thể."],
  ["brain", "não", "/breɪn/", "Cơ quan suy nghĩ."],
  ["lung", "phổi", "/lʌŋ/", "Để thở. Thường số nhiều 'lungs'."],
  ["muscle", "cơ bắp", "/ˈmʌsl/", "'c' câm. Đọc 'MUS-l'."],
  ["health", "sức khỏe", "/helθ/", "'good health' = sức khỏe tốt."],
  ["healthy", "khỏe mạnh", "/ˈhelθi/", "Trái nghĩa 'sick/ill'."],
  ["sick", "ốm / bệnh", "/sɪk/", "'I feel sick' = tôi thấy mệt/buồn nôn."],
  ["ill", "ốm (Anh-Anh)", "/ɪl/", "Đồng nghĩa 'sick'."],
  ["pain", "cơn đau", "/peɪn/", "'in pain' = đang đau."],
  ["hurt", "đau / làm đau", "/hɜːrt/", "Quá khứ giữ nguyên 'hurt'. 'It hurts' = nó đau."],
  ["ache", "đau âm ỉ", "/eɪk/", "'ch' đọc /k/. 'headache' = đau đầu."],
  ["fever", "sốt", "/ˈfiːvər/", "'have a fever' = bị sốt."],
  ["cough", "ho", "/kɔːf/", "Đọc 'kɔːf'. Phản xạ ở họng."],
  ["cold", "cảm lạnh", "/koʊld/", "'catch a cold' = bị cảm."],
  ["flu", "cúm", "/fluː/", "Viết tắt 'influenza'."],
  ["headache", "đau đầu", "/ˈhedeɪk/", "Ghép 'head' + 'ache'."],
  ["wound", "vết thương", "/wuːnd/", "Đọc 'wuːnd'. Da bị rách."],
  ["injury", "chấn thương", "/ˈɪndʒəri/", "Tổn thương do tai nạn."],
  ["medicine", "thuốc", "/ˈmedɪsn/", "'take medicine' = uống thuốc."],
  ["pill", "viên thuốc", "/pɪl/", "Thuốc dạng viên nén."],
  ["doctor", "bác sĩ", "/ˈdɑːktər/", "Viết tắt 'Dr.'."],
  ["nurse", "y tá", "/nɜːrs/", "Chăm sóc bệnh nhân."],
  ["dentist", "nha sĩ", "/ˈdentɪst/", "Bác sĩ răng."],
  ["hospital", "bệnh viện", "/ˈhɑːspɪtl/", "Nơi điều trị bệnh."],
  ["clinic", "phòng khám", "/ˈklɪnɪk/", "Nhỏ hơn bệnh viện."],
  ["patient", "bệnh nhân / kiên nhẫn", "/ˈpeɪʃnt/", "Hai nghĩa tùy ngữ cảnh."],
  ["treatment", "việc điều trị", "/ˈtriːtmənt/", "Cách chữa bệnh."],
  ["cure", "chữa khỏi / phương thuốc", "/kjʊr/", "Làm hết bệnh hẳn."],
  ["recover", "hồi phục", "/rɪˈkʌvər/", "Khỏe lại sau bệnh."],
  ["breathe", "thở", "/briːð/", "Động từ. Danh từ là 'breath' /breθ/."],
  ["heartbeat", "nhịp tim", "/ˈhɑːrtbiːt/", "Tiếng tim đập."],
  ["weight", "cân nặng", "/weɪt/", "'lose weight' = giảm cân. 'w' câm? không, 'gh' câm."],
  ["height", "chiều cao", "/haɪt/", "'gh' câm. Đo bằng cm."],
  ["exercise", "tập thể dục", "/ˈeksərsaɪz/", "'do exercise' = tập luyện."],
  ["sleep", "giấc ngủ / ngủ", "/sliːp/", "Cần cho sức khỏe."],
  ["rest", "nghỉ ngơi", "/rest/", "'take a rest' = nghỉ một chút."],
  ["tired", "mệt", "/ˈtaɪərd/", "'I'm tired' = tôi mệt."],
  ["strong", "khỏe / mạnh", "/strɔːŋ/", "Trái nghĩa 'weak'."],
  ["weak", "yếu", "/wiːk/", "Đồng âm 'week' (tuần)."],
  ["fat", "béo / mỡ", "/fæt/", "Trái nghĩa 'thin'."],
  ["thin", "gầy / mỏng", "/θɪn/", "Trái nghĩa 'fat/thick'."],
  ["slim", "thon thả", "/slɪm/", "Gầy theo nghĩa tích cực."],
  ["tall", "cao", "/tɔːl/", "Chỉ chiều cao người, vật."],
  ["short", "thấp / ngắn", "/ʃɔːrt/", "Trái nghĩa 'tall/long'."],
  ["smile", "nụ cười / mỉm cười", "/smaɪl/", "Cười không thành tiếng."],
  ["laugh", "cười (thành tiếng)", "/læf/", "'gh' đọc /f/."],
  ["cry", "khóc", "/kraɪ/", "Chảy nước mắt."],
  ["sweat", "mồ hôi / đổ mồ hôi", "/swet/", "Đọc 'swet'. Khi nóng hoặc tập."],
  ["wash", "rửa / tắm rửa", "/wɑːʃ/", "Giữ vệ sinh."],
  ["brush", "chải / bàn chải", "/brʌʃ/", "'brush teeth' = đánh răng."],
  ["toothbrush", "bàn chải đánh răng", "/ˈtuːθbrʌʃ/", "Ghép 'tooth' + 'brush'."],
  ["toothpaste", "kem đánh răng", "/ˈtuːθpeɪst/", "Bóp lên bàn chải."],
  ["shampoo", "dầu gội", "/ʃæmˈpuː/", "Gội đầu. Nhấn âm sau."],
  ["diet", "chế độ ăn", "/ˈdaɪət/", "'on a diet' = đang ăn kiêng."],
  ["vitamin", "vi-ta-min", "/ˈvaɪtəmɪn/", "Anh-Mỹ /ˈvaɪ-/, Anh-Anh /ˈvɪt-/."],
  ["allergy", "dị ứng", "/ˈælərdʒi/", "'allergic to' = dị ứng với."],
  ["dizzy", "chóng mặt", "/ˈdɪzi/", "'feel dizzy' = thấy choáng."],
  ["nausea", "buồn nôn", "/ˈnɔːziə/", "Cảm giác muốn ói."],
  ["bandage", "băng gạc", "/ˈbændɪdʒ/", "Quấn vết thương."],
  ["surgery", "phẫu thuật", "/ˈsɜːrdʒəri/", "Mổ để chữa bệnh."],
  ["pulse", "mạch đập", "/pʌls/", "'take the pulse' = bắt mạch."],
  ["pregnant", "mang thai", "/ˈpreɡnənt/", "Đang có em bé."],
  ["wrist", "cổ tay", "/rɪst/", "'w' câm. Khớp nối bàn tay."],
  ["ankle", "mắt cá chân", "/ˈæŋkl/", "Khớp nối bàn chân."],
];

// ===== English_Inter_Work (en-US) — 100 workplace words =====
const englishInterWork: Card4[] = [
  ["job", "công việc / việc làm", "/dʒɑːb/", "Một vị trí cụ thể. Khác 'work' (việc nói chung)."],
  ["career", "sự nghiệp", "/kəˈrɪr/", "Cả quá trình nghề nghiệp lâu dài."],
  ["employee", "nhân viên", "/ɪmˈplɔɪiː/", "Người được thuê làm việc."],
  ["employer", "người sử dụng lao động", "/ɪmˈplɔɪər/", "Người/công ty thuê nhân viên."],
  ["colleague", "đồng nghiệp", "/ˈkɑːliːɡ/", "Người làm cùng công ty."],
  ["manager", "quản lý", "/ˈmænɪdʒər/", "Người điều hành nhóm."],
  ["staff", "nhân viên (tập thể)", "/stæf/", "Toàn bộ nhân viên. Không thêm 's'."],
  ["team", "đội nhóm", "/tiːm/", "'teamwork' = làm việc nhóm."],
  ["department", "phòng ban", "/dɪˈpɑːrtmənt/", "Bộ phận trong công ty."],
  ["company", "công ty", "/ˈkʌmpəni/", "Doanh nghiệp."],
  ["office", "văn phòng", "/ˈɔːfɪs/", "Nơi làm việc bàn giấy."],
  ["salary", "lương (tháng)", "/ˈsæləri/", "Trả cố định hàng tháng/năm."],
  ["wage", "lương (giờ/ngày)", "/weɪdʒ/", "Trả theo giờ làm."],
  ["income", "thu nhập", "/ˈɪnkʌm/", "Tổng tiền kiếm được."],
  ["bonus", "tiền thưởng", "/ˈboʊnəs/", "Thưởng thêm ngoài lương."],
  ["promotion", "thăng chức", "/prəˈmoʊʃn/", "Lên vị trí cao hơn."],
  ["interview", "phỏng vấn", "/ˈɪntərvjuː/", "'job interview' = phỏng vấn xin việc."],
  ["resume", "sơ yếu lý lịch", "/ˈrezəmeɪ/", "Anh-Anh dùng 'CV'."],
  ["apply", "nộp đơn / ứng tuyển", "/əˈplaɪ/", "'apply for a job' = xin việc."],
  ["hire", "thuê / tuyển", "/ˈhaɪər/", "Nhận người vào làm."],
  ["fire", "sa thải", "/ˈfaɪər/", "Đuổi việc. Cũng nghĩa 'lửa'."],
  ["resign", "từ chức / xin nghỉ", "/rɪˈzaɪn/", "'g' câm. Tự rời công việc."],
  ["retire", "nghỉ hưu", "/rɪˈtaɪər/", "Nghỉ làm khi về già."],
  ["task", "nhiệm vụ", "/tæsk/", "Việc cụ thể cần làm."],
  ["project", "dự án", "/ˈprɑːdʒekt/", "Danh từ nhấn âm đầu."],
  ["deadline", "hạn chót", "/ˈdedlaɪn/", "'meet the deadline' = kịp hạn."],
  ["meeting", "cuộc họp", "/ˈmiːtɪŋ/", "'have a meeting' = họp."],
  ["schedule", "lịch trình", "/ˈskedʒuːl/", "Anh-Anh /ˈʃedjuːl/."],
  ["appointment", "cuộc hẹn", "/əˈpɔɪntmənt/", "Hẹn gặp đã định trước."],
  ["report", "báo cáo", "/rɪˈpɔːrt/", "Vừa danh từ vừa động từ."],
  ["presentation", "bài thuyết trình", "/ˌpriːzenˈteɪʃn/", "Trình bày trước nhóm."],
  ["client", "khách hàng (dịch vụ)", "/ˈklaɪənt/", "Khách dùng dịch vụ."],
  ["customer", "khách hàng (mua)", "/ˈkʌstəmər/", "Người mua sản phẩm."],
  ["contract", "hợp đồng", "/ˈkɑːntrækt/", "Thỏa thuận pháp lý."],
  ["agreement", "thỏa thuận", "/əˈɡriːmənt/", "Sự đồng ý chung."],
  ["budget", "ngân sách", "/ˈbʌdʒɪt/", "Số tiền được phân bổ."],
  ["profit", "lợi nhuận", "/ˈprɑːfɪt/", "Tiền lãi. Trái nghĩa 'loss'."],
  ["loss", "thua lỗ", "/lɔːs/", "Mất tiền. Trái nghĩa 'profit'."],
  ["invest", "đầu tư", "/ɪnˈvest/", "Bỏ tiền để sinh lời."],
  ["customer service", "dịch vụ khách hàng", "/ˈkʌstəmər ˌsɜːrvɪs/", "Bộ phận hỗ trợ khách."],
  ["skill", "kỹ năng", "/skɪl/", "'soft skills' = kỹ năng mềm."],
  ["experience", "kinh nghiệm", "/ɪkˈspɪriəns/", "'work experience' = kinh nghiệm làm việc."],
  ["qualification", "bằng cấp / trình độ", "/ˌkwɑːlɪfɪˈkeɪʃn/", "Chứng chỉ đủ điều kiện."],
  ["training", "đào tạo / huấn luyện", "/ˈtreɪnɪŋ/", "Dạy kỹ năng cho nhân viên."],
  ["responsibility", "trách nhiệm", "/rɪˌspɑːnsəˈbɪləti/", "Việc mình phải lo."],
  ["duty", "nhiệm vụ / bổn phận", "/ˈduːti/", "'on duty' = đang trực."],
  ["position", "vị trí / chức vụ", "/pəˈzɪʃn/", "Cấp bậc trong công ty."],
  ["role", "vai trò", "/roʊl/", "Phần việc mình đảm nhận."],
  ["performance", "hiệu suất / màn thể hiện", "/pərˈfɔːrməns/", "Mức độ làm việc tốt."],
  ["productivity", "năng suất", "/ˌproʊdʌkˈtɪvəti/", "Lượng việc làm được."],
  ["efficient", "hiệu quả", "/ɪˈfɪʃnt/", "Làm tốt mà ít lãng phí."],
  ["overtime", "làm thêm giờ", "/ˈoʊvərtaɪm/", "Làm quá giờ quy định."],
  ["shift", "ca làm", "/ʃɪft/", "'night shift' = ca đêm."],
  ["leave", "nghỉ phép / rời đi", "/liːv/", "'sick leave' = nghỉ ốm."],
  ["vacation", "kỳ nghỉ", "/veɪˈkeɪʃn/", "Anh-Anh dùng 'holiday'."],
  ["benefit", "phúc lợi / lợi ích", "/ˈbenɪfɪt/", "Bảo hiểm, thưởng ngoài lương."],
  ["insurance", "bảo hiểm", "/ɪnˈʃʊrəns/", "'health insurance' = bảo hiểm y tế."],
  ["stakeholder", "bên liên quan", "/ˈsteɪkhoʊldər/", "Người/nhóm bị ảnh hưởng bởi dự án."],
  ["network", "mạng lưới quan hệ", "/ˈnetwɜːrk/", "'networking' = mở rộng quan hệ."],
  ["goal", "mục tiêu", "/ɡoʊl/", "Điều muốn đạt được."],
  ["target", "chỉ tiêu / mục tiêu", "/ˈtɑːrɡɪt/", "Con số cần đạt."],
  ["strategy", "chiến lược", "/ˈstrætədʒi/", "Kế hoạch dài hạn."],
  ["solution", "giải pháp", "/səˈluːʃn/", "Cách giải quyết vấn đề."],
  ["challenge", "thử thách", "/ˈtʃælɪndʒ/", "Việc khó cần vượt qua."],
  ["opportunity", "cơ hội", "/ˌɑːpərˈtuːnəti/", "Dịp tốt để phát triển."],
  ["decision", "quyết định", "/dɪˈsɪʒn/", "'make a decision' = ra quyết định."],
  ["approve", "phê duyệt", "/əˈpruːv/", "Đồng ý chính thức."],
  ["reject", "từ chối / bác bỏ", "/rɪˈdʒekt/", "Không chấp nhận."],
  ["feedback", "phản hồi / góp ý", "/ˈfiːdbæk/", "Nhận xét để cải thiện."],
  ["review", "đánh giá / xem lại", "/rɪˈvjuː/", "'performance review' = đánh giá năng lực."],
  ["evaluate", "đánh giá", "/ɪˈvæljueɪt/", "Xem xét chất lượng."],
  ["improve", "cải thiện", "/ɪmˈpruːv/", "Làm tốt hơn."],
  ["achieve", "đạt được", "/əˈtʃiːv/", "'achieve a goal' = đạt mục tiêu."],
  ["manage", "quản lý / xoay xở", "/ˈmænɪdʒ/", "Điều hành hoặc giải quyết được."],
  ["supervise", "giám sát", "/ˈsuːpərvaɪz/", "Trông coi người khác làm."],
  ["delegate", "giao việc / ủy quyền", "/ˈdelɪɡeɪt/", "Phân việc cho người dưới."],
  ["cooperate", "hợp tác", "/koʊˈɑːpəreɪt/", "Làm việc cùng nhau."],
  ["collaborate", "phối hợp", "/kəˈlæbəreɪt/", "Cùng tạo ra kết quả."],
  ["negotiate", "đàm phán", "/nɪˈɡoʊʃieɪt/", "Thương lượng để đạt thỏa thuận."],
  ["communicate", "giao tiếp", "/kəˈmjuːnɪkeɪt/", "Trao đổi thông tin."],
  ["organize", "tổ chức / sắp xếp", "/ˈɔːrɡənaɪz/", "Anh-Anh 'organise'."],
  ["prioritize", "ưu tiên", "/praɪˈɔːrətaɪz/", "Chọn việc quan trọng làm trước."],
  ["multitask", "làm nhiều việc cùng lúc", "/ˌmʌltiˈtæsk/", "Xử lý song song nhiều việc."],
  ["workload", "khối lượng công việc", "/ˈwɜːrkloʊd/", "Lượng việc phải làm."],
  ["colleague-friendly", "thân thiện đồng nghiệp", "/ˈkɑːliːɡ ˈfrendli/", "Môi trường dễ hợp tác."],
  ["freelance", "làm tự do", "/ˈfriːlæns/", "Làm thuê độc lập, không cố định một công ty."],
  ["recruit", "tuyển dụng", "/rɪˈkruːt/", "Tìm và nhận người mới."],
  ["candidate", "ứng viên", "/ˈkændɪdeɪt/", "Người dự tuyển."],
  ["probation", "thử việc", "/proʊˈbeɪʃn/", "Giai đoạn thử trước khi chính thức."],
  ["resignation", "đơn từ chức", "/ˌrezɪɡˈneɪʃn/", "Thông báo nghỉ việc."],
  ["workflow", "quy trình làm việc", "/ˈwɜːrkfloʊ/", "Trình tự các bước công việc."],
  ["overtime pay", "tiền làm thêm giờ", "/ˈoʊvərtaɪm peɪ/", "Lương cho giờ làm thêm."],
  ["subordinate", "cấp dưới", "/səˈbɔːrdɪnət/", "Người làm dưới quyền mình."],
  ["headquarters", "trụ sở chính", "/ˈhedkwɔːrtərz/", "Văn phòng chính của công ty."],
  ["branch", "chi nhánh", "/bræntʃ/", "Văn phòng phụ. Cũng nghĩa 'cành cây'."],
  ["industry", "ngành công nghiệp", "/ˈɪndəstri/", "Lĩnh vực kinh tế."],
  ["profession", "nghề chuyên môn", "/prəˈfeʃn/", "Nghề cần đào tạo (bác sĩ, luật sư)."],
  ["expertise", "chuyên môn", "/ˌekspɜːrˈtiːz/", "Kiến thức sâu về lĩnh vực."],
  ["mentor", "người cố vấn", "/ˈmentɔːr/", "Hướng dẫn người ít kinh nghiệm."],
  ["deadline-driven", "chạy theo hạn chót", "/ˈdedlaɪn ˈdrɪvn/", "Làm việc theo áp lực thời hạn."],
];

async function seedDeck(deckName: string, lang: string, cards: Card4[]) {
  const deck = await prisma.deck.upsert({
    where: { name: deckName },
    update: {},
    create: { name: deckName },
  });

  const existing = new Set(
    (
      await prisma.card.findMany({
        where: { deckId: deck.id },
        select: { word: true },
      })
    ).map((c) => c.word.toLowerCase())
  );

  let added = 0;
  let skipped = 0;
  let i = 0;
  for (const [word, meaning, ipa, explanation] of cards) {
    if (existing.has(word.toLowerCase())) {
      skipped++;
      continue;
    }
    await prisma.card.create({
      data: {
        word,
        meaning,
        ipa,
        explanation,
        authorName: "WordPool",
        color: COLORS[i % COLORS.length],
        lang,
        deckId: deck.id,
      },
    });
    existing.add(word.toLowerCase());
    added++;
    i++;
  }
  console.log(`${deckName}: +${added} added, ${skipped} already there (total ${cards.length})`);
}

async function main() {
  await seedDeck("English_Basic_Life", "en-US", englishBasicLife);
  await seedDeck("English_Basic_Food", "en-US", englishBasicFood);
  await seedDeck("English_Basic_Home", "en-US", englishBasicHome);
  await seedDeck("English_Basic_Body", "en-US", englishBasicBody);
  await seedDeck("English_Inter_Work", "en-US", englishInterWork);
}

main()
  .then(() => prisma.$disconnect())
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
