import { PrismaClient } from "../src/generated/prisma/client";
import { PrismaNeon } from "@prisma/adapter-neon";
import "dotenv/config";

const adapter = new PrismaNeon({
  connectionString: process.env.DATABASE_URL ?? "",
});
const prisma = new PrismaClient({ adapter });

const COLORS = [
  "#dbeafe",
  "#dcfce7",
  "#fef9c3",
  "#fce7f3",
  "#ede9fe",
  "#ffedd5",
  "#cffafe",
];

// Rich card tuple: [word, meaning (Vietnamese), ipa, explanation (Vietnamese)]
type Card4 = [string, string, string, string];

// ===== English_Basic_Life (en-US) — 100 everyday-life words =====
const englishBasicLife: Card4[] = [
  ["time", "thời gian", "/taɪm/", "Danh từ chỉ thời gian nói chung. 'What time is it?' = Mấy giờ rồi?"],
  ["day", "ngày", "/deɪ/", "Một ngày 24 giờ. 'today' = hôm nay, 'every day' = mỗi ngày."],
  ["night", "đêm", "/naɪt/", "Khoảng tối từ tối đến sáng. 'Good night' = chúc ngủ ngon."],
  ["morning", "buổi sáng", "/ˈmɔːrnɪŋ/", "'in the morning' = vào buổi sáng. 'Good morning' = chào buổi sáng."],
  ["week", "tuần", "/wiːk/", "7 ngày. 'last week' = tuần trước, 'next week' = tuần sau."],
  ["month", "tháng", "/mʌnθ/", "Một trong 12 tháng. Phát âm 'th' giọng gió."],
  ["year", "năm", "/jɪr/", "12 tháng. 'this year' = năm nay."],
  ["hour", "giờ (tiếng)", "/ˈaʊər/", "60 phút. 'h' câm, đọc như 'our'."],
  ["minute", "phút", "/ˈmɪnɪt/", "60 giây. 'Wait a minute' = đợi một chút."],
  ["water", "nước", "/ˈwɔːtər/", "Chất lỏng để uống. 'a glass of water' = một ly nước."],
  ["food", "thức ăn", "/fuːd/", "Đồ ăn nói chung. 'fast food' = đồ ăn nhanh."],
  ["money", "tiền", "/ˈmʌni/", "'make money' = kiếm tiền, 'spend money' = tiêu tiền."],
  ["house", "ngôi nhà", "/haʊs/", "Nơi ở. Khác 'home' (nhà - cảm giác thân thuộc)."],
  ["home", "nhà (mái ấm)", "/hoʊm/", "Nơi mình sống, mang nghĩa thân thuộc. 'go home' = về nhà."],
  ["family", "gia đình", "/ˈfæməli/", "Những người thân. 'my family' = gia đình tôi."],
  ["friend", "bạn bè", "/frend/", "'best friend' = bạn thân nhất."],
  ["work", "công việc / làm việc", "/wɜːrk/", "Vừa là danh từ vừa là động từ. 'go to work' = đi làm."],
  ["school", "trường học", "/skuːl/", "'go to school' = đi học."],
  ["car", "xe hơi", "/kɑːr/", "Phương tiện 4 bánh. 'drive a car' = lái xe."],
  ["road", "con đường", "/roʊd/", "Đường cho xe chạy. Khác 'street' (đường trong phố)."],
  ["city", "thành phố", "/ˈsɪti/", "'big city' = thành phố lớn."],
  ["country", "đất nước / vùng quê", "/ˈkʌntri/", "Vừa nghĩa quốc gia, vừa nghĩa nông thôn tùy ngữ cảnh."],
  ["people", "mọi người", "/ˈpiːpl/", "Số nhiều của 'person'. Luôn đi với động từ số nhiều."],
  ["person", "người (một người)", "/ˈpɜːrsn/", "Số ít. Số nhiều thường dùng 'people'."],
  ["man", "đàn ông", "/mæn/", "Số nhiều bất quy tắc: 'men'."],
  ["woman", "phụ nữ", "/ˈwʊmən/", "Số nhiều bất quy tắc: 'women' /ˈwɪmɪn/."],
  ["child", "đứa trẻ", "/tʃaɪld/", "Số nhiều bất quy tắc: 'children'."],
  ["name", "tên", "/neɪm/", "'What's your name?' = Bạn tên gì?"],
  ["love", "tình yêu / yêu", "/lʌv/", "Danh từ và động từ. 'I love you' = anh yêu em."],
  ["life", "cuộc sống", "/laɪf/", "Số nhiều: 'lives' /laɪvz/."],
  ["world", "thế giới", "/wɜːrld/", "'around the world' = khắp thế giới."],
  ["place", "nơi chốn", "/pleɪs/", "'a nice place' = một nơi đẹp."],
  ["thing", "vật / việc", "/θɪŋ/", "Từ chung chỉ đồ vật hoặc sự việc."],
  ["word", "từ / lời nói", "/wɜːrd/", "'in other words' = nói cách khác."],
  ["book", "quyển sách", "/bʊk/", "'read a book' = đọc sách."],
  ["phone", "điện thoại", "/foʊn/", "'call on the phone' = gọi điện thoại."],
  ["door", "cửa", "/dɔːr/", "'open the door' = mở cửa."],
  ["window", "cửa sổ", "/ˈwɪndoʊ/", "'look out the window' = nhìn ra cửa sổ."],
  ["table", "cái bàn", "/ˈteɪbl/", "'on the table' = trên bàn."],
  ["chair", "cái ghế", "/tʃer/", "'sit on a chair' = ngồi trên ghế."],
  ["bed", "cái giường", "/bed/", "'go to bed' = đi ngủ."],
  ["room", "căn phòng", "/ruːm/", "'living room' = phòng khách."],
  ["street", "đường phố", "/striːt/", "Đường trong khu dân cư có nhà hai bên."],
  ["bag", "túi / cặp", "/bæɡ/", "'a bag of rice' = một túi gạo."],
  ["clothes", "quần áo", "/kloʊz/", "Luôn số nhiều, không có 'a clothes'."],
  ["shoe", "chiếc giày", "/ʃuː/", "Thường dùng số nhiều 'shoes' (đôi giày)."],
  ["hand", "bàn tay", "/hænd/", "'shake hands' = bắt tay."],
  ["eye", "con mắt", "/aɪ/", "Số nhiều 'eyes'. Phát âm như chữ 'I'."],
  ["head", "cái đầu", "/hed/", "'headache' = đau đầu."],
  ["heart", "trái tim", "/hɑːrt/", "'h' đọc, chữ giống 'hurt' nhưng nghĩa khác."],
  ["color", "màu sắc", "/ˈkʌlər/", "Anh-Anh viết 'colour'. 'favorite color' = màu yêu thích."],
  ["light", "ánh sáng / đèn", "/laɪt/", "'turn on the light' = bật đèn."],
  ["air", "không khí", "/er/", "'fresh air' = không khí trong lành."],
  ["fire", "lửa", "/ˈfaɪər/", "'make a fire' = nhóm lửa."],
  ["sun", "mặt trời", "/sʌn/", "'sunny' = nắng."],
  ["moon", "mặt trăng", "/muːn/", "'full moon' = trăng tròn."],
  ["star", "ngôi sao", "/stɑːr/", "Cũng nghĩa 'ngôi sao' (người nổi tiếng)."],
  ["rain", "mưa", "/reɪn/", "'It's raining' = trời đang mưa."],
  ["wind", "gió", "/wɪnd/", "'windy' = nhiều gió."],
  ["tree", "cây", "/triː/", "Số nhiều 'trees'."],
  ["flower", "bông hoa", "/ˈflaʊər/", "'a bunch of flowers' = một bó hoa."],
  ["animal", "động vật", "/ˈænɪml/", "'wild animal' = động vật hoang dã."],
  ["dog", "con chó", "/dɔːɡ/", "'walk the dog' = dắt chó đi dạo."],
  ["cat", "con mèo", "/kæt/", "Tiếng kêu 'meow'."],
  ["bird", "con chim", "/bɜːrd/", "'birds fly' = chim bay."],
  ["fish", "con cá", "/fɪʃ/", "Số nhiều thường giữ nguyên 'fish'."],
  ["go", "đi", "/ɡoʊ/", "Quá khứ bất quy tắc 'went'. 'go home' = về nhà."],
  ["come", "đến", "/kʌm/", "Quá khứ 'came'. 'come here' = đến đây."],
  ["eat", "ăn", "/iːt/", "Quá khứ 'ate'. 'eat lunch' = ăn trưa."],
  ["drink", "uống", "/drɪŋk/", "Quá khứ 'drank'. Cũng là danh từ 'đồ uống'."],
  ["sleep", "ngủ", "/sliːp/", "Quá khứ 'slept'. 'go to sleep' = đi ngủ."],
  ["see", "nhìn thấy", "/siː/", "Quá khứ 'saw'. Khác 'look' (nhìn chủ động)."],
  ["hear", "nghe thấy", "/hɪr/", "Quá khứ 'heard'. Khác 'listen' (lắng nghe)."],
  ["speak", "nói", "/spiːk/", "Quá khứ 'spoke'. 'speak English' = nói tiếng Anh."],
  ["read", "đọc", "/riːd/", "Quá khứ viết giống nhưng đọc /red/."],
  ["write", "viết", "/raɪt/", "Quá khứ 'wrote'. 'w' câm."],
  ["walk", "đi bộ", "/wɔːk/", "'l' câm. 'go for a walk' = đi dạo."],
  ["run", "chạy", "/rʌn/", "Quá khứ 'ran'. 'go running' = đi chạy bộ."],
  ["buy", "mua", "/baɪ/", "Quá khứ 'bought'. Trái nghĩa 'sell'."],
  ["sell", "bán", "/sel/", "Quá khứ 'sold'. Trái nghĩa 'buy'."],
  ["open", "mở", "/ˈoʊpən/", "Trái nghĩa 'close'. 'open the door' = mở cửa."],
  ["close", "đóng", "/kloʊz/", "Động từ /kloʊz/, tính từ 'gần' đọc /kloʊs/."],
  ["start", "bắt đầu", "/stɑːrt/", "Đồng nghĩa 'begin'. Trái nghĩa 'stop/finish'."],
  ["stop", "dừng lại", "/stɑːp/", "'stop talking' = ngừng nói."],
  ["help", "giúp đỡ", "/help/", "'Can you help me?' = Bạn giúp tôi được không?"],
  ["want", "muốn", "/wɑːnt/", "'I want to go' = tôi muốn đi."],
  ["need", "cần", "/niːd/", "Mạnh hơn 'want'. 'I need water' = tôi cần nước."],
  ["like", "thích", "/laɪk/", "'I like it' = tôi thích nó. Cũng nghĩa 'giống như'."],
  ["know", "biết", "/noʊ/", "Quá khứ 'knew'. 'k' câm. 'I don't know' = tôi không biết."],
  ["think", "nghĩ", "/θɪŋk/", "Quá khứ 'thought'. 'I think so' = tôi nghĩ vậy."],
  ["say", "nói (điều gì)", "/seɪ/", "Quá khứ 'said' /sed/. 'say yes' = nói đồng ý."],
  ["good", "tốt", "/ɡʊd/", "So sánh bất quy tắc: better / best."],
  ["bad", "tệ / xấu", "/bæd/", "So sánh bất quy tắc: worse / worst."],
  ["big", "to / lớn", "/bɪɡ/", "Trái nghĩa 'small'. So sánh 'bigger'."],
  ["small", "nhỏ", "/smɔːl/", "Đồng nghĩa 'little'. Trái nghĩa 'big'."],
  ["new", "mới", "/nuː/", "Trái nghĩa 'old'. 'brand new' = mới toanh."],
  ["old", "cũ / già", "/oʊld/", "'How old are you?' = Bạn bao nhiêu tuổi?"],
  ["hot", "nóng", "/hɑːt/", "Trái nghĩa 'cold'. Cũng nghĩa 'cay'."],
  ["cold", "lạnh", "/koʊld/", "'I'm cold' = tôi thấy lạnh. Cũng nghĩa 'cảm lạnh'."],
  ["happy", "vui / hạnh phúc", "/ˈhæpi/", "Trái nghĩa 'sad'. 'Happy birthday' = chúc mừng sinh nhật."],
  ["easy", "dễ", "/ˈiːzi/", "Trái nghĩa 'hard/difficult'. 'easy to learn' = dễ học."],
];

// ===== English_Basic_Food (en-US) — 100 food & eating words =====
const englishBasicFood: Card4[] = [
  ["rice", "cơm / gạo", "/raɪs/", "Lương thực chính ở châu Á. Không đếm được, không thêm 's'."],
  ["bread", "bánh mì", "/bred/", "'a loaf of bread' = một ổ bánh mì."],
  ["meat", "thịt", "/miːt/", "Đồng âm với 'meet' (gặp). Thịt nói chung."],
  ["chicken", "thịt gà / con gà", "/ˈtʃɪkɪn/", "Vừa chỉ con gà vừa chỉ thịt gà."],
  ["beef", "thịt bò", "/biːf/", "Thịt từ con bò (cow)."],
  ["pork", "thịt heo", "/pɔːrk/", "Thịt từ con heo (pig)."],
  ["fish", "cá", "/fɪʃ/", "Vừa con cá vừa món cá. Số nhiều giữ nguyên."],
  ["egg", "trứng", "/eɡ/", "'fried egg' = trứng chiên, 'boiled egg' = trứng luộc."],
  ["milk", "sữa", "/mɪlk/", "Không đếm được. 'a glass of milk' = một ly sữa."],
  ["cheese", "phô mai", "/tʃiːz/", "Làm từ sữa. 'Say cheese!' = cười lên (khi chụp ảnh)."],
  ["butter", "bơ", "/ˈbʌtər/", "Phết lên bánh mì. Khác 'avocado' (quả bơ)."],
  ["sugar", "đường", "/ˈʃʊɡər/", "'s' đầu đọc như 'sh'. Vị ngọt."],
  ["salt", "muối", "/sɔːlt/", "Vị mặn. 'salt and pepper' = muối và tiêu."],
  ["pepper", "tiêu / ớt chuông", "/ˈpepər/", "'black pepper' = tiêu đen."],
  ["oil", "dầu ăn", "/ɔɪl/", "'cooking oil' = dầu nấu ăn."],
  ["soup", "súp / canh", "/suːp/", "'a bowl of soup' = một tô súp."],
  ["noodle", "mì / bún", "/ˈnuːdl/", "Thường số nhiều 'noodles'."],
  ["fruit", "trái cây", "/fruːt/", "Nói chung không đếm. 'fresh fruit' = trái cây tươi."],
  ["apple", "táo", "/ˈæpl/", "'an apple a day' = mỗi ngày một quả táo."],
  ["banana", "chuối", "/bəˈnænə/", "Nhấn âm giữa: ba-NA-na."],
  ["orange", "cam", "/ˈɔːrɪndʒ/", "Vừa quả cam vừa màu cam."],
  ["grape", "nho", "/ɡreɪp/", "Thường số nhiều 'grapes' (chùm nho)."],
  ["lemon", "chanh vàng", "/ˈlemən/", "Vị chua. Khác 'lime' (chanh xanh)."],
  ["mango", "xoài", "/ˈmæŋɡoʊ/", "Số nhiều 'mangoes'."],
  ["watermelon", "dưa hấu", "/ˈwɔːtərmelən/", "Ghép 'water' + 'melon'."],
  ["strawberry", "dâu tây", "/ˈstrɔːberi/", "Quả đỏ có hạt bên ngoài."],
  ["pineapple", "dứa / thơm", "/ˈpaɪnæpl/", "Ghép 'pine' + 'apple'."],
  ["vegetable", "rau củ", "/ˈvedʒtəbl/", "Đọc gọn 3 âm: VEJ-tə-bl."],
  ["tomato", "cà chua", "/təˈmeɪtoʊ/", "Anh-Mỹ /təˈmeɪtoʊ/, Anh-Anh /təˈmɑːtəʊ/."],
  ["potato", "khoai tây", "/pəˈteɪtoʊ/", "Số nhiều 'potatoes'."],
  ["carrot", "cà rốt", "/ˈkærət/", "Củ màu cam, tốt cho mắt."],
  ["onion", "hành tây", "/ˈʌnjən/", "Bắt đầu bằng âm 'ʌ' (như 'un')."],
  ["garlic", "tỏi", "/ˈɡɑːrlɪk/", "Gia vị thơm, củ trắng nhiều tép."],
  ["salad", "rau trộn / sa lát", "/ˈsæləd/", "Món rau sống trộn."],
  ["mushroom", "nấm", "/ˈmʌʃruːm/", "Mọc ẩm ướt, hình ô."],
  ["corn", "ngô / bắp", "/kɔːrn/", "'sweet corn' = ngô ngọt."],
  ["bean", "đậu", "/biːn/", "Thường số nhiều 'beans'."],
  ["meal", "bữa ăn", "/miːl/", "'three meals a day' = ba bữa một ngày."],
  ["breakfast", "bữa sáng", "/ˈbrekfəst/", "'have breakfast' = ăn sáng."],
  ["lunch", "bữa trưa", "/lʌntʃ/", "'have lunch' = ăn trưa."],
  ["dinner", "bữa tối", "/ˈdɪnər/", "Bữa chính buổi tối."],
  ["snack", "đồ ăn vặt", "/snæk/", "Ăn nhẹ giữa các bữa."],
  ["dessert", "món tráng miệng", "/dɪˈzɜːrt/", "Nhấn âm sau. Khác 'desert' (sa mạc)."],
  ["cake", "bánh ngọt", "/keɪk/", "'birthday cake' = bánh sinh nhật."],
  ["cookie", "bánh quy", "/ˈkʊki/", "Anh-Anh gọi là 'biscuit'."],
  ["candy", "kẹo", "/ˈkændi/", "Anh-Anh gọi là 'sweets'."],
  ["chocolate", "sô cô la", "/ˈtʃɑːklət/", "Đọc gọn 2 âm: CHOK-lət."],
  ["ice cream", "kem", "/ˈaɪs kriːm/", "Món lạnh ngọt."],
  ["coffee", "cà phê", "/ˈkɔːfi/", "'a cup of coffee' = một tách cà phê."],
  ["tea", "trà", "/tiː/", "'green tea' = trà xanh."],
  ["juice", "nước ép", "/dʒuːs/", "'orange juice' = nước cam."],
  ["wine", "rượu vang", "/waɪn/", "'red wine' = vang đỏ."],
  ["beer", "bia", "/bɪr/", "Đồ uống có cồn từ lúa mạch."],
  ["plate", "cái đĩa", "/pleɪt/", "Đĩa phẳng đựng thức ăn."],
  ["bowl", "cái tô / bát", "/boʊl/", "Đựng súp, cơm. 'l' nhẹ."],
  ["cup", "cái tách / cốc", "/kʌp/", "'a cup of tea' = một tách trà."],
  ["glass", "cái ly thủy tinh", "/ɡlæs/", "Cũng nghĩa 'thủy tinh, kính'."],
  ["spoon", "cái thìa / muỗng", "/spuːn/", "Dùng để múc."],
  ["fork", "cái nĩa", "/fɔːrk/", "Dùng để xiên thức ăn."],
  ["knife", "con dao", "/naɪf/", "'k' câm. Số nhiều 'knives'."],
  ["cook", "nấu ăn / đầu bếp", "/kʊk/", "Vừa động từ vừa danh từ (người nấu)."],
  ["bake", "nướng (lò)", "/beɪk/", "Nướng bánh trong lò. 'bakery' = tiệm bánh."],
  ["fry", "chiên / rán", "/fraɪ/", "'fried rice' = cơm chiên."],
  ["boil", "luộc / đun sôi", "/bɔɪl/", "'boiled egg' = trứng luộc."],
  ["taste", "nếm / vị", "/teɪst/", "'It tastes good' = nó ngon."],
  ["sweet", "ngọt", "/swiːt/", "Vị của đường, kẹo."],
  ["sour", "chua", "/ˈsaʊər/", "Vị của chanh, giấm."],
  ["bitter", "đắng", "/ˈbɪtər/", "Vị của cà phê đen."],
  ["spicy", "cay", "/ˈspaɪsi/", "Vị của ớt. 'hot' cũng nghĩa cay."],
  ["fresh", "tươi", "/freʃ/", "'fresh vegetables' = rau tươi."],
  ["delicious", "ngon tuyệt", "/dɪˈlɪʃəs/", "Mạnh hơn 'good'. 'It's delicious' = ngon quá."],
  ["hungry", "đói", "/ˈhʌŋɡri/", "'I'm hungry' = tôi đói."],
  ["thirsty", "khát", "/ˈθɜːrsti/", "'I'm thirsty' = tôi khát nước."],
  ["full", "no", "/fʊl/", "'I'm full' = tôi no rồi."],
  ["dish", "món ăn / cái đĩa", "/dɪʃ/", "Vừa món ăn vừa đĩa lớn."],
  ["menu", "thực đơn", "/ˈmenjuː/", "Danh sách món ở nhà hàng."],
  ["restaurant", "nhà hàng", "/ˈrestrɑːnt/", "Đọc gọn: RES-tront."],
  ["kitchen", "nhà bếp", "/ˈkɪtʃɪn/", "Nơi nấu ăn trong nhà."],
  ["recipe", "công thức nấu ăn", "/ˈresəpi/", "3 âm: RES-ə-pi. Hướng dẫn nấu món."],
  ["flour", "bột mì", "/ˈflaʊər/", "Đồng âm với 'flower' (hoa)."],
  ["honey", "mật ong", "/ˈhʌni/", "Cũng dùng gọi yêu 'cưng'."],
  ["jam", "mứt", "/dʒæm/", "Phết lên bánh mì. Cũng nghĩa 'kẹt xe'."],
  ["sauce", "nước sốt", "/sɔːs/", "'soy sauce' = nước tương."],
  ["soy sauce", "nước tương / xì dầu", "/ˈsɔɪ sɔːs/", "Gia vị mặn màu nâu của châu Á."],
  ["vinegar", "giấm", "/ˈvɪnɪɡər/", "Chất lỏng chua dùng nêm."],
  ["flavor", "hương vị", "/ˈfleɪvər/", "Anh-Anh 'flavour'. Mùi vị món ăn."],
  ["serve", "phục vụ / dọn ra", "/sɜːrv/", "'serve dinner' = dọn bữa tối."],
  ["order", "gọi món / đặt hàng", "/ˈɔːrdər/", "'order food' = gọi đồ ăn."],
  ["bill", "hóa đơn", "/bɪl/", "Anh-Mỹ cũng dùng 'check'."],
  ["tip", "tiền boa / mẹo", "/tɪp/", "Tiền thưởng thêm cho phục vụ."],
  ["waiter", "bồi bàn (nam)", "/ˈweɪtər/", "Nữ là 'waitress'."],
  ["chef", "đầu bếp chính", "/ʃef/", "'ch' đọc như 'sh'. Bếp trưởng."],
  ["frozen", "đông lạnh", "/ˈfroʊzn/", "Quá khứ phân từ của 'freeze'."],
  ["raw", "sống (chưa nấu)", "/rɔː/", "'raw fish' = cá sống (sashimi)."],
  ["ripe", "chín (trái cây)", "/raɪp/", "Trái cây đã chín, sẵn ăn."],
  ["nut", "hạt (óc chó, đậu phộng)", "/nʌt/", "'peanut' = đậu phộng."],
  ["seafood", "hải sản", "/ˈsiːfuːd/", "Ghép 'sea' + 'food'. Tôm, cua, cá biển."],
  ["shrimp", "tôm", "/ʃrɪmp/", "Anh-Anh dùng 'prawn'."],
];

// ===== English_Basic_Home (en-US) — 100 house & home words =====
const englishBasicHome: Card4[] = [
  ["roof", "mái nhà", "/ruːf/", "Phần che trên cùng ngôi nhà."],
  ["wall", "bức tường", "/wɔːl/", "'on the wall' = trên tường."],
  ["floor", "sàn nhà / tầng", "/flɔːr/", "Cũng nghĩa 'tầng': 'first floor'."],
  ["ceiling", "trần nhà", "/ˈsiːlɪŋ/", "Mặt trên trong phòng. 'c' đọc /s/."],
  ["stairs", "cầu thang", "/sterz/", "Luôn số nhiều. 'go up the stairs' = lên cầu thang."],
  ["gate", "cổng", "/ɡeɪt/", "Cửa ở hàng rào, lối vào sân."],
  ["fence", "hàng rào", "/fens/", "Vây quanh sân, vườn."],
  ["garden", "khu vườn", "/ˈɡɑːrdn/", "Anh-Mỹ cũng dùng 'yard'."],
  ["garage", "nhà để xe", "/ɡəˈrɑːʒ/", "Nơi đậu xe hơi."],
  ["bedroom", "phòng ngủ", "/ˈbedruːm/", "Ghép 'bed' + 'room'."],
  ["bathroom", "phòng tắm / nhà vệ sinh", "/ˈbæθruːm/", "Nơi tắm rửa, vệ sinh."],
  ["living room", "phòng khách", "/ˈlɪvɪŋ ruːm/", "Nơi tiếp khách, xem TV."],
  ["dining room", "phòng ăn", "/ˈdaɪnɪŋ ruːm/", "Phòng đặt bàn ăn."],
  ["kitchen", "nhà bếp", "/ˈkɪtʃɪn/", "Nơi nấu nướng."],
  ["furniture", "đồ nội thất", "/ˈfɜːrnɪtʃər/", "Không đếm được. Bàn ghế tủ giường nói chung."],
  ["sofa", "ghế sô pha", "/ˈsoʊfə/", "Ghế dài. Anh-Anh dùng 'couch'."],
  ["shelf", "kệ / giá", "/ʃelf/", "Số nhiều 'shelves'. 'bookshelf' = kệ sách."],
  ["drawer", "ngăn kéo", "/drɔːr/", "Hộc kéo ra kéo vào trong tủ."],
  ["wardrobe", "tủ quần áo", "/ˈwɔːrdroʊb/", "Tủ lớn treo đồ."],
  ["mirror", "cái gương", "/ˈmɪrər/", "Soi để nhìn mình."],
  ["lamp", "đèn bàn", "/læmp/", "Đèn nhỏ để bàn hoặc đứng."],
  ["curtain", "rèm cửa", "/ˈkɜːrtn/", "Vải che cửa sổ."],
  ["carpet", "tấm thảm", "/ˈkɑːrpɪt/", "Trải sàn nhà."],
  ["pillow", "cái gối", "/ˈpɪloʊ/", "Kê đầu khi ngủ."],
  ["blanket", "cái chăn / mền", "/ˈblæŋkɪt/", "Đắp khi ngủ cho ấm."],
  ["sheet", "tấm ga giường", "/ʃiːt/", "Cũng nghĩa 'tờ giấy'."],
  ["towel", "khăn tắm", "/ˈtaʊəl/", "Lau khô người sau khi tắm."],
  ["toilet", "bồn cầu / nhà vệ sinh", "/ˈtɔɪlət/", "Cũng chỉ phòng vệ sinh (Anh-Anh)."],
  ["sink", "bồn rửa", "/sɪŋk/", "Rửa tay, rửa bát. Cũng động từ 'chìm'."],
  ["shower", "vòi sen / tắm vòi", "/ˈʃaʊər/", "'take a shower' = tắm vòi sen."],
  ["tap", "vòi nước", "/tæp/", "Anh-Mỹ dùng 'faucet'."],
  ["stove", "bếp lò", "/stoʊv/", "Nơi đặt nồi để nấu."],
  ["oven", "lò nướng", "/ˈʌvn/", "Nướng bánh, thịt. Bắt đầu âm 'ʌ'."],
  ["fridge", "tủ lạnh", "/frɪdʒ/", "Viết tắt của 'refrigerator'."],
  ["microwave", "lò vi sóng", "/ˈmaɪkrəweɪv/", "Hâm nóng nhanh thức ăn."],
  ["dishwasher", "máy rửa bát", "/ˈdɪʃwɑːʃər/", "Ghép 'dish' + 'washer'."],
  ["washing machine", "máy giặt", "/ˈwɑːʃɪŋ məˌʃiːn/", "Giặt quần áo tự động."],
  ["fan", "cái quạt", "/fæn/", "Cũng nghĩa 'người hâm mộ'."],
  ["heater", "máy sưởi", "/ˈhiːtər/", "Làm ấm phòng mùa lạnh."],
  ["air conditioner", "máy lạnh / điều hòa", "/er kənˈdɪʃənər/", "Viết tắt 'AC' hoặc 'aircon'."],
  ["television", "ti vi", "/ˈtelɪvɪʒn/", "Thường gọi tắt 'TV'."],
  ["remote", "điều khiển từ xa", "/rɪˈmoʊt/", "'remote control'. Cũng nghĩa 'xa xôi'."],
  ["clock", "đồng hồ (treo/để)", "/klɑːk/", "Khác 'watch' (đồng hồ đeo tay)."],
  ["key", "chìa khóa", "/kiː/", "'house key' = chìa khóa nhà."],
  ["lock", "ổ khóa / khóa lại", "/lɑːk/", "Vừa danh từ vừa động từ."],
  ["switch", "công tắc", "/swɪtʃ/", "'light switch' = công tắc đèn."],
  ["plug", "phích cắm / ổ cắm", "/plʌɡ/", "Cắm vào điện."],
  ["socket", "ổ điện", "/ˈsɑːkɪt/", "Lỗ cắm điện trên tường."],
  ["bulb", "bóng đèn", "/bʌlb/", "'light bulb' = bóng đèn."],
  ["candle", "cây nến", "/ˈkændl/", "Thắp sáng bằng lửa."],
  ["broom", "cây chổi", "/bruːm/", "Quét nhà."],
  ["bucket", "cái xô", "/ˈbʌkɪt/", "Đựng nước."],
  ["trash", "rác", "/træʃ/", "Anh-Anh dùng 'rubbish'. 'trash can' = thùng rác."],
  ["soap", "xà phòng", "/soʊp/", "Rửa cho sạch."],
  ["clean", "sạch / dọn dẹp", "/kliːn/", "Vừa tính từ vừa động từ. Trái nghĩa 'dirty'."],
  ["dirty", "bẩn", "/ˈdɜːrti/", "Trái nghĩa 'clean'."],
  ["tidy", "gọn gàng / dọn gọn", "/ˈtaɪdi/", "'tidy up' = dọn gọn lại."],
  ["messy", "bừa bộn", "/ˈmesi/", "Trái nghĩa 'tidy'."],
  ["sweep", "quét", "/swiːp/", "Quá khứ 'swept'. Quét sàn bằng chổi."],
  ["wash", "rửa / giặt", "/wɑːʃ/", "'wash hands' = rửa tay."],
  ["dry", "khô / làm khô", "/draɪ/", "Trái nghĩa 'wet'."],
  ["wet", "ướt", "/wet/", "Trái nghĩa 'dry'."],
  ["repair", "sửa chữa", "/rɪˈper/", "Đồng nghĩa 'fix'."],
  ["fix", "sửa", "/fɪks/", "'fix the door' = sửa cửa."],
  ["build", "xây dựng", "/bɪld/", "Quá khứ 'built'. Xây nhà."],
  ["paint", "sơn / vẽ", "/peɪnt/", "'paint the wall' = sơn tường."],
  ["hang", "treo", "/hæŋ/", "Quá khứ 'hung'. 'hang clothes' = treo quần áo."],
  ["move", "di chuyển / chuyển nhà", "/muːv/", "'move house' = chuyển nhà."],
  ["rent", "thuê / tiền thuê", "/rent/", "'rent an apartment' = thuê căn hộ."],
  ["apartment", "căn hộ", "/əˈpɑːrtmənt/", "Anh-Anh dùng 'flat'."],
  ["neighbor", "hàng xóm", "/ˈneɪbər/", "Anh-Anh 'neighbour'."],
  ["address", "địa chỉ", "/ˈædres/", "Nơi ở. Cũng động từ 'giải quyết'."],
  ["yard", "sân", "/jɑːrd/", "Khoảng sân quanh nhà."],
  ["balcony", "ban công", "/ˈbælkəni/", "Phần nhô ra ngoài tầng cao."],
  ["basement", "tầng hầm", "/ˈbeɪsmənt/", "Tầng dưới mặt đất."],
  ["attic", "gác mái", "/ˈætɪk/", "Khoảng trống dưới mái nhà."],
  ["hallway", "hành lang", "/ˈhɔːlweɪ/", "Lối đi nối các phòng."],
  ["entrance", "lối vào", "/ˈentrəns/", "Trái nghĩa 'exit'."],
  ["table", "cái bàn", "/ˈteɪbl/", "Mặt phẳng có chân."],
  ["desk", "bàn làm việc", "/desk/", "Bàn để học, làm việc."],
  ["cupboard", "tủ chén / tủ bếp", "/ˈkʌbərd/", "'p' câm: đọc 'KUB-əd'."],
  ["cabinet", "tủ có ngăn", "/ˈkæbɪnət/", "Tủ đựng đồ có cánh cửa."],
  ["bin", "thùng rác", "/bɪn/", "Anh-Anh phổ biến. 'dustbin'."],
  ["vacuum", "máy hút bụi / hút bụi", "/ˈvækjuːm/", "'vacuum cleaner' = máy hút bụi."],
  ["iron", "bàn ủi / ủi", "/ˈaɪərn/", "'r' câm kiểu Mỹ. Cũng nghĩa 'sắt'."],
  ["kettle", "ấm đun nước", "/ˈketl/", "Đun nước sôi pha trà."],
  ["pot", "cái nồi", "/pɑːt/", "Nấu canh, hầm."],
  ["pan", "cái chảo", "/pæn/", "'frying pan' = chảo chiên."],
  ["blender", "máy xay sinh tố", "/ˈblendər/", "Xay trái cây, đá."],
  ["toaster", "máy nướng bánh mì", "/ˈtoʊstər/", "Nướng lát bánh mì sandwich."],
  ["wire", "dây điện", "/ˈwaɪər/", "Dây dẫn điện."],
  ["pipe", "đường ống", "/paɪp/", "Dẫn nước. Cũng nghĩa 'tẩu thuốc'."],
  ["roofing", "vật liệu lợp mái", "/ˈruːfɪŋ/", "Ngói, tôn lợp mái."],
  ["doorbell", "chuông cửa", "/ˈdɔːrbel/", "Bấm để báo có khách."],
  ["mat", "tấm thảm chùi chân", "/mæt/", "'doormat' = thảm trước cửa."],
  ["shelf life", "hạn sử dụng", "/ˈʃelf laɪf/", "Thời gian giữ được của sản phẩm."],
  ["household", "hộ gia đình / việc nhà", "/ˈhaʊshoʊld/", "'household chores' = việc nhà."],
  ["chore", "việc vặt trong nhà", "/tʃɔːr/", "'do the chores' = làm việc nhà."],
  ["comfortable", "thoải mái", "/ˈkʌmftəbl/", "Đọc gọn: KUMF-tə-bl."],
  ["cozy", "ấm cúng", "/ˈkoʊzi/", "Nhỏ ấm dễ chịu. Anh-Anh 'cosy'."],
];

// ===== English_Basic_Body (en-US) — 100 body & health words =====
const englishBasicBody: Card4[] = [
  ["body", "cơ thể", "/ˈbɑːdi/", "Toàn bộ cơ thể người."],
  ["head", "cái đầu", "/hed/", "Phần trên cùng cơ thể."],
  ["face", "khuôn mặt", "/feɪs/", "Mặt trước của đầu."],
  ["hair", "tóc", "/her/", "Không đếm được khi nói tóc nói chung."],
  ["eye", "con mắt", "/aɪ/", "Cơ quan để nhìn. Số nhiều 'eyes'."],
  ["ear", "tai", "/ɪr/", "Cơ quan để nghe."],
  ["nose", "mũi", "/noʊz/", "Để thở và ngửi."],
  ["mouth", "miệng", "/maʊθ/", "Để ăn và nói."],
  ["tooth", "răng", "/tuːθ/", "Số nhiều bất quy tắc 'teeth'."],
  ["tongue", "lưỡi", "/tʌŋ/", "Để nếm và nói. 'g' câm."],
  ["lip", "môi", "/lɪp/", "Thường số nhiều 'lips'."],
  ["cheek", "má", "/tʃiːk/", "Hai bên khuôn mặt."],
  ["chin", "cằm", "/tʃɪn/", "Phần dưới miệng."],
  ["forehead", "trán", "/ˈfɔːrhed/", "Phần trên lông mày."],
  ["neck", "cổ", "/nek/", "Nối đầu với thân."],
  ["shoulder", "vai", "/ˈʃoʊldər/", "Nơi nối tay với thân."],
  ["arm", "cánh tay", "/ɑːrm/", "Từ vai đến bàn tay."],
  ["elbow", "khuỷu tay", "/ˈelboʊ/", "Khớp giữa cánh tay."],
  ["hand", "bàn tay", "/hænd/", "Đầu cánh tay, có ngón."],
  ["finger", "ngón tay", "/ˈfɪŋɡər/", "Mỗi bàn tay 5 ngón."],
  ["thumb", "ngón cái", "/θʌm/", "'b' câm. Ngón to nhất."],
  ["nail", "móng tay / móng chân", "/neɪl/", "Cũng nghĩa 'cái đinh'."],
  ["chest", "ngực", "/tʃest/", "Phần trước thân trên."],
  ["back", "lưng", "/bæk/", "Mặt sau cơ thể."],
  ["stomach", "bụng / dạ dày", "/ˈstʌmək/", "'stomachache' = đau bụng."],
  ["waist", "eo", "/weɪst/", "Phần thắt giữa thân. Đồng âm 'waste'."],
  ["hip", "hông", "/hɪp/", "Hai bên dưới eo."],
  ["leg", "chân (cẳng)", "/leɡ/", "Từ hông đến bàn chân."],
  ["knee", "đầu gối", "/niː/", "'k' câm. Khớp giữa chân."],
  ["foot", "bàn chân", "/fʊt/", "Số nhiều bất quy tắc 'feet'."],
  ["toe", "ngón chân", "/toʊ/", "Mỗi bàn chân 5 ngón."],
  ["heel", "gót chân", "/hiːl/", "Phần sau bàn chân."],
  ["skin", "da", "/skɪn/", "Lớp ngoài cơ thể."],
  ["bone", "xương", "/boʊn/", "Khung cứng bên trong."],
  ["blood", "máu", "/blʌd/", "Chất lỏng đỏ. Đọc 'blʌd' không 'blood'."],
  ["heart", "tim", "/hɑːrt/", "Bơm máu đi khắp cơ thể."],
  ["brain", "não", "/breɪn/", "Cơ quan suy nghĩ."],
  ["lung", "phổi", "/lʌŋ/", "Để thở. Thường số nhiều 'lungs'."],
  ["muscle", "cơ bắp", "/ˈmʌsl/", "'c' câm. Đọc 'MUS-l'."],
  ["health", "sức khỏe", "/helθ/", "'good health' = sức khỏe tốt."],
  ["healthy", "khỏe mạnh", "/ˈhelθi/", "Trái nghĩa 'sick/ill'."],
  ["sick", "ốm / bệnh", "/sɪk/", "'I feel sick' = tôi thấy mệt/buồn nôn."],
  ["ill", "ốm (Anh-Anh)", "/ɪl/", "Đồng nghĩa 'sick'."],
  ["pain", "cơn đau", "/peɪn/", "'in pain' = đang đau."],
  ["hurt", "đau / làm đau", "/hɜːrt/", "Quá khứ giữ nguyên 'hurt'. 'It hurts' = nó đau."],
  ["ache", "đau âm ỉ", "/eɪk/", "'ch' đọc /k/. 'headache' = đau đầu."],
  ["fever", "sốt", "/ˈfiːvər/", "'have a fever' = bị sốt."],
  ["cough", "ho", "/kɔːf/", "Đọc 'kɔːf'. Phản xạ ở họng."],
  ["cold", "cảm lạnh", "/koʊld/", "'catch a cold' = bị cảm."],
  ["flu", "cúm", "/fluː/", "Viết tắt 'influenza'."],
  ["headache", "đau đầu", "/ˈhedeɪk/", "Ghép 'head' + 'ache'."],
  ["wound", "vết thương", "/wuːnd/", "Đọc 'wuːnd'. Da bị rách."],
  ["injury", "chấn thương", "/ˈɪndʒəri/", "Tổn thương do tai nạn."],
  ["medicine", "thuốc", "/ˈmedɪsn/", "'take medicine' = uống thuốc."],
  ["pill", "viên thuốc", "/pɪl/", "Thuốc dạng viên nén."],
  ["doctor", "bác sĩ", "/ˈdɑːktər/", "Viết tắt 'Dr.'."],
  ["nurse", "y tá", "/nɜːrs/", "Chăm sóc bệnh nhân."],
  ["dentist", "nha sĩ", "/ˈdentɪst/", "Bác sĩ răng."],
  ["hospital", "bệnh viện", "/ˈhɑːspɪtl/", "Nơi điều trị bệnh."],
  ["clinic", "phòng khám", "/ˈklɪnɪk/", "Nhỏ hơn bệnh viện."],
  ["patient", "bệnh nhân / kiên nhẫn", "/ˈpeɪʃnt/", "Hai nghĩa tùy ngữ cảnh."],
  ["treatment", "việc điều trị", "/ˈtriːtmənt/", "Cách chữa bệnh."],
  ["cure", "chữa khỏi / phương thuốc", "/kjʊr/", "Làm hết bệnh hẳn."],
  ["recover", "hồi phục", "/rɪˈkʌvər/", "Khỏe lại sau bệnh."],
  ["breathe", "thở", "/briːð/", "Động từ. Danh từ là 'breath' /breθ/."],
  ["heartbeat", "nhịp tim", "/ˈhɑːrtbiːt/", "Tiếng tim đập."],
  ["weight", "cân nặng", "/weɪt/", "'lose weight' = giảm cân. 'w' câm? không, 'gh' câm."],
  ["height", "chiều cao", "/haɪt/", "'gh' câm. Đo bằng cm."],
  ["exercise", "tập thể dục", "/ˈeksərsaɪz/", "'do exercise' = tập luyện."],
  ["sleep", "giấc ngủ / ngủ", "/sliːp/", "Cần cho sức khỏe."],
  ["rest", "nghỉ ngơi", "/rest/", "'take a rest' = nghỉ một chút."],
  ["tired", "mệt", "/ˈtaɪərd/", "'I'm tired' = tôi mệt."],
  ["strong", "khỏe / mạnh", "/strɔːŋ/", "Trái nghĩa 'weak'."],
  ["weak", "yếu", "/wiːk/", "Đồng âm 'week' (tuần)."],
  ["fat", "béo / mỡ", "/fæt/", "Trái nghĩa 'thin'."],
  ["thin", "gầy / mỏng", "/θɪn/", "Trái nghĩa 'fat/thick'."],
  ["slim", "thon thả", "/slɪm/", "Gầy theo nghĩa tích cực."],
  ["tall", "cao", "/tɔːl/", "Chỉ chiều cao người, vật."],
  ["short", "thấp / ngắn", "/ʃɔːrt/", "Trái nghĩa 'tall/long'."],
  ["smile", "nụ cười / mỉm cười", "/smaɪl/", "Cười không thành tiếng."],
  ["laugh", "cười (thành tiếng)", "/læf/", "'gh' đọc /f/."],
  ["cry", "khóc", "/kraɪ/", "Chảy nước mắt."],
  ["sweat", "mồ hôi / đổ mồ hôi", "/swet/", "Đọc 'swet'. Khi nóng hoặc tập."],
  ["wash", "rửa / tắm rửa", "/wɑːʃ/", "Giữ vệ sinh."],
  ["brush", "chải / bàn chải", "/brʌʃ/", "'brush teeth' = đánh răng."],
  ["toothbrush", "bàn chải đánh răng", "/ˈtuːθbrʌʃ/", "Ghép 'tooth' + 'brush'."],
  ["toothpaste", "kem đánh răng", "/ˈtuːθpeɪst/", "Bóp lên bàn chải."],
  ["shampoo", "dầu gội", "/ʃæmˈpuː/", "Gội đầu. Nhấn âm sau."],
  ["diet", "chế độ ăn", "/ˈdaɪət/", "'on a diet' = đang ăn kiêng."],
  ["vitamin", "vi-ta-min", "/ˈvaɪtəmɪn/", "Anh-Mỹ /ˈvaɪ-/, Anh-Anh /ˈvɪt-/."],
  ["allergy", "dị ứng", "/ˈælərdʒi/", "'allergic to' = dị ứng với."],
  ["dizzy", "chóng mặt", "/ˈdɪzi/", "'feel dizzy' = thấy choáng."],
  ["nausea", "buồn nôn", "/ˈnɔːziə/", "Cảm giác muốn ói."],
  ["bandage", "băng gạc", "/ˈbændɪdʒ/", "Quấn vết thương."],
  ["surgery", "phẫu thuật", "/ˈsɜːrdʒəri/", "Mổ để chữa bệnh."],
  ["pulse", "mạch đập", "/pʌls/", "'take the pulse' = bắt mạch."],
  ["pregnant", "mang thai", "/ˈpreɡnənt/", "Đang có em bé."],
  ["wrist", "cổ tay", "/rɪst/", "'w' câm. Khớp nối bàn tay."],
  ["ankle", "mắt cá chân", "/ˈæŋkl/", "Khớp nối bàn chân."],
];

// ===== English_Inter_Work (en-US) — 100 workplace words =====
const englishInterWork: Card4[] = [
  ["job", "công việc / việc làm", "/dʒɑːb/", "Một vị trí cụ thể. Khác 'work' (việc nói chung)."],
  ["career", "sự nghiệp", "/kəˈrɪr/", "Cả quá trình nghề nghiệp lâu dài."],
  ["employee", "nhân viên", "/ɪmˈplɔɪiː/", "Người được thuê làm việc."],
  ["employer", "người sử dụng lao động", "/ɪmˈplɔɪər/", "Người/công ty thuê nhân viên."],
  ["colleague", "đồng nghiệp", "/ˈkɑːliːɡ/", "Người làm cùng công ty."],
  ["manager", "quản lý", "/ˈmænɪdʒər/", "Người điều hành nhóm."],
  ["staff", "nhân viên (tập thể)", "/stæf/", "Toàn bộ nhân viên. Không thêm 's'."],
  ["team", "đội nhóm", "/tiːm/", "'teamwork' = làm việc nhóm."],
  ["department", "phòng ban", "/dɪˈpɑːrtmənt/", "Bộ phận trong công ty."],
  ["company", "công ty", "/ˈkʌmpəni/", "Doanh nghiệp."],
  ["office", "văn phòng", "/ˈɔːfɪs/", "Nơi làm việc bàn giấy."],
  ["salary", "lương (tháng)", "/ˈsæləri/", "Trả cố định hàng tháng/năm."],
  ["wage", "lương (giờ/ngày)", "/weɪdʒ/", "Trả theo giờ làm."],
  ["income", "thu nhập", "/ˈɪnkʌm/", "Tổng tiền kiếm được."],
  ["bonus", "tiền thưởng", "/ˈboʊnəs/", "Thưởng thêm ngoài lương."],
  ["promotion", "thăng chức", "/prəˈmoʊʃn/", "Lên vị trí cao hơn."],
  ["interview", "phỏng vấn", "/ˈɪntərvjuː/", "'job interview' = phỏng vấn xin việc."],
  ["resume", "sơ yếu lý lịch", "/ˈrezəmeɪ/", "Anh-Anh dùng 'CV'."],
  ["apply", "nộp đơn / ứng tuyển", "/əˈplaɪ/", "'apply for a job' = xin việc."],
  ["hire", "thuê / tuyển", "/ˈhaɪər/", "Nhận người vào làm."],
  ["fire", "sa thải", "/ˈfaɪər/", "Đuổi việc. Cũng nghĩa 'lửa'."],
  ["resign", "từ chức / xin nghỉ", "/rɪˈzaɪn/", "'g' câm. Tự rời công việc."],
  ["retire", "nghỉ hưu", "/rɪˈtaɪər/", "Nghỉ làm khi về già."],
  ["task", "nhiệm vụ", "/tæsk/", "Việc cụ thể cần làm."],
  ["project", "dự án", "/ˈprɑːdʒekt/", "Danh từ nhấn âm đầu."],
  ["deadline", "hạn chót", "/ˈdedlaɪn/", "'meet the deadline' = kịp hạn."],
  ["meeting", "cuộc họp", "/ˈmiːtɪŋ/", "'have a meeting' = họp."],
  ["schedule", "lịch trình", "/ˈskedʒuːl/", "Anh-Anh /ˈʃedjuːl/."],
  ["appointment", "cuộc hẹn", "/əˈpɔɪntmənt/", "Hẹn gặp đã định trước."],
  ["report", "báo cáo", "/rɪˈpɔːrt/", "Vừa danh từ vừa động từ."],
  ["presentation", "bài thuyết trình", "/ˌpriːzenˈteɪʃn/", "Trình bày trước nhóm."],
  ["client", "khách hàng (dịch vụ)", "/ˈklaɪənt/", "Khách dùng dịch vụ."],
  ["customer", "khách hàng (mua)", "/ˈkʌstəmər/", "Người mua sản phẩm."],
  ["contract", "hợp đồng", "/ˈkɑːntrækt/", "Thỏa thuận pháp lý."],
  ["agreement", "thỏa thuận", "/əˈɡriːmənt/", "Sự đồng ý chung."],
  ["budget", "ngân sách", "/ˈbʌdʒɪt/", "Số tiền được phân bổ."],
  ["profit", "lợi nhuận", "/ˈprɑːfɪt/", "Tiền lãi. Trái nghĩa 'loss'."],
  ["loss", "thua lỗ", "/lɔːs/", "Mất tiền. Trái nghĩa 'profit'."],
  ["invest", "đầu tư", "/ɪnˈvest/", "Bỏ tiền để sinh lời."],
  ["customer service", "dịch vụ khách hàng", "/ˈkʌstəmər ˌsɜːrvɪs/", "Bộ phận hỗ trợ khách."],
  ["skill", "kỹ năng", "/skɪl/", "'soft skills' = kỹ năng mềm."],
  ["experience", "kinh nghiệm", "/ɪkˈspɪriəns/", "'work experience' = kinh nghiệm làm việc."],
  ["qualification", "bằng cấp / trình độ", "/ˌkwɑːlɪfɪˈkeɪʃn/", "Chứng chỉ đủ điều kiện."],
  ["training", "đào tạo / huấn luyện", "/ˈtreɪnɪŋ/", "Dạy kỹ năng cho nhân viên."],
  ["responsibility", "trách nhiệm", "/rɪˌspɑːnsəˈbɪləti/", "Việc mình phải lo."],
  ["duty", "nhiệm vụ / bổn phận", "/ˈduːti/", "'on duty' = đang trực."],
  ["position", "vị trí / chức vụ", "/pəˈzɪʃn/", "Cấp bậc trong công ty."],
  ["role", "vai trò", "/roʊl/", "Phần việc mình đảm nhận."],
  ["performance", "hiệu suất / màn thể hiện", "/pərˈfɔːrməns/", "Mức độ làm việc tốt."],
  ["productivity", "năng suất", "/ˌproʊdʌkˈtɪvəti/", "Lượng việc làm được."],
  ["efficient", "hiệu quả", "/ɪˈfɪʃnt/", "Làm tốt mà ít lãng phí."],
  ["overtime", "làm thêm giờ", "/ˈoʊvərtaɪm/", "Làm quá giờ quy định."],
  ["shift", "ca làm", "/ʃɪft/", "'night shift' = ca đêm."],
  ["leave", "nghỉ phép / rời đi", "/liːv/", "'sick leave' = nghỉ ốm."],
  ["vacation", "kỳ nghỉ", "/veɪˈkeɪʃn/", "Anh-Anh dùng 'holiday'."],
  ["benefit", "phúc lợi / lợi ích", "/ˈbenɪfɪt/", "Bảo hiểm, thưởng ngoài lương."],
  ["insurance", "bảo hiểm", "/ɪnˈʃʊrəns/", "'health insurance' = bảo hiểm y tế."],
  ["stakeholder", "bên liên quan", "/ˈsteɪkhoʊldər/", "Người/nhóm bị ảnh hưởng bởi dự án."],
  ["network", "mạng lưới quan hệ", "/ˈnetwɜːrk/", "'networking' = mở rộng quan hệ."],
  ["goal", "mục tiêu", "/ɡoʊl/", "Điều muốn đạt được."],
  ["target", "chỉ tiêu / mục tiêu", "/ˈtɑːrɡɪt/", "Con số cần đạt."],
  ["strategy", "chiến lược", "/ˈstrætədʒi/", "Kế hoạch dài hạn."],
  ["solution", "giải pháp", "/səˈluːʃn/", "Cách giải quyết vấn đề."],
  ["challenge", "thử thách", "/ˈtʃælɪndʒ/", "Việc khó cần vượt qua."],
  ["opportunity", "cơ hội", "/ˌɑːpərˈtuːnəti/", "Dịp tốt để phát triển."],
  ["decision", "quyết định", "/dɪˈsɪʒn/", "'make a decision' = ra quyết định."],
  ["approve", "phê duyệt", "/əˈpruːv/", "Đồng ý chính thức."],
  ["reject", "từ chối / bác bỏ", "/rɪˈdʒekt/", "Không chấp nhận."],
  ["feedback", "phản hồi / góp ý", "/ˈfiːdbæk/", "Nhận xét để cải thiện."],
  ["review", "đánh giá / xem lại", "/rɪˈvjuː/", "'performance review' = đánh giá năng lực."],
  ["evaluate", "đánh giá", "/ɪˈvæljueɪt/", "Xem xét chất lượng."],
  ["improve", "cải thiện", "/ɪmˈpruːv/", "Làm tốt hơn."],
  ["achieve", "đạt được", "/əˈtʃiːv/", "'achieve a goal' = đạt mục tiêu."],
  ["manage", "quản lý / xoay xở", "/ˈmænɪdʒ/", "Điều hành hoặc giải quyết được."],
  ["supervise", "giám sát", "/ˈsuːpərvaɪz/", "Trông coi người khác làm."],
  ["delegate", "giao việc / ủy quyền", "/ˈdelɪɡeɪt/", "Phân việc cho người dưới."],
  ["cooperate", "hợp tác", "/koʊˈɑːpəreɪt/", "Làm việc cùng nhau."],
  ["collaborate", "phối hợp", "/kəˈlæbəreɪt/", "Cùng tạo ra kết quả."],
  ["negotiate", "đàm phán", "/nɪˈɡoʊʃieɪt/", "Thương lượng để đạt thỏa thuận."],
  ["communicate", "giao tiếp", "/kəˈmjuːnɪkeɪt/", "Trao đổi thông tin."],
  ["organize", "tổ chức / sắp xếp", "/ˈɔːrɡənaɪz/", "Anh-Anh 'organise'."],
  ["prioritize", "ưu tiên", "/praɪˈɔːrətaɪz/", "Chọn việc quan trọng làm trước."],
  ["multitask", "làm nhiều việc cùng lúc", "/ˌmʌltiˈtæsk/", "Xử lý song song nhiều việc."],
  ["workload", "khối lượng công việc", "/ˈwɜːrkloʊd/", "Lượng việc phải làm."],
  ["colleague-friendly", "thân thiện đồng nghiệp", "/ˈkɑːliːɡ ˈfrendli/", "Môi trường dễ hợp tác."],
  ["freelance", "làm tự do", "/ˈfriːlæns/", "Làm thuê độc lập, không cố định một công ty."],
  ["recruit", "tuyển dụng", "/rɪˈkruːt/", "Tìm và nhận người mới."],
  ["candidate", "ứng viên", "/ˈkændɪdeɪt/", "Người dự tuyển."],
  ["probation", "thử việc", "/proʊˈbeɪʃn/", "Giai đoạn thử trước khi chính thức."],
  ["resignation", "đơn từ chức", "/ˌrezɪɡˈneɪʃn/", "Thông báo nghỉ việc."],
  ["workflow", "quy trình làm việc", "/ˈwɜːrkfloʊ/", "Trình tự các bước công việc."],
  ["overtime pay", "tiền làm thêm giờ", "/ˈoʊvərtaɪm peɪ/", "Lương cho giờ làm thêm."],
  ["subordinate", "cấp dưới", "/səˈbɔːrdɪnət/", "Người làm dưới quyền mình."],
  ["headquarters", "trụ sở chính", "/ˈhedkwɔːrtərz/", "Văn phòng chính của công ty."],
  ["branch", "chi nhánh", "/bræntʃ/", "Văn phòng phụ. Cũng nghĩa 'cành cây'."],
  ["industry", "ngành công nghiệp", "/ˈɪndəstri/", "Lĩnh vực kinh tế."],
  ["profession", "nghề chuyên môn", "/prəˈfeʃn/", "Nghề cần đào tạo (bác sĩ, luật sư)."],
  ["expertise", "chuyên môn", "/ˌekspɜːrˈtiːz/", "Kiến thức sâu về lĩnh vực."],
  ["mentor", "người cố vấn", "/ˈmentɔːr/", "Hướng dẫn người ít kinh nghiệm."],
  ["deadline-driven", "chạy theo hạn chót", "/ˈdedlaɪn ˈdrɪvn/", "Làm việc theo áp lực thời hạn."],
];

// ===== English_Inter_Travel (en-US) — 100 travel words =====
const englishInterTravel: Card4[] = [
  ["trip", "chuyến đi", "/trɪp/", "'business trip' = chuyến công tác."],
  ["journey", "hành trình", "/ˈdʒɜːrni/", "Chuyến đi dài, nhấn trải nghiệm."],
  ["travel", "đi du lịch / di chuyển", "/ˈtrævl/", "Động từ chung cho việc đi xa."],
  ["tour", "chuyến tham quan", "/tʊr/", "Đi vòng quanh, có hướng dẫn."],
  ["tourist", "khách du lịch", "/ˈtʊrɪst/", "Người đi tham quan."],
  ["destination", "điểm đến", "/ˌdestɪˈneɪʃn/", "Nơi mình muốn tới."],
  ["airport", "sân bay", "/ˈerpɔːrt/", "Nơi máy bay cất/hạ cánh."],
  ["flight", "chuyến bay", "/flaɪt/", "'book a flight' = đặt vé bay."],
  ["airline", "hãng hàng không", "/ˈerlaɪn/", "Công ty vận hành máy bay."],
  ["passport", "hộ chiếu", "/ˈpæspɔːrt/", "Giấy tờ đi nước ngoài."],
  ["visa", "thị thực", "/ˈviːzə/", "Giấy phép nhập cảnh."],
  ["ticket", "vé", "/ˈtɪkɪt/", "'one-way ticket' = vé một chiều."],
  ["boarding pass", "thẻ lên máy bay", "/ˈbɔːrdɪŋ pæs/", "Cấp sau khi check-in."],
  ["luggage", "hành lý", "/ˈlʌɡɪdʒ/", "Không đếm được. Đồng nghĩa 'baggage'."],
  ["suitcase", "vali", "/ˈsuːtkeɪs/", "Hộp đựng đồ khi đi xa."],
  ["backpack", "ba lô", "/ˈbækpæk/", "Túi đeo sau lưng."],
  ["check-in", "làm thủ tục", "/ˈtʃek ɪn/", "Đăng ký ở sân bay/khách sạn."],
  ["departure", "khởi hành", "/dɪˈpɑːrtʃər/", "Lúc rời đi. Trái nghĩa 'arrival'."],
  ["arrival", "đến nơi", "/əˈraɪvl/", "Lúc tới. Trái nghĩa 'departure'."],
  ["gate", "cổng ra máy bay", "/ɡeɪt/", "Cửa lên tàu bay ở sân bay."],
  ["terminal", "nhà ga (sân bay)", "/ˈtɜːrmɪnl/", "Tòa nhà ở sân bay."],
  ["customs", "hải quan", "/ˈkʌstəmz/", "Kiểm tra hàng hóa nhập cảnh."],
  ["immigration", "xuất nhập cảnh", "/ˌɪmɪˈɡreɪʃn/", "Kiểm tra hộ chiếu, visa."],
  ["delay", "trễ / hoãn", "/dɪˈleɪ/", "'flight delay' = chuyến bay trễ."],
  ["cancel", "hủy", "/ˈkænsl/", "Bỏ chuyến/đặt chỗ."],
  ["book", "đặt (vé/phòng)", "/bʊk/", "'book a room' = đặt phòng."],
  ["reservation", "việc đặt chỗ", "/ˌrezərˈveɪʃn/", "Giữ chỗ trước."],
  ["hotel", "khách sạn", "/hoʊˈtel/", "Nhấn âm sau: ho-TEL."],
  ["hostel", "nhà nghỉ giá rẻ", "/ˈhɑːstl/", "Rẻ, thường ở chung phòng."],
  ["guesthouse", "nhà khách", "/ˈɡesthaʊs/", "Nhỏ, kiểu gia đình."],
  ["room service", "dịch vụ phòng", "/ruːm ˈsɜːrvɪs/", "Mang đồ tới tận phòng."],
  ["check-out", "trả phòng", "/ˈtʃek aʊt/", "Rời khách sạn."],
  ["map", "bản đồ", "/mæp/", "Chỉ đường đi."],
  ["route", "lộ trình / tuyến đường", "/ruːt/", "Đường đi từ A đến B."],
  ["direction", "phương hướng / chỉ dẫn", "/dəˈrekʃn/", "'ask for directions' = hỏi đường."],
  ["distance", "khoảng cách", "/ˈdɪstəns/", "Bao xa giữa hai nơi."],
  ["abroad", "ở nước ngoài", "/əˈbrɔːd/", "'go abroad' = ra nước ngoài."],
  ["foreign", "nước ngoài / ngoại quốc", "/ˈfɔːrən/", "'g' câm. 'foreign country' = nước ngoài."],
  ["currency", "tiền tệ", "/ˈkɜːrənsi/", "Đồng tiền của một nước."],
  ["exchange", "đổi tiền / trao đổi", "/ɪksˈtʃeɪndʒ/", "'exchange rate' = tỷ giá."],
  ["budget", "ngân sách (chi tiêu)", "/ˈbʌdʒɪt/", "'budget travel' = du lịch tiết kiệm."],
  ["souvenir", "quà lưu niệm", "/ˌsuːvəˈnɪr/", "Mua làm kỷ niệm chuyến đi."],
  ["sightseeing", "tham quan ngắm cảnh", "/ˈsaɪtsiːɪŋ/", "Đi xem danh lam."],
  ["landmark", "địa danh nổi tiếng", "/ˈlændmɑːrk/", "Công trình/điểm dễ nhận biết."],
  ["beach", "bãi biển", "/biːtʃ/", "Bờ cát ven biển."],
  ["mountain", "núi", "/ˈmaʊntn/", "Địa hình cao."],
  ["village", "ngôi làng", "/ˈvɪlɪdʒ/", "Khu dân cư nhỏ ở quê."],
  ["countryside", "vùng quê", "/ˈkʌntrisaɪd/", "Ngoài thành phố."],
  ["adventure", "cuộc phiêu lưu", "/ədˈventʃər/", "Trải nghiệm mạo hiểm."],
  ["explore", "khám phá", "/ɪkˈsplɔːr/", "Đi tìm hiểu nơi mới."],
  ["guide", "hướng dẫn viên / hướng dẫn", "/ɡaɪd/", "'tour guide' = HDV du lịch."],
  ["itinerary", "lịch trình chuyến đi", "/aɪˈtɪnəreri/", "Kế hoạch đi từng ngày."],
  ["accommodation", "chỗ ở", "/əˌkɑːməˈdeɪʃn/", "Nơi nghỉ khi đi xa."],
  ["departure lounge", "phòng chờ", "/dɪˈpɑːrtʃər laʊndʒ/", "Chờ trước giờ bay."],
  ["jet lag", "lệch múi giờ", "/ˈdʒet læɡ/", "Mệt do bay qua nhiều múi giờ."],
  ["transit", "quá cảnh", "/ˈtrænzɪt/", "Dừng giữa chừng để đổi chuyến."],
  ["domestic", "nội địa", "/dəˈmestɪk/", "Trong nước. Trái nghĩa 'international'."],
  ["international", "quốc tế", "/ˌɪntərˈnæʃnəl/", "Giữa các nước."],
  ["one-way", "một chiều", "/ˌwʌn ˈweɪ/", "Vé chỉ đi không về."],
  ["round-trip", "khứ hồi", "/ˌraʊnd ˈtrɪp/", "Vé đi và về. Anh-Anh 'return'."],
  ["aisle", "lối đi (ghế)", "/aɪl/", "'s' câm. 'aisle seat' = ghế cạnh lối đi."],
  ["window seat", "ghế cạnh cửa sổ", "/ˈwɪndoʊ siːt/", "Ngồi sát cửa sổ máy bay."],
  ["carry-on", "hành lý xách tay", "/ˈkæri ɑːn/", "Mang lên cabin."],
  ["overweight", "quá cân (hành lý)", "/ˌoʊvərˈweɪt/", "Vượt giới hạn cân nặng."],
  ["passenger", "hành khách", "/ˈpæsɪndʒər/", "Người đi trên phương tiện."],
  ["crew", "phi hành đoàn / tổ bay", "/kruː/", "Nhân viên trên máy bay."],
  ["pilot", "phi công", "/ˈpaɪlət/", "Người lái máy bay."],
  ["cabin", "khoang (máy bay)", "/ˈkæbɪn/", "Chỗ ngồi hành khách."],
  ["seatbelt", "dây an toàn", "/ˈsiːtbelt/", "Thắt khi ngồi xe/máy bay."],
  ["station", "nhà ga (tàu)", "/ˈsteɪʃn/", "'train station' = ga tàu."],
  ["platform", "sân ga", "/ˈplætfɔːrm/", "Nơi đứng chờ tàu."],
  ["railway", "đường sắt", "/ˈreɪlweɪ/", "Anh-Mỹ 'railroad'."],
  ["subway", "tàu điện ngầm", "/ˈsʌbweɪ/", "Anh-Anh dùng 'underground/tube'."],
  ["taxi", "tắc xi", "/ˈtæksi/", "Xe chở thuê. Cũng 'cab'."],
  ["ferry", "phà", "/ˈferi/", "Tàu chở người/xe qua sông biển."],
  ["cruise", "du thuyền / chuyến tàu biển", "/kruːz/", "Du lịch bằng tàu lớn."],
  ["harbor", "bến cảng", "/ˈhɑːrbər/", "Anh-Anh 'harbour'. Nơi tàu đậu."],
  ["border", "biên giới", "/ˈbɔːrdər/", "Ranh giới giữa hai nước."],
  ["embassy", "đại sứ quán", "/ˈembəsi/", "Cơ quan đại diện nước ngoài."],
  ["local", "người/của địa phương", "/ˈloʊkl/", "'local food' = món địa phương."],
  ["culture", "văn hóa", "/ˈkʌltʃər/", "Phong tục, lối sống."],
  ["custom", "phong tục", "/ˈkʌstəm/", "Tập quán địa phương."],
  ["language", "ngôn ngữ", "/ˈlæŋɡwɪdʒ/", "Tiếng nói của một nơi."],
  ["phrasebook", "sách hội thoại", "/ˈfreɪzbʊk/", "Cẩm nang câu giao tiếp du lịch."],
  ["wander", "đi lang thang", "/ˈwɑːndər/", "Đi không định hướng."],
  ["depart", "khởi hành", "/dɪˈpɑːrt/", "Động từ của 'departure'."],
  ["arrive", "đến nơi", "/əˈraɪv/", "Động từ của 'arrival'."],
  ["pack", "đóng gói / xếp đồ", "/pæk/", "'pack a suitcase' = xếp vali."],
  ["unpack", "dỡ đồ ra", "/ˌʌnˈpæk/", "Lấy đồ khỏi vali."],
  ["postpone", "hoãn lại", "/poʊˈspoʊn/", "Dời sang lúc khác."],
  ["scenery", "phong cảnh", "/ˈsiːnəri/", "Cảnh đẹp tự nhiên."],
  ["resort", "khu nghỉ dưỡng", "/rɪˈzɔːrt/", "Nơi nghỉ cao cấp."],
  ["camping", "cắm trại", "/ˈkæmpɪŋ/", "Ngủ lều ngoài trời."],
  ["hiking", "đi bộ đường dài", "/ˈhaɪkɪŋ/", "Leo núi, đi rừng."],
  ["visa-free", "miễn thị thực", "/ˈviːzə friː/", "Không cần visa để nhập cảnh."],
  ["layover", "chặng dừng nối chuyến", "/ˈleɪoʊvər/", "Dừng chờ đổi máy bay."],
  ["fare", "giá vé (xe/tàu)", "/fer/", "Đồng âm 'fair'. Tiền đi phương tiện."],
  ["roam", "đi rong / chuyển vùng", "/roʊm/", "'roaming' = chuyển vùng điện thoại."],
  ["voyage", "chuyến đi biển dài", "/ˈvɔɪɪdʒ/", "Hành trình trên biển."],
];

// ===== English_Inter_Emotion (en-US) — 100 feelings & emotion words =====
const englishInterEmotion: Card4[] = [
  ["emotion", "cảm xúc", "/ɪˈmoʊʃn/", "Trạng thái tình cảm nói chung."],
  ["feeling", "cảm giác", "/ˈfiːlɪŋ/", "'mixed feelings' = cảm xúc lẫn lộn."],
  ["mood", "tâm trạng", "/muːd/", "'in a good mood' = tâm trạng tốt."],
  ["happy", "vui / hạnh phúc", "/ˈhæpi/", "Cảm xúc tích cực cơ bản."],
  ["joy", "niềm vui sướng", "/dʒɔɪ/", "Vui mạnh hơn 'happy'."],
  ["glad", "mừng / vui", "/ɡlæd/", "'I'm glad' = tôi mừng."],
  ["delighted", "rất vui mừng", "/dɪˈlaɪtɪd/", "Vui hơn 'happy', trang trọng."],
  ["excited", "phấn khích", "/ɪkˈsaɪtɪd/", "Hào hứng chờ đợi điều gì."],
  ["cheerful", "vui vẻ / yêu đời", "/ˈtʃɪrfl/", "Tính cách hay cười."],
  ["proud", "tự hào", "/praʊd/", "'proud of' = tự hào về."],
  ["grateful", "biết ơn", "/ˈɡreɪtfl/", "Đồng nghĩa 'thankful'."],
  ["satisfied", "hài lòng", "/ˈsætɪsfaɪd/", "Thấy đủ, vừa ý."],
  ["relieved", "nhẹ nhõm", "/rɪˈliːvd/", "Hết lo lắng."],
  ["calm", "bình tĩnh", "/kɑːm/", "'l' câm. Không lo, không giận."],
  ["peaceful", "yên bình", "/ˈpiːsfl/", "Tĩnh lặng dễ chịu."],
  ["confident", "tự tin", "/ˈkɑːnfɪdənt/", "Tin vào bản thân."],
  ["hopeful", "đầy hy vọng", "/ˈhoʊpfl/", "Tin điều tốt sẽ đến."],
  ["sad", "buồn", "/sæd/", "Trái nghĩa 'happy'."],
  ["unhappy", "không vui", "/ʌnˈhæpi/", "Buồn nhẹ, không hài lòng."],
  ["upset", "buồn bực / khó chịu", "/ʌpˈset/", "Bực và buồn lẫn lộn."],
  ["depressed", "trầm cảm / chán nản", "/dɪˈprest/", "Buồn sâu, kéo dài."],
  ["miserable", "khốn khổ", "/ˈmɪzrəbl/", "Rất bất hạnh."],
  ["lonely", "cô đơn", "/ˈloʊnli/", "Buồn vì thiếu bạn bè."],
  ["disappointed", "thất vọng", "/ˌdɪsəˈpɔɪntɪd/", "Buồn vì không như mong đợi."],
  ["heartbroken", "đau lòng / tan vỡ", "/ˈhɑːrtbroʊkən/", "Rất buồn, thường vì tình."],
  ["angry", "tức giận", "/ˈæŋɡri/", "'angry at/with' = giận với."],
  ["furious", "giận dữ (cực độ)", "/ˈfjʊriəs/", "Giận hơn 'angry' rất nhiều."],
  ["annoyed", "bực mình", "/əˈnɔɪd/", "Khó chịu nhẹ."],
  ["frustrated", "bức bối / nản", "/ˈfrʌstreɪtɪd/", "Bực vì bị cản trở."],
  ["irritated", "cáu kỉnh", "/ˈɪrɪteɪtɪd/", "Khó chịu, dễ nổi nóng."],
  ["jealous", "ghen / ganh tị", "/ˈdʒeləs/", "'jealous of' = ghen với."],
  ["envious", "ganh tị", "/ˈenviəs/", "Muốn cái người khác có."],
  ["afraid", "sợ hãi", "/əˈfreɪd/", "'afraid of' = sợ cái gì."],
  ["scared", "sợ", "/skerd/", "Đồng nghĩa 'afraid', thông dụng."],
  ["frightened", "hoảng sợ", "/ˈfraɪtnd/", "Sợ đột ngột."],
  ["terrified", "khiếp sợ", "/ˈterɪfaɪd/", "Sợ cực độ."],
  ["nervous", "lo lắng / hồi hộp", "/ˈnɜːrvəs/", "Bồn chồn trước sự kiện."],
  ["anxious", "lo âu", "/ˈæŋkʃəs/", "Lo lắng kéo dài."],
  ["worried", "lo lắng", "/ˈwɜːrid/", "'worried about' = lo về."],
  ["stressed", "căng thẳng", "/strest/", "Áp lực nhiều."],
  ["tense", "căng thẳng (cứng)", "/tens/", "Cơ thể/không khí căng."],
  ["uncomfortable", "không thoải mái", "/ʌnˈkʌmftəbl/", "Thấy gượng, khó chịu."],
  ["embarrassed", "ngượng ngùng", "/ɪmˈbærəst/", "Xấu hổ trước người khác."],
  ["ashamed", "xấu hổ / hổ thẹn", "/əˈʃeɪmd/", "Hổ thẹn vì điều mình làm."],
  ["guilty", "tội lỗi / áy náy", "/ˈɡɪlti/", "Thấy mình làm sai."],
  ["confused", "bối rối", "/kənˈfjuːzd/", "Không hiểu, rối trí."],
  ["surprised", "ngạc nhiên", "/sərˈpraɪzd/", "Bất ngờ."],
  ["shocked", "sốc / choáng", "/ʃɑːkt/", "Ngạc nhiên mạnh, tiêu cực."],
  ["amazed", "kinh ngạc (tốt)", "/əˈmeɪzd/", "Ngạc nhiên thán phục."],
  ["curious", "tò mò", "/ˈkjʊriəs/", "Muốn biết thêm."],
  ["bored", "chán", "/bɔːrd/", "'bored of/with' = chán cái gì."],
  ["tired", "mệt mỏi", "/ˈtaɪərd/", "Mệt thể chất/tinh thần."],
  ["exhausted", "kiệt sức", "/ɪɡˈzɔːstɪd/", "Mệt cực độ."],
  ["disgusted", "ghê tởm", "/dɪsˈɡʌstɪd/", "Thấy kinh tởm."],
  ["hurt", "tổn thương (lòng)", "/hɜːrt/", "Bị làm đau về tình cảm."],
  ["hopeless", "tuyệt vọng", "/ˈhoʊpləs/", "Mất hết hy vọng."],
  ["desperate", "tuyệt vọng / cùng quẫn", "/ˈdespərət/", "Liều lĩnh vì hết cách."],
  ["overwhelmed", "quá tải cảm xúc", "/ˌoʊvərˈwelmd/", "Bị tràn ngập, không xử nổi."],
  ["calm down", "bình tĩnh lại", "/kɑːm daʊn/", "Cụm: hạ cơn giận/lo."],
  ["cheer up", "vui lên", "/tʃɪr ʌp/", "Cụm: làm ai bớt buồn."],
  ["sympathy", "sự thông cảm", "/ˈsɪmpəθi/", "Hiểu nỗi buồn người khác."],
  ["empathy", "sự đồng cảm", "/ˈempəθi/", "Cảm nhận như chính họ."],
  ["compassion", "lòng trắc ẩn", "/kəmˈpæʃn/", "Thương xót muốn giúp."],
  ["affection", "sự trìu mến", "/əˈfekʃn/", "Tình cảm yêu thương nhẹ."],
  ["passion", "đam mê / nhiệt huyết", "/ˈpæʃn/", "Cảm xúc mãnh liệt."],
  ["desire", "khao khát", "/dɪˈzaɪər/", "Mong muốn mạnh."],
  ["regret", "hối tiếc", "/rɪˈɡret/", "Tiếc về điều đã làm."],
  ["disgust", "sự ghê tởm", "/dɪsˈɡʌst/", "Danh từ của 'disgusted'."],
  ["pride", "niềm tự hào / kiêu hãnh", "/praɪd/", "Danh từ của 'proud'."],
  ["fear", "nỗi sợ", "/fɪr/", "Danh từ của 'afraid'."],
  ["anger", "cơn giận", "/ˈæŋɡər/", "Danh từ của 'angry'."],
  ["grief", "nỗi đau buồn", "/ɡriːf/", "Buồn vì mất mát (người thân)."],
  ["loneliness", "sự cô đơn", "/ˈloʊnlinəs/", "Danh từ của 'lonely'."],
  ["jealousy", "sự ghen tị", "/ˈdʒeləsi/", "Danh từ của 'jealous'."],
  ["gratitude", "lòng biết ơn", "/ˈɡrætɪtuːd/", "Danh từ của 'grateful'."],
  ["comfort", "an ủi / sự dễ chịu", "/ˈkʌmfərt/", "Làm ai bớt buồn."],
  ["encourage", "động viên", "/ɪnˈkɜːrɪdʒ/", "Khích lệ ai đó."],
  ["mood swing", "thay đổi tâm trạng", "/muːd swɪŋ/", "Cảm xúc lên xuống thất thường."],
  ["sensitive", "nhạy cảm", "/ˈsensətɪv/", "Dễ xúc động."],
  ["emotional", "giàu cảm xúc / dễ xúc động", "/ɪˈmoʊʃənl/", "Hay bộc lộ cảm xúc."],
  ["temper", "tính khí / cơn nóng giận", "/ˈtempər/", "'lose your temper' = nổi nóng."],
  ["patient", "kiên nhẫn", "/ˈpeɪʃnt/", "Bình tĩnh chờ đợi."],
  ["impatient", "thiếu kiên nhẫn", "/ɪmˈpeɪʃnt/", "Nóng vội."],
  ["optimistic", "lạc quan", "/ˌɑːptɪˈmɪstɪk/", "Nghĩ tích cực."],
  ["pessimistic", "bi quan", "/ˌpesɪˈmɪstɪk/", "Nghĩ tiêu cực."],
  ["motivated", "có động lực", "/ˈmoʊtɪveɪtɪd/", "Có hứng làm việc."],
  ["inspired", "được truyền cảm hứng", "/ɪnˈspaɪərd/", "Thấy muốn sáng tạo/hành động."],
  ["content", "mãn nguyện", "/kənˈtent/", "Hài lòng yên ổn (nhấn âm sau)."],
  ["thrilled", "vô cùng phấn khích", "/θrɪld/", "Vui sướng tột độ."],
  ["amused", "thấy buồn cười / thích thú", "/əˈmjuːzd/", "Được giải trí."],
  ["sorrow", "nỗi sầu", "/ˈsɑːroʊ/", "Buồn sâu sắc, văn chương."],
  ["resent", "oán giận", "/rɪˈzent/", "Giận âm ỉ vì bị đối xử tệ."],
  ["panic", "hoảng loạn", "/ˈpænɪk/", "Sợ mất kiểm soát."],
  ["relief", "sự nhẹ nhõm", "/rɪˈliːf/", "Danh từ của 'relieved'."],
  ["doubt", "nghi ngờ", "/daʊt/", "'b' câm. Không chắc chắn."],
  ["trust", "tin tưởng", "/trʌst/", "Tin vào ai/điều gì."],
  ["self-esteem", "lòng tự trọng", "/self ɪˈstiːm/", "Cách mình đánh giá bản thân."],
  ["mindful", "chú tâm / tỉnh thức", "/ˈmaɪndfl/", "Ý thức hiện tại, bình an."],
];

// ===== English_Advanced_Business (en-US) — 100 business/finance words =====
const englishAdvancedBusiness: Card4[] = [
  ["revenue", "doanh thu", "/ˈrevənuː/", "Tổng tiền bán hàng trước chi phí."],
  ["turnover", "doanh thu / tỷ lệ nghỉ việc", "/ˈtɜːrnoʊvər/", "Anh-Anh = doanh thu; cũng = tỷ lệ thay nhân sự."],
  ["profit margin", "biên lợi nhuận", "/ˈprɑːfɪt ˈmɑːrdʒɪn/", "Lợi nhuận trên mỗi đồng doanh thu."],
  ["overhead", "chi phí cố định", "/ˈoʊvərhed/", "Chi phí vận hành (thuê, điện, lương)."],
  ["asset", "tài sản", "/ˈæset/", "Thứ có giá trị công ty sở hữu."],
  ["liability", "khoản nợ / trách nhiệm pháp lý", "/ˌlaɪəˈbɪləti/", "Nghĩa vụ tài chính phải trả."],
  ["equity", "vốn chủ sở hữu / cổ phần", "/ˈekwəti/", "Phần sở hữu sau khi trừ nợ."],
  ["capital", "vốn", "/ˈkæpɪtl/", "Tiền/tài sản để kinh doanh."],
  ["investment", "khoản đầu tư", "/ɪnˈvestmənt/", "Bỏ vốn để sinh lời."],
  ["shareholder", "cổ đông", "/ˈʃerhoʊldər/", "Người sở hữu cổ phần."],
  ["stakeholder", "bên liên quan", "/ˈsteɪkhoʊldər/", "Bất kỳ ai chịu ảnh hưởng từ công ty."],
  ["dividend", "cổ tức", "/ˈdɪvɪdend/", "Lợi nhuận chia cho cổ đông."],
  ["merger", "sáp nhập", "/ˈmɜːrdʒər/", "Hai công ty hợp thành một."],
  ["acquisition", "thâu tóm / mua lại", "/ˌækwɪˈzɪʃn/", "Công ty mua công ty khác."],
  ["startup", "công ty khởi nghiệp", "/ˈstɑːrtʌp/", "Doanh nghiệp mới, tăng trưởng nhanh."],
  ["entrepreneur", "doanh nhân khởi nghiệp", "/ˌɑːntrəprəˈnɜːr/", "Người lập và điều hành doanh nghiệp."],
  ["corporation", "tập đoàn", "/ˌkɔːrpəˈreɪʃn/", "Công ty lớn có tư cách pháp nhân."],
  ["enterprise", "doanh nghiệp", "/ˈentərpraɪz/", "Tổ chức kinh doanh."],
  ["subsidiary", "công ty con", "/səbˈsɪdieri/", "Do công ty mẹ kiểm soát."],
  ["competitor", "đối thủ cạnh tranh", "/kəmˈpetɪtər/", "Công ty cùng thị trường."],
  ["market share", "thị phần", "/ˈmɑːrkɪt ʃer/", "Phần thị trường công ty chiếm."],
  ["supply chain", "chuỗi cung ứng", "/səˈplaɪ tʃeɪn/", "Từ nguyên liệu đến sản phẩm cuối."],
  ["logistics", "hậu cần / vận chuyển", "/ləˈdʒɪstɪks/", "Quản lý lưu thông hàng hóa."],
  ["inventory", "hàng tồn kho", "/ˈɪnvəntɔːri/", "Hàng còn trong kho."],
  ["wholesale", "bán sỉ", "/ˈhoʊlseɪl/", "Bán số lượng lớn giá thấp."],
  ["retail", "bán lẻ", "/ˈriːteɪl/", "Bán trực tiếp cho người dùng."],
  ["procurement", "thu mua", "/prəˈkjʊrmənt/", "Quy trình mua hàng/dịch vụ."],
  ["forecast", "dự báo", "/ˈfɔːrkæst/", "'sales forecast' = dự báo doanh số."],
  ["quarter", "quý (3 tháng)", "/ˈkwɔːrtər/", "'Q1, Q2...' báo cáo theo quý."],
  ["fiscal year", "năm tài chính", "/ˈfɪskl jɪr/", "Năm kế toán của công ty."],
  ["audit", "kiểm toán", "/ˈɔːdɪt/", "Kiểm tra sổ sách tài chính."],
  ["compliance", "tuân thủ", "/kəmˈplaɪəns/", "Theo đúng luật và quy định."],
  ["regulation", "quy định", "/ˌreɡjuˈleɪʃn/", "Luật lệ ngành phải theo."],
  ["invoice", "hóa đơn (yêu cầu thanh toán)", "/ˈɪnvɔɪs/", "Chứng từ đòi tiền hàng."],
  ["receipt", "biên lai", "/rɪˈsiːt/", "'p' câm. Bằng chứng đã trả tiền."],
  ["transaction", "giao dịch", "/trænˈzækʃn/", "Một lần mua/bán/chuyển tiền."],
  ["cash flow", "dòng tiền", "/kæʃ floʊ/", "Tiền ra vào doanh nghiệp."],
  ["debt", "nợ", "/det/", "'b' câm. Tiền phải trả."],
  ["credit", "tín dụng / ghi có", "/ˈkredɪt/", "Vay được dựa trên uy tín."],
  ["loan", "khoản vay", "/loʊn/", "Tiền mượn phải trả lãi."],
  ["interest rate", "lãi suất", "/ˈɪntrəst reɪt/", "% phải trả khi vay."],
  ["mortgage", "thế chấp / khoản vay mua nhà", "/ˈmɔːrɡɪdʒ/", "'t' câm. Vay có tài sản bảo đảm."],
  ["bankrupt", "phá sản", "/ˈbæŋkrʌpt/", "Hết khả năng trả nợ."],
  ["recession", "suy thoái", "/rɪˈseʃn/", "Kinh tế đi xuống."],
  ["inflation", "lạm phát", "/ɪnˈfleɪʃn/", "Giá cả tăng, tiền mất giá."],
  ["stock", "cổ phiếu / hàng dự trữ", "/stɑːk/", "'stock market' = thị trường chứng khoán."],
  ["share", "cổ phần", "/ʃer/", "Một phần sở hữu công ty."],
  ["bond", "trái phiếu", "/bɑːnd/", "Giấy nợ trả lãi cố định."],
  ["portfolio", "danh mục đầu tư", "/pɔːrtˈfoʊlioʊ/", "Tập hợp các khoản đầu tư."],
  ["valuation", "định giá", "/ˌvæljuˈeɪʃn/", "Xác định giá trị công ty."],
  ["benchmark", "chuẩn so sánh", "/ˈbentʃmɑːrk/", "Mốc để đánh giá hiệu quả."],
  ["leverage", "đòn bẩy / tận dụng", "/ˈlevərɪdʒ/", "Dùng vốn vay để khuếch đại lợi nhuận."],
  ["liquidity", "tính thanh khoản", "/lɪˈkwɪdəti/", "Khả năng đổi tài sản ra tiền mặt."],
  ["depreciation", "khấu hao", "/dɪˌpriːʃiˈeɪʃn/", "Giảm giá trị tài sản theo thời gian."],
  ["overhead cost", "chi phí chung", "/ˈoʊvərhed kɔːst/", "Chi phí không trực tiếp sản xuất."],
  ["margin", "biên / khoản chênh", "/ˈmɑːrdʒɪn/", "Chênh giữa giá vốn và giá bán."],
  ["niche", "thị trường ngách", "/niːʃ/", "Phân khúc nhỏ chuyên biệt."],
  ["outsource", "thuê ngoài", "/ˈaʊtsɔːrs/", "Giao việc cho bên thứ ba."],
  ["scalable", "có thể mở rộng", "/ˈskeɪləbl/", "Tăng quy mô không tăng chi phí nhiều."],
  ["sustainable", "bền vững", "/səˈsteɪnəbl/", "Duy trì lâu dài không cạn kiệt."],
  ["incentive", "ưu đãi / động lực", "/ɪnˈsentɪv/", "Thưởng để khuyến khích."],
  ["commission", "tiền hoa hồng", "/kəˈmɪʃn/", "% thưởng theo doanh số bán."],
  ["quota", "hạn ngạch / chỉ tiêu", "/ˈkwoʊtə/", "Mức bắt buộc đạt."],
  ["pipeline", "tiến trình bán hàng / chuỗi", "/ˈpaɪplaɪn/", "Các cơ hội đang xử lý."],
  ["lead", "khách hàng tiềm năng", "/liːd/", "Người có thể thành khách hàng."],
  ["conversion", "tỷ lệ chuyển đổi", "/kənˈvɜːrʒn/", "Lead thành khách thật."],
  ["churn", "tỷ lệ rời bỏ", "/tʃɜːrn/", "Khách hàng ngừng dùng dịch vụ."],
  ["retention", "giữ chân khách hàng", "/rɪˈtenʃn/", "Trái nghĩa 'churn'."],
  ["brand", "thương hiệu", "/brænd/", "Hình ảnh, danh tiếng sản phẩm."],
  ["marketing", "tiếp thị", "/ˈmɑːrkɪtɪŋ/", "Quảng bá để bán hàng."],
  ["campaign", "chiến dịch", "/kæmˈpeɪn/", "'g' câm. Loạt hoạt động quảng bá."],
  ["target market", "thị trường mục tiêu", "/ˈtɑːrɡɪt ˈmɑːrkɪt/", "Nhóm khách hàng nhắm tới."],
  ["demographic", "nhóm nhân khẩu học", "/ˌdeməˈɡræfɪk/", "Phân nhóm theo tuổi, giới, thu nhập."],
  ["B2B", "doanh nghiệp với doanh nghiệp", "/ˌbiː tə ˈbiː/", "Bán cho công ty khác."],
  ["B2C", "doanh nghiệp với người dùng", "/ˌbiː tə ˈsiː/", "Bán trực tiếp cho khách lẻ."],
  ["ROI", "lợi tức đầu tư", "/ˌɑːr oʊ ˈaɪ/", "Return On Investment, lời/vốn bỏ ra."],
  ["KPI", "chỉ số hiệu suất chính", "/ˌkeɪ piː ˈaɪ/", "Key Performance Indicator."],
  ["stakeholder buy-in", "sự đồng thuận của bên liên quan", "/ˈsteɪkhoʊldər baɪ ɪn/", "Các bên ủng hộ quyết định."],
  ["due diligence", "thẩm định kỹ lưỡng", "/duː ˈdɪlɪdʒəns/", "Kiểm tra trước khi mua/đầu tư."],
  ["proposal", "đề xuất / bản chào", "/prəˈpoʊzl/", "Tài liệu đề nghị hợp tác."],
  ["bid", "bỏ thầu / chào giá", "/bɪd/", "Đề nghị giá để giành hợp đồng."],
  ["tender", "gói thầu", "/ˈtendər/", "Mời chào giá chính thức."],
  ["quotation", "báo giá", "/kwoʊˈteɪʃn/", "Giá đưa ra cho khách."],
  ["markup", "phần cộng giá", "/ˈmɑːrkʌp/", "Tăng thêm so với giá gốc."],
  ["discount", "chiết khấu / giảm giá", "/ˈdɪskaʊnt/", "Bớt giá cho khách."],
  ["refund", "hoàn tiền", "/ˈriːfʌnd/", "Trả lại tiền đã thu."],
  ["warranty", "bảo hành", "/ˈwɔːrənti/", "Cam kết sửa/đổi nếu hỏng."],
  ["liability insurance", "bảo hiểm trách nhiệm", "/ˌlaɪəˈbɪləti ɪnˈʃʊrəns/", "Bảo vệ khỏi rủi ro pháp lý."],
  ["headhunt", "săn nhân tài", "/ˈhedhʌnt/", "Tìm chiêu mộ người giỏi."],
  ["onboarding", "hội nhập nhân viên mới", "/ˈɑːnbɔːrdɪŋ/", "Quy trình tiếp nhận người mới."],
  ["restructure", "tái cơ cấu", "/ˌriːˈstrʌktʃər/", "Tổ chức lại công ty."],
  ["downsize", "cắt giảm quy mô", "/ˈdaʊnsaɪz/", "Giảm nhân sự/bộ phận."],
  ["expansion", "mở rộng", "/ɪkˈspænʃn/", "Phát triển thêm thị trường."],
  ["franchise", "nhượng quyền", "/ˈfræntʃaɪz/", "Cho phép dùng thương hiệu kinh doanh."],
  ["monopoly", "độc quyền", "/məˈnɑːpəli/", "Một bên kiểm soát toàn thị trường."],
  ["overdraft", "thấu chi", "/ˈoʊvərdræft/", "Rút quá số dư tài khoản."],
  ["solvent", "có khả năng trả nợ", "/ˈsɑːlvənt/", "Trái nghĩa 'bankrupt'."],
  ["venture capital", "vốn đầu tư mạo hiểm", "/ˈventʃər ˈkæpɪtl/", "Vốn rót vào startup rủi ro cao."],
  ["IPO", "phát hành cổ phiếu lần đầu", "/ˌaɪ piː ˈoʊ/", "Công ty lên sàn chứng khoán."],
  ["overvalued", "định giá quá cao", "/ˌoʊvərˈvæljuːd/", "Giá cao hơn giá trị thật."],
];

// ===== English_Advanced_Academic (en-US) — 100 academic words =====
const englishAdvancedAcademic: Card4[] = [
  ["analyze", "phân tích", "/ˈænəlaɪz/", "Anh-Anh 'analyse'. Xem xét chi tiết."],
  ["analysis", "sự phân tích", "/əˈnæləsɪs/", "Số nhiều 'analyses' /-siːz/."],
  ["hypothesis", "giả thuyết", "/haɪˈpɑːθəsɪs/", "Phỏng đoán cần kiểm chứng."],
  ["theory", "lý thuyết", "/ˈθiːəri/", "Hệ thống ý tưởng giải thích."],
  ["concept", "khái niệm", "/ˈkɑːnsept/", "Ý tưởng trừu tượng."],
  ["evidence", "bằng chứng", "/ˈevɪdəns/", "Không đếm được. Dữ liệu chứng minh."],
  ["data", "dữ liệu", "/ˈdeɪtə/", "Thông tin thu thập được."],
  ["research", "nghiên cứu", "/ˈriːsɜːrtʃ/", "Tìm hiểu có hệ thống."],
  ["method", "phương pháp", "/ˈmeθəd/", "Cách làm có hệ thống."],
  ["methodology", "phương pháp luận", "/ˌmeθəˈdɑːlədʒi/", "Hệ thống các phương pháp."],
  ["approach", "cách tiếp cận", "/əˈproʊtʃ/", "Hướng giải quyết vấn đề."],
  ["framework", "khung lý thuyết", "/ˈfreɪmwɜːrk/", "Cấu trúc nền cho phân tích."],
  ["criterion", "tiêu chí", "/kraɪˈtɪriən/", "Số nhiều 'criteria'."],
  ["variable", "biến số", "/ˈveriəbl/", "Yếu tố thay đổi được."],
  ["correlation", "mối tương quan", "/ˌkɔːrəˈleɪʃn/", "Liên hệ giữa hai biến."],
  ["significant", "có ý nghĩa / đáng kể", "/sɪɡˈnɪfɪkənt/", "'statistically significant' = có ý nghĩa thống kê."],
  ["empirical", "thực nghiệm", "/ɪmˈpɪrɪkl/", "Dựa trên quan sát, dữ liệu thật."],
  ["theoretical", "lý thuyết", "/ˌθiːəˈretɪkl/", "Trái nghĩa 'empirical/practical'."],
  ["abstract", "tóm tắt / trừu tượng", "/ˈæbstrækt/", "Phần tóm lược đầu bài báo."],
  ["thesis", "luận án / luận điểm", "/ˈθiːsɪs/", "Số nhiều 'theses'."],
  ["dissertation", "luận văn", "/ˌdɪsərˈteɪʃn/", "Bài nghiên cứu dài bậc cao học."],
  ["citation", "trích dẫn", "/saɪˈteɪʃn/", "Dẫn nguồn tài liệu."],
  ["reference", "tài liệu tham khảo", "/ˈrefrəns/", "Nguồn được dẫn."],
  ["bibliography", "thư mục", "/ˌbɪbliˈɑːɡrəfi/", "Danh sách tài liệu cuối bài."],
  ["plagiarism", "đạo văn", "/ˈpleɪdʒərɪzəm/", "Chép ý người khác không ghi nguồn."],
  ["paraphrase", "diễn giải lại", "/ˈpærəfreɪz/", "Viết lại ý bằng lời mình."],
  ["summarize", "tóm tắt", "/ˈsʌməraɪz/", "Anh-Anh 'summarise'."],
  ["interpret", "diễn giải / lý giải", "/ɪnˈtɜːrprət/", "Giải thích ý nghĩa."],
  ["evaluate", "đánh giá", "/ɪˈvæljueɪt/", "Xét giá trị, ưu nhược."],
  ["assess", "thẩm định", "/əˈses/", "Đánh giá mức độ/chất lượng."],
  ["critique", "phê bình / bài phê bình", "/krɪˈtiːk/", "Đánh giá có lập luận."],
  ["argue", "lập luận / tranh luận", "/ˈɑːrɡjuː/", "Đưa lý lẽ bảo vệ quan điểm."],
  ["argument", "luận điểm / lập luận", "/ˈɑːrɡjumənt/", "Chuỗi lý lẽ."],
  ["claim", "khẳng định / luận điểm", "/kleɪm/", "Điều cho là đúng cần chứng minh."],
  ["assumption", "giả định", "/əˈsʌmpʃn/", "Điều coi là đúng không chứng minh."],
  ["implication", "hàm ý / hệ quả", "/ˌɪmplɪˈkeɪʃn/", "Điều suy ra được."],
  ["conclusion", "kết luận", "/kənˈkluːʒn/", "Phần chốt lại kết quả."],
  ["objective", "mục tiêu / khách quan", "/əbˈdʒektɪv/", "Trái nghĩa 'subjective'."],
  ["subjective", "chủ quan", "/səbˈdʒektɪv/", "Dựa trên cảm nhận cá nhân."],
  ["bias", "thiên kiến", "/ˈbaɪəs/", "Nghiêng về một phía thiếu công bằng."],
  ["validity", "tính hợp lệ", "/vəˈlɪdəti/", "Mức độ đo đúng cái cần đo."],
  ["reliability", "độ tin cậy", "/rɪˌlaɪəˈbɪləti/", "Kết quả nhất quán khi lặp lại."],
  ["sample", "mẫu (nghiên cứu)", "/ˈsæmpl/", "Nhóm nhỏ đại diện."],
  ["survey", "khảo sát", "/ˈsɜːrveɪ/", "Thu dữ liệu bằng câu hỏi."],
  ["questionnaire", "bảng câu hỏi", "/ˌkwestʃəˈner/", "Bộ câu hỏi khảo sát."],
  ["experiment", "thí nghiệm", "/ɪkˈsperɪmənt/", "Kiểm chứng giả thuyết."],
  ["observation", "quan sát", "/ˌɑːbzərˈveɪʃn/", "Theo dõi ghi nhận."],
  ["phenomenon", "hiện tượng", "/fəˈnɑːmɪnən/", "Số nhiều 'phenomena'."],
  ["paradigm", "hệ hình / mô thức", "/ˈpærədaɪm/", "'g' câm. Khung tư duy chủ đạo."],
  ["discourse", "diễn ngôn", "/ˈdɪskɔːrs/", "Cách bàn luận về chủ đề."],
  ["rhetoric", "tu từ / hùng biện", "/ˈretərɪk/", "Nghệ thuật dùng ngôn từ thuyết phục."],
  ["coherent", "mạch lạc", "/koʊˈhɪrənt/", "Logic, gắn kết."],
  ["ambiguous", "mơ hồ / đa nghĩa", "/æmˈbɪɡjuəs/", "Hiểu được nhiều cách."],
  ["explicit", "rõ ràng / tường minh", "/ɪkˈsplɪsɪt/", "Nói thẳng. Trái nghĩa 'implicit'."],
  ["implicit", "ngầm / ẩn", "/ɪmˈplɪsɪt/", "Hiểu ngầm, không nói thẳng."],
  ["fundamental", "cơ bản / nền tảng", "/ˌfʌndəˈmentl/", "Mang tính gốc rễ."],
  ["comprehensive", "toàn diện", "/ˌkɑːmprɪˈhensɪv/", "Bao quát đầy đủ."],
  ["substantial", "đáng kể", "/səbˈstænʃl/", "Lớn, quan trọng."],
  ["adequate", "đầy đủ / thỏa đáng", "/ˈædɪkwət/", "Đủ mức cần thiết."],
  ["relevant", "liên quan / thích đáng", "/ˈreləvənt/", "Có liên hệ tới vấn đề."],
  ["consistent", "nhất quán", "/kənˈsɪstənt/", "Không mâu thuẫn."],
  ["contradict", "mâu thuẫn / phản bác", "/ˌkɑːntrəˈdɪkt/", "Nói ngược lại."],
  ["distinguish", "phân biệt", "/dɪˈstɪŋɡwɪʃ/", "Thấy khác biệt giữa các thứ."],
  ["distinct", "khác biệt rõ", "/dɪˈstɪŋkt/", "Riêng biệt, dễ nhận ra."],
  ["component", "thành phần", "/kəmˈpoʊnənt/", "Bộ phận cấu thành."],
  ["aspect", "khía cạnh", "/ˈæspekt/", "Một mặt của vấn đề."],
  ["factor", "yếu tố", "/ˈfæktər/", "Thứ góp phần gây kết quả."],
  ["context", "ngữ cảnh / bối cảnh", "/ˈkɑːntekst/", "Hoàn cảnh xung quanh."],
  ["scope", "phạm vi", "/skoʊp/", "Giới hạn của nghiên cứu."],
  ["constraint", "ràng buộc / hạn chế", "/kənˈstreɪnt/", "Giới hạn cản trở."],
  ["limitation", "hạn chế", "/ˌlɪmɪˈteɪʃn/", "Điểm yếu của nghiên cứu."],
  ["derive", "rút ra / có nguồn gốc từ", "/dɪˈraɪv/", "'derive from' = bắt nguồn từ."],
  ["demonstrate", "chứng minh / minh họa", "/ˈdemənstreɪt/", "Cho thấy rõ điều gì."],
  ["illustrate", "minh họa", "/ˈɪləstreɪt/", "Làm rõ bằng ví dụ."],
  ["emphasize", "nhấn mạnh", "/ˈemfəsaɪz/", "Anh-Anh 'emphasise'."],
  ["highlight", "làm nổi bật", "/ˈhaɪlaɪt/", "Chỉ ra điểm quan trọng."],
  ["indicate", "cho thấy / chỉ ra", "/ˈɪndɪkeɪt/", "Là dấu hiệu của."],
  ["imply", "ngụ ý", "/ɪmˈplaɪ/", "Gợi ý không nói thẳng."],
  ["infer", "suy luận", "/ɪnˈfɜːr/", "Rút kết luận từ bằng chứng."],
  ["justify", "biện minh / chứng minh là hợp lý", "/ˈdʒʌstɪfaɪ/", "Đưa lý do bảo vệ."],
  ["validate", "xác nhận tính đúng đắn", "/ˈvælɪdeɪt/", "Chứng tỏ là hợp lệ."],
  ["refute", "bác bỏ", "/rɪˈfjuːt/", "Chứng minh là sai."],
  ["synthesize", "tổng hợp", "/ˈsɪnθəsaɪz/", "Kết hợp nhiều nguồn thành cái mới."],
  ["integrate", "tích hợp", "/ˈɪntɪɡreɪt/", "Gộp các phần thành thể thống nhất."],
  ["differentiate", "phân hóa / phân biệt", "/ˌdɪfəˈrenʃieɪt/", "Tạo/thấy sự khác biệt."],
  ["generalize", "khái quát hóa", "/ˈdʒenrəlaɪz/", "Rút ra điều chung từ ví dụ."],
  ["quantitative", "định lượng", "/ˈkwɑːntəteɪtɪv/", "Dựa trên số liệu."],
  ["qualitative", "định tính", "/ˈkwɑːlɪteɪtɪv/", "Dựa trên mô tả, đặc điểm."],
  ["statistics", "thống kê", "/stəˈtɪstɪks/", "Phân tích số liệu."],
  ["percentage", "tỷ lệ phần trăm", "/pərˈsentɪdʒ/", "Phần trên 100."],
  ["proportion", "tỷ lệ", "/prəˈpɔːrʃn/", "Phần so với tổng."],
  ["dimension", "chiều / khía cạnh", "/dɪˈmenʃn/", "Mặt cần xét."],
  ["spectrum", "quang phổ / dải", "/ˈspektrəm/", "Dải liên tục các mức."],
  ["domain", "lĩnh vực / miền", "/doʊˈmeɪn/", "Phạm vi kiến thức."],
  ["discipline", "ngành học / kỷ luật", "/ˈdɪsəplɪn/", "Lĩnh vực nghiên cứu."],
  ["scholar", "học giả", "/ˈskɑːlər/", "Người nghiên cứu chuyên sâu."],
  ["peer review", "phản biện đồng nghiệp", "/pɪr rɪˈvjuː/", "Chuyên gia thẩm định bài báo."],
  ["publication", "ấn phẩm / bài công bố", "/ˌpʌblɪˈkeɪʃn/", "Bài đăng tạp chí khoa học."],
  ["academic", "thuộc học thuật", "/ˌækəˈdemɪk/", "Liên quan nghiên cứu, đại học."],
];

// ===== English_Advanced_Idioms (en-US) — 100 idioms & phrasal verbs =====
const englishAdvancedIdioms: Card4[] = [
  ["break the ice", "phá vỡ sự ngại ngùng", "/breɪk ðə aɪs/", "Làm không khí bớt gượng khi mới gặp."],
  ["piece of cake", "dễ như ăn bánh", "/piːs əv keɪk/", "Việc rất dễ làm."],
  ["hit the books", "vùi đầu vào học", "/hɪt ðə bʊks/", "Học hành chăm chỉ."],
  ["under the weather", "thấy không khỏe", "/ˈʌndər ðə ˈweðər/", "Hơi ốm, mệt."],
  ["once in a blue moon", "hiếm khi", "/wʌns ɪn ə bluː muːn/", "Rất thỉnh thoảng mới xảy ra."],
  ["cost an arm and a leg", "đắt cắt cổ", "/kɔːst ən ɑːrm ən ə leɡ/", "Rất tốn tiền."],
  ["the ball is in your court", "đến lượt bạn quyết định", "/ðə bɔːl ɪz ɪn jɔːr kɔːrt/", "Trách nhiệm hành động thuộc về bạn."],
  ["bite the bullet", "cắn răng chịu đựng", "/baɪt ðə ˈbʊlɪt/", "Làm việc khó/khó chịu mà phải làm."],
  ["hit the nail on the head", "nói trúng phóc", "/hɪt ðə neɪl ɑːn ðə hed/", "Nói/làm chính xác điều đúng."],
  ["let the cat out of the bag", "để lộ bí mật", "/let ðə kæt aʊt əv ðə bæɡ/", "Vô tình tiết lộ điều giấu kín."],
  ["a blessing in disguise", "trong cái rủi có cái may", "/ə ˈblesɪŋ ɪn dɪsˈɡaɪz/", "Điều xấu hóa ra lại tốt."],
  ["beat around the bush", "nói vòng vo", "/biːt əˈraʊnd ðə bʊʃ/", "Không vào thẳng vấn đề."],
  ["call it a day", "tạm nghỉ / kết thúc", "/kɔːl ɪt ə deɪ/", "Dừng công việc hôm nay."],
  ["cut corners", "làm ẩu cho nhanh", "/kʌt ˈkɔːrnərz/", "Bỏ bước để tiết kiệm thời gian/tiền."],
  ["get out of hand", "vượt tầm kiểm soát", "/ɡet aʊt əv hænd/", "Trở nên không kiểm soát được."],
  ["go the extra mile", "nỗ lực hơn mức yêu cầu", "/ɡoʊ ðə ˈekstrə maɪl/", "Cố gắng thêm để làm tốt hơn."],
  ["pull someone's leg", "trêu chọc ai", "/pʊl ˈsʌmwʌnz leɡ/", "Đùa, nói giỡn để chọc."],
  ["speak of the devil", "vừa nhắc đã thấy", "/spiːk əv ðə ˈdevl/", "Người vừa nhắc tới thì xuất hiện."],
  ["the last straw", "giọt nước tràn ly", "/ðə læst strɔː/", "Điều cuối làm hết chịu nổi."],
  ["under the radar", "lặng lẽ không bị chú ý", "/ˈʌndər ðə ˈreɪdɑːr/", "Tránh sự để ý."],
  ["on the same page", "cùng quan điểm", "/ɑːn ðə seɪm peɪdʒ/", "Hiểu và đồng ý như nhau."],
  ["read between the lines", "hiểu ẩn ý", "/riːd bɪˈtwiːn ðə laɪnz/", "Hiểu điều không nói thẳng."],
  ["jump on the bandwagon", "chạy theo trào lưu", "/dʒʌmp ɑːn ðə ˈbændwæɡən/", "Theo cái đang thịnh hành."],
  ["throw in the towel", "bỏ cuộc", "/θroʊ ɪn ðə ˈtaʊəl/", "Đầu hàng, từ bỏ."],
  ["burn the midnight oil", "thức khuya làm việc", "/bɜːrn ðə ˈmɪdnaɪt ɔɪl/", "Làm/học tới khuya."],
  ["the tip of the iceberg", "phần nổi của tảng băng", "/ðə tɪp əv ði ˈaɪsbɜːrɡ/", "Phần nhỏ của vấn đề lớn ẩn giấu."],
  ["a dime a dozen", "nhiều vô kể / tầm thường", "/ə daɪm ə ˈdʌzn/", "Rất phổ biến, không quý."],
  ["barking up the wrong tree", "đổ lỗi/tìm sai chỗ", "/ˈbɑːrkɪŋ ʌp ðə rɔːŋ triː/", "Hướng nỗ lực vào sai đối tượng."],
  ["a piece of one's mind", "nói thẳng sự bực", "/ə piːs əv wʌnz maɪnd/", "Mắng thẳng vì tức giận."],
  ["off the top of my head", "nghĩ ngay không tra cứu", "/ɔːf ðə tɑːp əv maɪ hed/", "Trả lời ngay theo trí nhớ."],
  ["in hot water", "gặp rắc rối", "/ɪn hɑːt ˈwɔːtər/", "Đang bị phiền phức/khiển trách."],
  ["miss the boat", "lỡ cơ hội", "/mɪs ðə boʊt/", "Bỏ lỡ dịp tốt."],
  ["sit on the fence", "lưỡng lự không chọn phe", "/sɪt ɑːn ðə fens/", "Chưa quyết định bên nào."],
  ["a storm in a teacup", "chuyện bé xé ra to", "/ə stɔːrm ɪn ə ˈtiːkʌp/", "Làm to chuyện nhỏ nhặt."],
  ["the best of both worlds", "lợi cả đôi đường", "/ðə best əv boʊθ wɜːrldz/", "Được cả hai điều tốt cùng lúc."],
  ["add fuel to the fire", "đổ thêm dầu vào lửa", "/æd ˈfjuːəl tə ðə ˈfaɪər/", "Làm tình hình tệ hơn."],
  ["back to square one", "trở lại vạch xuất phát", "/bæk tə skwer wʌn/", "Phải bắt đầu lại từ đầu."],
  ["bend over backwards", "cố hết sức giúp", "/bend ˈoʊvər ˈbækwərdz/", "Nỗ lực tối đa vì ai đó."],
  ["cry over spilt milk", "tiếc nuối chuyện đã rồi", "/kraɪ ˈoʊvər spɪlt mɪlk/", "Buồn về điều không thể thay đổi."],
  ["face the music", "đối mặt hậu quả", "/feɪs ðə ˈmjuːzɪk/", "Chấp nhận hệ quả việc mình làm."],
  ["get cold feet", "chùn bước / mất can đảm", "/ɡet koʊld fiːt/", "Sợ hãi trước việc lớn."],
  ["give the benefit of the doubt", "cho cơ hội tin tưởng", "/ɡɪv ðə ˈbenɪfɪt əv ðə daʊt/", "Tin ai dù chưa chắc."],
  ["hit the sack", "đi ngủ", "/hɪt ðə sæk/", "Lên giường ngủ."],
  ["kill two birds with one stone", "một công đôi việc", "/kɪl tuː bɜːrdz wɪð wʌn stoʊn/", "Giải quyết hai việc cùng lúc."],
  ["the elephant in the room", "vấn đề ai cũng tránh nói", "/ði ˈelɪfənt ɪn ðə ruːm/", "Chuyện hiển nhiên mà mọi người lờ đi."],
  ["wrap your head around", "hiểu được điều khó", "/ræp jɔːr hed əˈraʊnd/", "Cố nắm bắt khái niệm khó."],
  ["pull yourself together", "trấn tĩnh lại", "/pʊl jɔːrˈself təˈɡeðər/", "Bình tĩnh, kiểm soát cảm xúc."],
  ["go down the rabbit hole", "sa đà vào chi tiết", "/ɡoʊ daʊn ðə ˈræbɪt hoʊl/", "Lún sâu vào việc phức tạp."],
  ["touch base", "liên lạc trao đổi nhanh", "/tʌtʃ beɪs/", "Cập nhật tình hình ngắn gọn."],
  ["raining cats and dogs", "mưa như trút nước", "/ˈreɪnɪŋ kæts ən dɔːɡz/", "Mưa rất to."],
  ["bring up", "nuôi dạy / nêu ra", "/brɪŋ ʌp/", "Cụm động từ: dạy con hoặc đề cập."],
  ["call off", "hủy bỏ", "/kɔːl ɔːf/", "'call off the meeting' = hủy họp."],
  ["carry out", "thực hiện", "/ˈkæri aʊt/", "Tiến hành kế hoạch."],
  ["come across", "tình cờ gặp / tạo ấn tượng", "/kʌm əˈkrɔːs/", "Bắt gặp hoặc gây cảm nhận."],
  ["figure out", "tìm ra / hiểu ra", "/ˈfɪɡjər aʊt/", "Giải được, hiểu được."],
  ["get along", "hòa thuận", "/ɡet əˈlɔːŋ/", "'get along with' = hợp với ai."],
  ["give up", "từ bỏ", "/ɡɪv ʌp/", "Ngừng cố gắng."],
  ["look forward to", "mong chờ", "/lʊk ˈfɔːrwərd tə/", "Theo sau là V-ing."],
  ["look up to", "ngưỡng mộ", "/lʊk ʌp tə/", "Kính trọng ai đó."],
  ["put off", "trì hoãn", "/pʊt ɔːf/", "Hoãn lại. Cũng nghĩa 'làm ai mất hứng'."],
  ["run out of", "hết / cạn", "/rʌn aʊt əv/", "'run out of money' = hết tiền."],
  ["take after", "giống (người thân)", "/teɪk ˈæftər/", "Giống bố mẹ về ngoại hình/tính."],
  ["turn down", "từ chối / vặn nhỏ", "/tɜːrn daʊn/", "Khước từ hoặc giảm âm lượng."],
  ["work out", "tập thể dục / giải quyết", "/wɜːrk aʊt/", "Tập gym hoặc tìm ra cách."],
  ["back up", "sao lưu / ủng hộ", "/bæk ʌp/", "Lưu dự phòng hoặc hỗ trợ."],
  ["break down", "hỏng / suy sụp", "/breɪk daʊn/", "Máy hỏng hoặc gục ngã tinh thần."],
  ["bump into", "tình cờ gặp", "/bʌmp ˈɪntə/", "Gặp ai bất ngờ."],
  ["count on", "trông cậy vào", "/kaʊnt ɑːn/", "Tin tưởng dựa vào ai."],
  ["drop by", "ghé qua", "/drɑːp baɪ/", "Ghé thăm ngắn."],
  ["end up", "rốt cuộc / kết thúc ở", "/end ʌp/", "'end up doing' = cuối cùng lại làm."],
  ["fill in", "điền vào / thay thế", "/fɪl ɪn/", "Điền form hoặc làm thay ai."],
  ["get over", "vượt qua / hồi phục", "/ɡet ˈoʊvər/", "Quên nỗi buồn, khỏi bệnh."],
  ["hold on", "chờ chút / bám chặt", "/hoʊld ɑːn/", "'hold on' = đợi đã."],
  ["keep up with", "theo kịp", "/kiːp ʌp wɪð/", "Không bị tụt lại."],
  ["make up", "bịa ra / làm hòa / trang điểm", "/meɪk ʌp/", "Nhiều nghĩa tùy ngữ cảnh."],
  ["pass away", "qua đời", "/pæs əˈweɪ/", "Cách nói lịch sự của 'die'."],
  ["pick up", "đón / nhặt lên / học lóm", "/pɪk ʌp/", "'pick up at the airport' = đón sân bay."],
  ["point out", "chỉ ra", "/pɔɪnt aʊt/", "Nêu rõ điều gì."],
  ["set up", "thiết lập / dựng", "/set ʌp/", "Cài đặt hoặc tổ chức."],
  ["show up", "xuất hiện / đến", "/ʃoʊ ʌp/", "Có mặt."],
  ["sort out", "giải quyết / sắp xếp", "/sɔːrt aʊt/", "Xử lý cho ổn thỏa."],
  ["take over", "tiếp quản", "/teɪk ˈoʊvər/", "Nắm quyền điều hành."],
  ["throw away", "vứt đi", "/θroʊ əˈweɪ/", "Bỏ rác."],
  ["turn up", "xuất hiện / vặn to", "/tɜːrn ʌp/", "Đến nơi hoặc tăng âm lượng."],
  ["watch out", "coi chừng", "/wɑːtʃ aʊt/", "Cảnh báo nguy hiểm."],
  ["a far cry from", "khác xa", "/ə fɑːr kraɪ frəm/", "Rất khác so với."],
  ["at the drop of a hat", "ngay lập tức", "/ət ðə drɑːp əv ə hæt/", "Không do dự, tức thì."],
  ["by the book", "đúng quy tắc", "/baɪ ðə bʊk/", "Làm theo luật chặt chẽ."],
  ["caught off guard", "bị bất ngờ", "/kɔːt ɔːf ɡɑːrd/", "Không kịp chuẩn bị."],
  ["devil's advocate", "người phản biện cho vui", "/ˈdevlz ˈædvəkət/", "Cố tình bác để tranh luận."],
  ["down to earth", "giản dị thực tế", "/daʊn tə ɜːrθ/", "Không kiêu, gần gũi."],
  ["get the hang of", "quen tay / thạo", "/ɡet ðə hæŋ əv/", "Bắt đầu làm thành thạo."],
  ["in the long run", "về lâu dài", "/ɪn ðə lɔːŋ rʌn/", "Xét trong tương lai xa."],
  ["jump to conclusions", "vội kết luận", "/dʒʌmp tə kənˈkluːʒnz/", "Kết luận khi chưa đủ thông tin."],
  ["keep an eye on", "để mắt trông chừng", "/kiːp ən aɪ ɑːn/", "Theo dõi, canh chừng."],
  ["on the ball", "nhanh nhạy / giỏi", "/ɑːn ðə bɔːl/", "Phản ứng tốt, am hiểu."],
  ["out of the blue", "bất thình lình", "/aʊt əv ðə bluː/", "Xảy ra hoàn toàn bất ngờ."],
  ["pull strings", "dùng quan hệ", "/pʊl strɪŋz/", "Nhờ mối quan hệ để đạt việc."],
  ["take it with a grain of salt", "đừng tin hoàn toàn", "/teɪk ɪt wɪð ə ɡreɪn əv sɔːlt/", "Nghe nhưng giữ hoài nghi."],
  ["the bottom line", "điểm mấu chốt", "/ðə ˈbɑːtəm laɪn/", "Kết luận quan trọng nhất."],
  ["wear many hats", "kiêm nhiều vai trò", "/wer ˈmeni hæts/", "Làm nhiều việc khác nhau."],
];

// ===== French_Basic_Life (fr-FR) — 100 everyday-life words =====
const frenchBasicLife: Card4[] = [
  ["le temps", "thời gian / thời tiết", "/lə tɑ̃/", "Hai nghĩa: thời gian và thời tiết."],
  ["le jour", "ngày", "/lə ʒuʁ/", "'aujourd'hui' = hôm nay."],
  ["la nuit", "đêm", "/la nɥi/", "'bonne nuit' = chúc ngủ ngon."],
  ["le matin", "buổi sáng", "/lə matɛ̃/", "'le matin' = vào buổi sáng."],
  ["la semaine", "tuần", "/la səmɛn/", "7 ngày."],
  ["le mois", "tháng", "/lə mwa/", "'s' câm cuối."],
  ["l'année", "năm", "/lane/", "Giống cái: 'une année'."],
  ["l'heure", "giờ", "/lœʁ/", "'h' câm. 'Quelle heure est-il?' = mấy giờ?"],
  ["la minute", "phút", "/la minyt/", "60 giây."],
  ["l'eau", "nước", "/lo/", "Giống cái. 'un verre d'eau' = ly nước."],
  ["la nourriture", "thức ăn", "/la nuʁityʁ/", "Đồ ăn nói chung."],
  ["l'argent", "tiền / bạc", "/laʁʒɑ̃/", "Giống đực. Cũng nghĩa kim loại bạc."],
  ["la maison", "ngôi nhà", "/la mɛzɔ̃/", "'à la maison' = ở nhà."],
  ["la famille", "gia đình", "/la famij/", "'ll' đọc như 'y'."],
  ["l'ami", "bạn (nam)", "/lami/", "Bạn nữ: 'l'amie' (đọc giống)."],
  ["le travail", "công việc", "/lə tʁavaj/", "'ail' đọc /aj/."],
  ["l'école", "trường học", "/lekɔl/", "Giống cái: 'une école'."],
  ["la voiture", "xe hơi", "/la vwatyʁ/", "'conduire une voiture' = lái xe."],
  ["la route", "con đường", "/la ʁut/", "Đường lớn cho xe."],
  ["la ville", "thành phố", "/la vil/", "Khác 'village' (làng)."],
  ["le pays", "đất nước", "/lə pei/", "'s' câm. Quốc gia."],
  ["les gens", "mọi người", "/le ʒɑ̃/", "Luôn số nhiều."],
  ["la personne", "người (một người)", "/la pɛʁsɔn/", "Số ít, giống cái."],
  ["l'homme", "đàn ông", "/lɔm/", "'h' câm. Cũng nghĩa 'con người'."],
  ["la femme", "phụ nữ / vợ", "/la fam/", "Đọc 'fam', không 'fem'."],
  ["l'enfant", "đứa trẻ", "/lɑ̃fɑ̃/", "Dùng cho cả nam và nữ."],
  ["le nom", "tên / họ", "/lə nɔ̃/", "'Quel est ton nom?' = bạn tên gì?"],
  ["l'amour", "tình yêu", "/lamuʁ/", "Giống đực. 'je t'aime' = anh yêu em."],
  ["la vie", "cuộc sống", "/la vi/", "'c'est la vie' = đời là thế."],
  ["le monde", "thế giới / mọi người", "/lə mɔ̃d/", "'tout le monde' = mọi người."],
  ["l'endroit", "nơi chốn", "/lɑ̃dʁwa/", "Một địa điểm."],
  ["la chose", "vật / điều", "/la ʃoz/", "Từ chung cho đồ vật/sự việc."],
  ["le mot", "từ / lời", "/lə mo/", "'t' câm."],
  ["le livre", "quyển sách", "/lə livʁ/", "'lire un livre' = đọc sách."],
  ["le téléphone", "điện thoại", "/lə telefɔn/", "'téléphoner' = gọi điện."],
  ["la porte", "cửa", "/la pɔʁt/", "'ouvrir la porte' = mở cửa."],
  ["la fenêtre", "cửa sổ", "/la fənɛtʁ/", "Có dấu mũ trên ê."],
  ["la table", "cái bàn", "/la tabl/", "'sur la table' = trên bàn."],
  ["la chaise", "cái ghế", "/la ʃɛz/", "Ghế có lưng tựa."],
  ["le lit", "cái giường", "/lə li/", "'t' câm. 'aller au lit' = đi ngủ."],
  ["la chambre", "phòng (ngủ)", "/la ʃɑ̃bʁ/", "Thường là phòng ngủ."],
  ["la rue", "đường phố", "/la ʁy/", "Đường trong phố có nhà."],
  ["le sac", "túi / cặp", "/lə sak/", "'sac à dos' = ba lô."],
  ["les vêtements", "quần áo", "/le vɛtmɑ̃/", "Thường số nhiều."],
  ["la chaussure", "chiếc giày", "/la ʃosyʁ/", "Thường số nhiều 'chaussures'."],
  ["la main", "bàn tay", "/la mɛ̃/", "'n' mũi. 'serrer la main' = bắt tay."],
  ["l'œil", "con mắt", "/lœj/", "Số nhiều bất quy tắc 'les yeux'."],
  ["la tête", "cái đầu", "/la tɛt/", "'mal à la tête' = đau đầu."],
  ["le cœur", "trái tim", "/lə kœʁ/", "'par cœur' = thuộc lòng."],
  ["la couleur", "màu sắc", "/la kulœʁ/", "'couleur préférée' = màu yêu thích."],
  ["la lumière", "ánh sáng", "/la lymjɛʁ/", "Nguồn sáng."],
  ["l'air", "không khí / vẻ", "/lɛʁ/", "Giống đực. Cũng nghĩa 'dáng vẻ'."],
  ["le feu", "lửa", "/lə fø/", "Cũng nghĩa 'đèn giao thông'."],
  ["le soleil", "mặt trời", "/lə sɔlɛj/", "'il fait soleil' = trời nắng."],
  ["la lune", "mặt trăng", "/la lyn/", "'pleine lune' = trăng tròn."],
  ["l'étoile", "ngôi sao", "/letwal/", "Giống cái."],
  ["la pluie", "mưa", "/la plɥi/", "'il pleut' = trời mưa."],
  ["le vent", "gió", "/lə vɑ̃/", "'il y a du vent' = có gió."],
  ["l'arbre", "cái cây", "/laʁbʁ/", "Giống đực."],
  ["la fleur", "bông hoa", "/la flœʁ/", "'un bouquet de fleurs' = bó hoa."],
  ["l'animal", "động vật", "/lanimal/", "Số nhiều 'animaux'."],
  ["le chien", "con chó", "/lə ʃjɛ̃/", "Chó cái: 'la chienne'."],
  ["le chat", "con mèo", "/lə ʃa/", "'t' câm. Mèo cái: 'la chatte'."],
  ["l'oiseau", "con chim", "/lwazo/", "Số nhiều 'oiseaux'."],
  ["le poisson", "con cá", "/lə pwasɔ̃/", "Cũng là món cá."],
  ["aller", "đi", "/ale/", "Động từ bất quy tắc. 'je vais' = tôi đi."],
  ["venir", "đến", "/vəniʁ/", "'je viens' = tôi đến."],
  ["manger", "ăn", "/mɑ̃ʒe/", "'je mange' = tôi ăn."],
  ["boire", "uống", "/bwaʁ/", "'je bois' = tôi uống."],
  ["dormir", "ngủ", "/dɔʁmiʁ/", "'je dors' = tôi ngủ."],
  ["voir", "nhìn thấy", "/vwaʁ/", "'je vois' = tôi thấy."],
  ["entendre", "nghe thấy", "/ɑ̃tɑ̃dʁ/", "Khác 'écouter' (lắng nghe)."],
  ["parler", "nói", "/paʁle/", "'parler français' = nói tiếng Pháp."],
  ["lire", "đọc", "/liʁ/", "'je lis' = tôi đọc."],
  ["écrire", "viết", "/ekʁiʁ/", "'j'écris' = tôi viết."],
  ["marcher", "đi bộ / hoạt động", "/maʁʃe/", "Cũng nghĩa 'chạy được' (máy móc)."],
  ["courir", "chạy", "/kuʁiʁ/", "'je cours' = tôi chạy."],
  ["acheter", "mua", "/aʃte/", "Trái nghĩa 'vendre'."],
  ["vendre", "bán", "/vɑ̃dʁ/", "'je vends' = tôi bán."],
  ["ouvrir", "mở", "/uvʁiʁ/", "Trái nghĩa 'fermer'."],
  ["fermer", "đóng", "/fɛʁme/", "'fermer la porte' = đóng cửa."],
  ["commencer", "bắt đầu", "/kɔmɑ̃se/", "Trái nghĩa 'finir'."],
  ["finir", "kết thúc", "/finiʁ/", "'je finis' = tôi xong."],
  ["aider", "giúp đỡ", "/ede/", "'aide-moi' = giúp tôi."],
  ["vouloir", "muốn", "/vulwaʁ/", "'je veux' = tôi muốn."],
  ["pouvoir", "có thể", "/puvwaʁ/", "'je peux' = tôi có thể."],
  ["aimer", "thích / yêu", "/eme/", "'j'aime' = tôi thích."],
  ["savoir", "biết (kiến thức)", "/savwaʁ/", "Khác 'connaître' (quen biết)."],
  ["penser", "nghĩ", "/pɑ̃se/", "'je pense' = tôi nghĩ."],
  ["dire", "nói (điều gì)", "/diʁ/", "'je dis' = tôi nói."],
  ["bon", "tốt / ngon", "/bɔ̃/", "Giống cái 'bonne'."],
  ["mauvais", "xấu / tệ", "/movɛ/", "'s' câm. Giống cái 'mauvaise'."],
  ["grand", "to / cao", "/ɡʁɑ̃/", "'d' câm. Giống cái 'grande'."],
  ["petit", "nhỏ / bé", "/pəti/", "'t' câm. Giống cái 'petite'."],
  ["nouveau", "mới", "/nuvo/", "Giống cái 'nouvelle'."],
  ["vieux", "cũ / già", "/vjø/", "Giống cái 'vieille'."],
  ["chaud", "nóng", "/ʃo/", "'il fait chaud' = trời nóng."],
  ["froid", "lạnh", "/fʁwa/", "'il fait froid' = trời lạnh."],
  ["heureux", "hạnh phúc", "/œʁø/", "Giống cái 'heureuse'."],
  ["facile", "dễ", "/fasil/", "Trái nghĩa 'difficile'."],
];

// ===== French_Basic_Food (fr-FR) — 100 food & eating words =====
const frenchBasicFood: Card4[] = [
  ["le pain", "bánh mì", "/lə pɛ̃/", "'n' mũi. Thực phẩm chính ở Pháp."],
  ["le riz", "cơm / gạo", "/lə ʁi/", "'z' câm."],
  ["la viande", "thịt", "/la vjɑ̃d/", "Thịt nói chung."],
  ["le poulet", "thịt gà", "/lə pulɛ/", "'t' câm."],
  ["le bœuf", "thịt bò", "/lə bœf/", "Cũng nghĩa con bò."],
  ["le porc", "thịt heo", "/lə pɔʁ/", "'c' câm."],
  ["le poisson", "cá", "/lə pwasɔ̃/", "Vừa con cá vừa món cá."],
  ["l'œuf", "trứng", "/lœf/", "Số nhiều 'les œufs' /le zø/ (f câm)."],
  ["le lait", "sữa", "/lə lɛ/", "'t' câm."],
  ["le fromage", "phô mai", "/lə fʁɔmaʒ/", "Pháp nổi tiếng phô mai."],
  ["le beurre", "bơ", "/lə bœʁ/", "Phết lên bánh mì."],
  ["le sucre", "đường", "/lə sykʁ/", "Vị ngọt."],
  ["le sel", "muối", "/lə sɛl/", "Vị mặn."],
  ["le poivre", "tiêu", "/lə pwavʁ/", "Gia vị cay nhẹ."],
  ["l'huile", "dầu ăn", "/lɥil/", "'h' câm, giống cái."],
  ["la soupe", "súp", "/la sup/", "Món lỏng nóng."],
  ["le fruit", "trái cây", "/lə fʁɥi/", "'t' câm."],
  ["la pomme", "táo", "/la pɔm/", "'pomme de terre' = khoai tây."],
  ["la banane", "chuối", "/la banan/", "Quả dài màu vàng."],
  ["l'orange", "cam", "/lɔʁɑ̃ʒ/", "Vừa quả vừa màu cam."],
  ["le raisin", "nho", "/lə ʁɛzɛ̃/", "'n' mũi cuối."],
  ["le citron", "chanh", "/lə sitʁɔ̃/", "Vị chua."],
  ["la fraise", "dâu tây", "/la fʁɛz/", "Quả đỏ nhỏ."],
  ["la mangue", "xoài", "/la mɑ̃ɡ/", "Quả nhiệt đới ngọt."],
  ["l'ananas", "dứa / thơm", "/lananas/", "'s' cuối có thể đọc."],
  ["la pastèque", "dưa hấu", "/la pastɛk/", "Quả to ruột đỏ."],
  ["le légume", "rau củ", "/lə leɡym/", "Giống đực."],
  ["la tomate", "cà chua", "/la tɔmat/", "Đỏ, dùng nấu ăn."],
  ["la pomme de terre", "khoai tây", "/la pɔm də tɛʁ/", "Nghĩa đen 'táo của đất'."],
  ["la carotte", "cà rốt", "/la kaʁɔt/", "Củ cam dài."],
  ["l'oignon", "hành tây", "/lɔɲɔ̃/", "'gn' đọc /ɲ/."],
  ["l'ail", "tỏi", "/laj/", "Giống đực. 'ail' đọc /aj/."],
  ["la salade", "rau xà lách / sa lát", "/la salad/", "Món rau trộn."],
  ["le champignon", "nấm", "/lə ʃɑ̃piɲɔ̃/", "'gn' đọc /ɲ/."],
  ["le repas", "bữa ăn", "/lə ʁəpa/", "'s' câm."],
  ["le petit-déjeuner", "bữa sáng", "/lə pəti deʒœne/", "Nghĩa đen 'bữa nhỏ phá chay'."],
  ["le déjeuner", "bữa trưa", "/lə deʒœne/", "Bữa giữa ngày."],
  ["le dîner", "bữa tối", "/lə dine/", "Có dấu mũ trên î."],
  ["le dessert", "món tráng miệng", "/lə desɛʁ/", "'t' câm."],
  ["le gâteau", "bánh ngọt", "/lə ɡato/", "Số nhiều 'gâteaux'."],
  ["le chocolat", "sô cô la", "/lə ʃɔkɔla/", "'t' câm."],
  ["la glace", "kem / đá / gương", "/la ɡlas/", "Nhiều nghĩa tùy ngữ cảnh."],
  ["le café", "cà phê", "/lə kafe/", "Cũng nghĩa 'quán cà phê'."],
  ["le thé", "trà", "/lə te/", "Đồ uống nóng."],
  ["le jus", "nước ép", "/lə ʒy/", "'jus d'orange' = nước cam."],
  ["le vin", "rượu vang", "/lə vɛ̃/", "'n' mũi. Pháp nổi tiếng vang."],
  ["la bière", "bia", "/la bjɛʁ/", "Đồ uống có cồn."],
  ["l'assiette", "cái đĩa", "/lasjɛt/", "Giống cái."],
  ["le bol", "cái tô / bát", "/lə bɔl/", "Đựng súp, ngũ cốc."],
  ["la tasse", "cái tách", "/la tas/", "'une tasse de café' = tách cà phê."],
  ["le verre", "cái ly / thủy tinh", "/lə vɛʁ/", "'un verre d'eau' = ly nước."],
  ["la cuillère", "cái thìa", "/la kɥijɛʁ/", "Cũng viết 'cuiller'."],
  ["la fourchette", "cái nĩa", "/la fuʁʃɛt/", "Xiên thức ăn."],
  ["le couteau", "con dao", "/lə kuto/", "Số nhiều 'couteaux'."],
  ["cuisiner", "nấu ăn", "/kɥizine/", "'la cuisine' = nhà bếp/ẩm thực."],
  ["la recette", "công thức nấu ăn", "/la ʁəsɛt/", "Hướng dẫn nấu món."],
  ["le goût", "vị / mùi vị", "/lə ɡu/", "'t' câm. Cảm nhận khi nếm."],
  ["sucré", "ngọt", "/sykʁe/", "Vị của đường."],
  ["salé", "mặn", "/sale/", "Vị của muối."],
  ["acide", "chua", "/asid/", "Vị của chanh."],
  ["amer", "đắng", "/amɛʁ/", "Vị của cà phê đen."],
  ["épicé", "cay", "/epise/", "Có dấu sắc trên é."],
  ["frais", "tươi / mát", "/fʁɛ/", "Giống cái 'fraîche'."],
  ["délicieux", "ngon tuyệt", "/delisjø/", "Giống cái 'délicieuse'."],
  ["avoir faim", "đói (có cái đói)", "/avwaʁ fɛ̃/", "'j'ai faim' = tôi đói."],
  ["avoir soif", "khát", "/avwaʁ swaf/", "'j'ai soif' = tôi khát."],
  ["le restaurant", "nhà hàng", "/lə ʁɛstoʁɑ̃/", "Nơi ăn uống."],
  ["la cuisine", "nhà bếp / ẩm thực", "/la kɥizin/", "Vừa phòng bếp vừa nghệ thuật nấu."],
  ["le menu", "thực đơn", "/lə məny/", "Danh sách món."],
  ["la farine", "bột mì", "/la faʁin/", "Làm bánh mì, bánh ngọt."],
  ["le miel", "mật ong", "/lə mjɛl/", "Ngọt tự nhiên từ ong."],
  ["la confiture", "mứt", "/la kɔ̃fityʁ/", "Phết lên bánh mì."],
  ["la sauce", "nước sốt", "/la sos/", "Nêm cho món ăn."],
  ["le vinaigre", "giấm", "/lə vinɛɡʁ/", "Chua, dùng trộn salad."],
  ["la moutarde", "mù tạt", "/la mutaʁd/", "Gia vị cay vàng."],
  ["la baguette", "bánh mì baguette", "/la baɡɛt/", "Bánh mì dài đặc trưng Pháp."],
  ["le croissant", "bánh sừng bò", "/lə kʁwasɑ̃/", "Bánh bơ hình trăng lưỡi liềm."],
  ["le jambon", "giăm bông", "/lə ʒɑ̃bɔ̃/", "Thịt heo muối."],
  ["la saucisse", "xúc xích", "/la sosis/", "Thịt nhồi."],
  ["les frites", "khoai tây chiên", "/le fʁit/", "Luôn số nhiều."],
  ["l'omelette", "trứng ốp lết", "/lɔmlɛt/", "Trứng đánh chiên."],
  ["le yaourt", "sữa chua", "/lə jauʁt/", "Lên men từ sữa."],
  ["la crème", "kem tươi", "/la kʁɛm/", "'crème fraîche' = kem chua."],
  ["la crevette", "tôm", "/la kʁəvɛt/", "Hải sản nhỏ."],
  ["le crabe", "cua", "/lə kʁab/", "Hải sản có càng."],
  ["le saumon", "cá hồi", "/lə somɔ̃/", "'n' mũi. Cá thịt hồng."],
  ["le canard", "thịt vịt", "/lə kanaʁ/", "'d' câm."],
  ["la noix", "quả óc chó", "/la nwa/", "'x' câm. Cũng nghĩa hạt nói chung."],
  ["l'olive", "ô liu", "/lɔliv/", "Giống cái. Dầu ô liu phổ biến."],
  ["servir", "phục vụ / dọn ra", "/sɛʁviʁ/", "'servir le dîner' = dọn bữa tối."],
  ["commander", "gọi món / đặt hàng", "/kɔmɑ̃de/", "'commander un plat' = gọi món."],
  ["l'addition", "hóa đơn (nhà hàng)", "/ladisjɔ̃/", "'l'addition, s'il vous plaît' = tính tiền."],
  ["le serveur", "bồi bàn (nam)", "/lə sɛʁvœʁ/", "Nữ: 'la serveuse'."],
  ["le plat", "món ăn / đĩa lớn", "/lə pla/", "'t' câm. 'plat principal' = món chính."],
  ["le déjeuner d'affaires", "bữa trưa công việc", "/lə deʒœne dafɛʁ/", "Ăn trưa bàn chuyện làm ăn."],
  ["la boisson", "đồ uống", "/la bwasɔ̃/", "Thức uống nói chung."],
  ["mûr", "chín (trái cây)", "/myʁ/", "Trái cây sẵn ăn."],
  ["cru", "sống (chưa nấu)", "/kʁy/", "'poisson cru' = cá sống."],
  ["bouillir", "đun sôi / luộc", "/bujiʁ/", "Nấu trong nước sôi."],
];

// ===== French_Basic_Home (fr-FR) — 100 house & home words =====
const frenchBasicHome: Card4[] = [
  ["le toit", "mái nhà", "/lə twa/", "'t' câm. Phần che trên cùng."],
  ["le mur", "bức tường", "/lə myʁ/", "'au mur' = trên tường."],
  ["le sol", "sàn nhà / mặt đất", "/lə sɔl/", "Mặt dưới chân."],
  ["le plafond", "trần nhà", "/lə plafɔ̃/", "'d' câm. Mặt trên phòng."],
  ["l'escalier", "cầu thang", "/lɛskalje/", "Giống đực."],
  ["la porte d'entrée", "cửa chính", "/la pɔʁt dɑ̃tʁe/", "Cửa ra vào nhà."],
  ["le jardin", "khu vườn", "/lə ʒaʁdɛ̃/", "'n' mũi."],
  ["le garage", "nhà để xe", "/lə ɡaʁaʒ/", "Nơi đậu xe hơi."],
  ["la chambre", "phòng ngủ", "/la ʃɑ̃bʁ/", "'chambre à coucher' = phòng ngủ."],
  ["la salle de bains", "phòng tắm", "/la sal də bɛ̃/", "Nơi tắm rửa."],
  ["les toilettes", "nhà vệ sinh", "/le twalɛt/", "Luôn số nhiều."],
  ["le salon", "phòng khách", "/lə salɔ̃/", "Nơi tiếp khách."],
  ["la salle à manger", "phòng ăn", "/la sal a mɑ̃ʒe/", "Phòng đặt bàn ăn."],
  ["la cuisine", "nhà bếp", "/la kɥizin/", "Nơi nấu nướng."],
  ["les meubles", "đồ nội thất", "/le mœbl/", "Bàn ghế tủ giường."],
  ["le canapé", "ghế sô pha", "/lə kanape/", "Ghế dài phòng khách."],
  ["l'étagère", "kệ / giá", "/letaʒɛʁ/", "Giống cái. Để sách, đồ."],
  ["le tiroir", "ngăn kéo", "/lə tiʁwaʁ/", "Hộc kéo trong tủ."],
  ["l'armoire", "tủ quần áo", "/laʁmwaʁ/", "Giống cái. Tủ lớn."],
  ["le miroir", "cái gương", "/lə miʁwaʁ/", "Soi để nhìn mình."],
  ["la lampe", "đèn", "/la lɑ̃p/", "Đèn bàn hoặc đứng."],
  ["le rideau", "rèm cửa", "/lə ʁido/", "Số nhiều 'rideaux'."],
  ["le tapis", "tấm thảm", "/lə tapi/", "'s' câm. Trải sàn."],
  ["l'oreiller", "cái gối", "/lɔʁeje/", "Giống đực. Kê đầu khi ngủ."],
  ["la couverture", "cái chăn / mền", "/la kuvɛʁtyʁ/", "Đắp cho ấm."],
  ["le drap", "ga giường", "/lə dʁa/", "'p' câm."],
  ["la serviette", "khăn / khăn tắm", "/la sɛʁvjɛt/", "Cũng nghĩa 'cặp tài liệu'."],
  ["l'évier", "bồn rửa (bếp)", "/levje/", "Giống đực. Rửa bát."],
  ["la douche", "vòi sen / tắm", "/la duʃ/", "'prendre une douche' = tắm vòi sen."],
  ["le robinet", "vòi nước", "/lə ʁɔbinɛ/", "'t' câm."],
  ["la cuisinière", "bếp lò / nữ đầu bếp", "/la kɥizinjɛʁ/", "Hai nghĩa tùy ngữ cảnh."],
  ["le four", "lò nướng", "/lə fuʁ/", "Nướng bánh, thịt."],
  ["le réfrigérateur", "tủ lạnh", "/lə ʁefʁiʒeʁatœʁ/", "Nói tắt 'le frigo'."],
  ["le micro-ondes", "lò vi sóng", "/lə mikʁoɔ̃d/", "Hâm nóng nhanh."],
  ["le lave-vaisselle", "máy rửa bát", "/lə lav vɛsɛl/", "'lave' (rửa) + 'vaisselle' (chén bát)."],
  ["le lave-linge", "máy giặt", "/lə lav lɛ̃ʒ/", "'linge' = đồ vải, quần áo."],
  ["le ventilateur", "cái quạt", "/lə vɑ̃tilatœʁ/", "Làm mát."],
  ["le chauffage", "hệ thống sưởi", "/lə ʃofaʒ/", "Làm ấm nhà."],
  ["la climatisation", "máy lạnh / điều hòa", "/la klimatizasjɔ̃/", "Nói tắt 'la clim'."],
  ["la télévision", "ti vi", "/la televizjɔ̃/", "Nói tắt 'la télé'."],
  ["la télécommande", "điều khiển từ xa", "/la telekɔmɑ̃d/", "Bấm điều khiển TV."],
  ["l'horloge", "đồng hồ (treo)", "/lɔʁlɔʒ/", "'h' câm, giống cái."],
  ["la clé", "chìa khóa", "/la kle/", "Cũng viết 'clef'."],
  ["la serrure", "ổ khóa", "/la seʁyʁ/", "Lỗ tra chìa."],
  ["l'interrupteur", "công tắc", "/lɛ̃teʁyptœʁ/", "Bật/tắt đèn."],
  ["la prise", "ổ cắm điện", "/la pʁiz/", "Cắm phích vào."],
  ["l'ampoule", "bóng đèn", "/lɑ̃pul/", "Giống cái."],
  ["la bougie", "cây nến", "/la buʒi/", "Thắp sáng bằng lửa."],
  ["le balai", "cây chổi", "/lə balɛ/", "Quét nhà."],
  ["le seau", "cái xô", "/lə so/", "Số nhiều 'seaux'. Đựng nước."],
  ["la poubelle", "thùng rác", "/la pubɛl/", "Đựng rác."],
  ["le savon", "xà phòng", "/lə savɔ̃/", "Rửa cho sạch."],
  ["propre", "sạch", "/pʁɔpʁ/", "Cũng nghĩa 'của riêng'."],
  ["sale", "bẩn", "/sal/", "Trái nghĩa 'propre'."],
  ["ranger", "dọn gọn / sắp xếp", "/ʁɑ̃ʒe/", "Cất đồ đúng chỗ."],
  ["balayer", "quét", "/baleje/", "Quét sàn bằng chổi."],
  ["laver", "rửa / giặt", "/lave/", "'se laver' = tắm rửa."],
  ["sécher", "làm khô / sấy", "/seʃe/", "Trái nghĩa 'mouiller'."],
  ["mouillé", "ướt", "/muje/", "Bị thấm nước."],
  ["réparer", "sửa chữa", "/ʁepaʁe/", "Làm cho hoạt động lại."],
  ["construire", "xây dựng", "/kɔ̃stʁɥiʁ/", "Xây nhà."],
  ["peindre", "sơn / vẽ", "/pɛ̃dʁ/", "'peindre le mur' = sơn tường."],
  ["déménager", "chuyển nhà", "/demenaʒe/", "Dời đến nhà mới."],
  ["louer", "thuê / cho thuê", "/lwe/", "'louer un appartement' = thuê căn hộ."],
  ["l'appartement", "căn hộ", "/lapaʁtəmɑ̃/", "Giống đực."],
  ["le voisin", "hàng xóm (nam)", "/lə vwazɛ̃/", "Nữ: 'la voisine'."],
  ["l'adresse", "địa chỉ", "/ladʁɛs/", "Giống cái. Nơi ở."],
  ["la cour", "cái sân", "/la kuʁ/", "Sân quanh nhà."],
  ["le balcon", "ban công", "/lə balkɔ̃/", "Phần nhô ra tầng cao."],
  ["la cave", "tầng hầm / hầm rượu", "/la kav/", "Dưới mặt đất, để rượu."],
  ["le grenier", "gác mái", "/lə ɡʁənje/", "Dưới mái nhà."],
  ["le couloir", "hành lang", "/lə kulwaʁ/", "Lối đi nối phòng."],
  ["le bureau", "bàn làm việc / văn phòng", "/lə byʁo/", "Hai nghĩa. Số nhiều 'bureaux'."],
  ["le placard", "tủ tường / tủ chén", "/lə plakaʁ/", "'d' câm."],
  ["la casserole", "cái nồi", "/la kasʁɔl/", "Nấu canh, hầm."],
  ["la poêle", "cái chảo", "/la pwal/", "Chiên, rán."],
  ["la bouilloire", "ấm đun nước", "/la bujwaʁ/", "Đun nước sôi."],
  ["le grille-pain", "máy nướng bánh mì", "/lə ɡʁij pɛ̃/", "'grille' (nướng) + 'pain' (bánh)."],
  ["le fil", "dây / sợi", "/lə fil/", "'fil électrique' = dây điện."],
  ["le tuyau", "đường ống", "/lə tɥijo/", "Dẫn nước. Số nhiều 'tuyaux'."],
  ["la sonnette", "chuông cửa", "/la sɔnɛt/", "Bấm báo có khách."],
  ["le paillasson", "thảm chùi chân", "/lə pajasɔ̃/", "Đặt trước cửa."],
  ["la pièce", "căn phòng / đồng xu", "/la pjɛs/", "Cũng nghĩa 'mảnh, vở kịch'."],
  ["l'étage", "tầng (lầu)", "/letaʒ/", "Giống đực. 'premier étage' = tầng 1 (lầu 1)."],
  ["le rez-de-chaussée", "tầng trệt", "/lə ʁe də ʃose/", "Tầng ngang mặt đất."],
  ["confortable", "thoải mái", "/kɔ̃fɔʁtabl/", "Dễ chịu khi dùng."],
  ["l'aspirateur", "máy hút bụi", "/laspiʁatœʁ/", "Giống đực. Hút bụi sàn."],
  ["le fer à repasser", "bàn ủi", "/lə fɛʁ a ʁəpase/", "'fer' (sắt) + 'repasser' (ủi)."],
  ["la vaisselle", "chén bát (bộ)", "/la vɛsɛl/", "'faire la vaisselle' = rửa bát."],
  ["le ménage", "việc nhà", "/lə menaʒ/", "'faire le ménage' = làm việc nhà."],
  ["la corbeille", "giỏ / sọt", "/la kɔʁbɛj/", "Đựng giấy, trái cây."],
  ["le coussin", "cái nệm tựa / gối tựa", "/lə kusɛ̃/", "'n' mũi. Đệm trên ghế."],
  ["le matelas", "nệm (giường)", "/lə matla/", "'s' câm. Nằm trên giường."],
  ["la couette", "chăn bông", "/la kwɛt/", "Chăn dày mùa đông."],
  ["la clôture", "hàng rào", "/la klotyʁ/", "Vây quanh sân."],
  ["le portail", "cổng lớn", "/lə pɔʁtaj/", "'ail' đọc /aj/. Cổng vào sân."],
  ["la boîte aux lettres", "hộp thư", "/la bwat o lɛtʁ/", "Nhận thư từ."],
  ["le déménagement", "việc chuyển nhà", "/lə demenaʒmɑ̃/", "Danh từ của 'déménager'."],
  ["le loyer", "tiền thuê nhà", "/lə lwaje/", "Trả hàng tháng."],
];

async function seedDeck(deckName: string, lang: string, cards: Card4[]) {
  const deck = await prisma.deck.upsert({
    where: { name: deckName },
    update: {},
    create: { name: deckName },
  });

  const existing = new Set(
    (
      await prisma.card.findMany({
        where: { deckId: deck.id },
        select: { word: true },
      })
    ).map((c) => c.word.toLowerCase())
  );

  let added = 0;
  let skipped = 0;
  let i = 0;
  for (const [word, meaning, ipa, explanation] of cards) {
    if (existing.has(word.toLowerCase())) {
      skipped++;
      continue;
    }
    await prisma.card.create({
      data: {
        word,
        meaning,
        ipa,
        explanation,
        authorName: "WordPool",
        color: COLORS[i % COLORS.length],
        lang,
        deckId: deck.id,
      },
    });
    existing.add(word.toLowerCase());
    added++;
    i++;
  }
  console.log(`${deckName}: +${added} added, ${skipped} already there (total ${cards.length})`);
}

async function main() {
  await seedDeck("English_Basic_Life", "en-US", englishBasicLife);
  await seedDeck("English_Basic_Food", "en-US", englishBasicFood);
  await seedDeck("English_Basic_Home", "en-US", englishBasicHome);
  await seedDeck("English_Basic_Body", "en-US", englishBasicBody);
  await seedDeck("English_Inter_Work", "en-US", englishInterWork);
  await seedDeck("English_Inter_Travel", "en-US", englishInterTravel);
  await seedDeck("English_Inter_Emotion", "en-US", englishInterEmotion);
  await seedDeck("English_Advanced_Business", "en-US", englishAdvancedBusiness);
  await seedDeck("English_Advanced_Academic", "en-US", englishAdvancedAcademic);
  await seedDeck("English_Advanced_Idioms", "en-US", englishAdvancedIdioms);
  await seedDeck("French_Basic_Life", "fr-FR", frenchBasicLife);
  await seedDeck("French_Basic_Food", "fr-FR", frenchBasicFood);
  await seedDeck("French_Basic_Home", "fr-FR", frenchBasicHome);
}

main()
  .then(() => prisma.$disconnect())
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
